### ISSUE TITLE
Misplaced sentence?

### ISSUE THREAD

**Issue by Hansonaplane** [MicrosoftDocs/SCCMdocs#1004]
"The risk of clients failing to connect to servers if they can't locate the CRL" - how does this fit in with the rest? This is not a requirement...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 799bac51-7861-7177-7bf6-db971d9dc6e0
* Version Independent ID: fa0ab454-93ed-062c-fac2-70bea751d5c2
* Content: [Plan for security - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/security/plan-for-security#BKMK_PlanningForCRLs)
* Content Source: [sccm/core/plan-design/security/plan-for-security.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/security/plan-for-security.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Hansonaplane for the feedback. I just reviewed this article recently, and admit it's a little confusing at times. 

This part is talking about business/security requirements. The need to enable CRL checking is greater than the risk of clients failing to connect. That list is kind of a weird way to present pros/cons. If you enable CRL, processing and connections may be slower, and some clients may fail to connect. But enabling CRL might be a business requirement, in which case you need to understand those possible outcomes. 

I'll keep this open to take another run at rewording that part.

**Comment by v-maudel** [comment]
Hi @aczechowski , Could you please let me know if there is an ETA for the change of the sentence into the file?

Regards.

**Comment by v-makoud** [comment]
Hi @aczechowski , Could you please let me know if there is an ETA for the change of the sentence into the file?

Regards.

**Comment by aczechowski** [comment]
There was a change to this last year, but I'm not sure it really solves the problem. But I'm not sure we'll likely get to making broader changes to this article. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
