### ISSUE TITLE
Missing Property: "Type" is not defined

### ISSUE THREAD

**Issue by hkystar35** [MicrosoftDocs/SCCMdocs#1006]
Troubleshooting a recent TS Deployment, I queried the CCM_Program class properties for that deployment and found `Type = 3`. No Property of Type is listed under this class, nor a description of the numerical values' meanings.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2447f2-eae6-046f-4a1f-c09d8a552c13
* Version Independent ID: 79cf01e1-767e-b8d8-1d39-1b33508c21b7
* Content: [CCM_Program Class - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/core/clients/sdk/ccm_program-client-wmi-class)
* Content Source: [sccm/develop/reference/core/clients/sdk/ccm_program-client-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/core/clients/sdk/ccm_program-client-wmi-class.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @hkystar35 for the feedback

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
