### ISSUE TITLE
Configuration Manager registry key is wrong

### ISSUE THREAD

**Issue by evandimsby** [MicrosoftDocs/SCCMdocs#1023]
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration\CDNBaseUrl is incorrect. Changing that value to any of the 4 releases will not receive deployments. There is a different registry key, HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration\UpdateChannel, which will effect the deployments from SCCM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1da48af-4783-bd17-67f3-f265df93503f
* Version Independent ID: 17432b22-04cb-f47f-1634-e5b7fc99c37d
* Content: [Manage Office 365 ProPlus updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/manage-office-365-proplus-updates#change-the-update-channel-after-you-enable-office-365-clients-to-receive-updates-from-configuration-manager)
* Content Source: [sccm/sum/deploy-use/manage-office-365-proplus-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/manage-office-365-proplus-updates.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @evandimsby for the feedback, I'm investigating.

**Comment by aczechowski** [comment]
Yes, this information is inaccurate. The recommended way to change channels when O365 is managed by SCCM is either with GPO (most reliable) or use ODT.

**Comment by RussellBlunt** [comment]
I found that the advice in the document above about changing channels not to work either. It was successful in moving computers from Semi-Annual to Monthly - but not back again. We had the reg keys deployed via SCCM baseline to about 1500 workstations. Unfortunately we have had about 100 computers drift to monthly channel from semi annual and was looking at a way to reset back.
I'm also fairly sure that the GPO setting for O365 channel will only effect computers that get updated via Office CDN not SCCM. However, you can set this to your preferred channel and run the command:
“C:\Program Files\Common Files\Microsoft Shared\ClickToRun\OfficeC2RClient.exe /update user”

Workstation will connect to Office CDN - check the GPO setting and install that channel. I presume SCCM would then take management back over if you have the other GPO set that determine management.

**Comment by arowswell** [comment]
How is this document still not up to date?!

As Jeff said the UpdateChannel registry key also must be updated to the new channel.

Prior to this month, we could leave the channel as Semi-Annual and still deploy Semi-Annual (Targeted) updates to select computers. Very disappointing. This means we'll have to setup another GPO for less than 5 users in an organization of 3000.

**Comment by aczechowski** [comment]
@arowswell we're working with the Office content team to help, so should have some updates in the near future.

**Comment by marendaweth** [comment]
Any updates on this matter yet?

**Comment by arowswell** [comment]
So after further testing CDNBaseUrl and/or UpdateChannel appear to rely on the HKLM\software\policies\microsoft\office\16.0\common\officeupdate!updatebranch key. Whatever this key is set to, it will change CDNBaseUrl and/or UpdateChannel to the corresponding setting the next time the O365 auto update scheduled task runs. 

This is truly disgraceful documentation from Microsoft. I'm dealing with thousands of computers that are reporting the update is not required because you guys can't properly document what settings we need to configure.

**Comment by marendaweth** [comment]
Hmm, wonder if the ADMX policy Update Channel needs to be set to disabled then and adding an GPP in an higher link order GPO to be able to switch channel from Office 365 to Office 2019 using GPOs then..? :S

**Comment by arowswell** [comment]
Further testing... I manually changed my updatebranch key again back to Deferred, and tried to manually trigger the scheduled task, the CDNBaseUrl and UpdateChannel are not getting updated. I'm stumped. I think I'm going to have the GPO tell it to go to SCCM for updates but only set Deferred channel ONCE. Then use baseline items to remediate the CDNBaseUrl and UpdateChannel. More baseline items for Pilot to change updatebranch to FirstReleaseDeferred and remediate CDNBaseUrl and UpdateChannel to that corresponding URL.

**Comment by JvilleJD** [comment]
@RussellBlunt I tried to go from 1905 monthly to Semi Annual 1902, and regardless of setting the CDNBaseURL, verifying GPOs, running OfficeC2RClient.exe /update user, or even setup.exe /configure, it would never "downgrade". It would show as 1905 Monthly, and report back to SCCM as 1905 monthly. Even allowing updates to O365 and removing OfficeMgmtCOM, I could never get it to work.

I ended up creating a new 1902 Semi-Annual Targeted using ODT, uninstalled 1905 Monthly, installed the 1902 SA-Targeted and it updates correctly via SCCM.

It seems that the issue is outside of SCCM and is mainly on O365. You can easily move from Semi-Annual to Monthly, but moving back is nigh impossible.

**Comment by mhouston100** [comment]
Is there any movement on this at all, I'm struggling to see any consistentcy with changing the setting 'forward' even (i.e from Semi-Annual to Monthly).

**Comment by mestew** [comment]
The Office documentation has been recently updated to reflect how to change channel. I am changing this section to defer to their documentation as the authority on the subject. Thanks for the feedback!
