### ISSUE TITLE
Update SCCM client for OpenSsl 1.1.*

### ISSUE THREAD

**Issue by ummone67** [MicrosoftDocs/SCCMdocs#1045]
At new Ubuntu 18.04 bionic release it uses openssl 1.1.*, so when I tried to isntall SCCM agent I've faced with the following issue:

This system's OpenSSL version: 1.1.0g 
Supported versions: 0.9.8*, 1.0.*

Could you please update SCCM source code to use new openssl package version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec20e40b-461f-9f32-7b77-d06a415fd487
* Version Independent ID: 608ac70d-0bda-4fc5-081a-c689e24f33cd
* Content: [Deploy Mac clients - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/deploy/deploy-clients-to-macs)
* Content Source: [sccm/core/clients/deploy/deploy-clients-to-macs.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/deploy-clients-to-macs.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ummone67 for taking the time to provide feedback on Configuration Manager! This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. 

I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by aczechowski** [comment]
Also, the page you reference is regarding Mac client. If you're actually referring to our Linux client, please note that it is deprecated: 
- [Removed and deprecated items for Configuration Manager clients](https://docs.microsoft.com/sccm/core/plan-design/changes/deprecated/removed-and-deprecated-client)  
- [Deprecation announcement for Linux and Unix client support](https://docs.microsoft.com/sccm/core/plan-design/changes/whats-new-in-version-1802#deprecation-announcement-for-linux-and-unix-client-support)
