### ISSUE TITLE
UseClusterPercentage values not documented

### ISSUE THREAD

**Issue by LeviStevens** [MicrosoftDocs/SCCMdocs#1049]
Should document the possible values.  1 = Percentage, 2 = Number of Machines , 3 = Specific Order

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afb307a0-90fb-8e75-736a-93b0f9efbfc0
* Version Independent ID: cab921d4-db16-d217-a29d-449508170674
* Content: [SMS_CollectionSettings Class - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/core/clients/collections/sms_collectionsettings-server-wmi-class)
* Content Source: [sccm/develop/reference/core/clients/collections/sms_collectionsettings-server-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/core/clients/collections/sms_collectionsettings-server-wmi-class.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by LeviStevens** [comment]
I will make an attempt. ;)

Levi Stevens
425-941-0602

On Nov 29, 2018, at 1:26 PM, Aaron Czechowski <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks @LeviStevens<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLeviStevens&data=02%7C01%7C%7Ca72a8c6f883a48408fc308d656415f00%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636791236091542659&sdata=vKOYxLUozXTcewB0Yc2P2Qvz51Xqlf95AeTOUBMkivg%3D&reserved=0> for the feedback. To which property are you referring?
Also, if you're willing and interested in submitting this yourself, I'm happy to review and help. For more information, see How to contribute<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fsccm%2Fcore%2Funderstand%2Fuse-docs%23bkmk_contribute&data=02%7C01%7C%7Ca72a8c6f883a48408fc308d656415f00%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636791236091542659&sdata=Vcttfu%2BWq7ncpqVExhK7QuhHR8za6ma1oH7QHXbh8PM%3D&reserved=0>.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.

I'm also wondering if these properties are deprecated with the introduction of orchestration groups
