### ISSUE TITLE
ADR execution on SUP sync schedule

### ISSUE THREAD

**Issue by miaminemo** [MicrosoftDocs/SCCMdocs#1070]
PSS helped us to identify that when you select the option for ADR to run whenever the SUP performs a synchronization , it will only run if changes to the catalog are detected - new, removed, modified updates. 

The result is that if a job runs on day 0 for an update, where required &gt; 0 is not true, when the job runs the next day if no new updates are identified the job will not run and properly download any updates that have since been reported as required. If you want this behavior, you need to set the ADR to run on a defined schedule. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc1bc8d-2e4b-650b-7644-84e5790e4630
* Version Independent ID: 9488c8c6-c912-1667-db02-f8a29f5c2023
* Content: [Automatically deploy software updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/automatically-deploy-software-updates#feedback)
* Content Source: [sccm/sum/deploy-use/automatically-deploy-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/automatically-deploy-software-updates.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by mestew** [comment]
Thanks again for the feedback. We moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
