### ISSUE TITLE
APIs to create SCUP catalog

### ISSUE THREAD

**Issue by tathvik** [MicrosoftDocs/SCCMdocs#1075]
Can you please API documentation to create .xml, .sdp and .json files that are part of the .cab (SCUP)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9deb71e4-f72f-aaba-4460-36612e4c95dc
* Version Independent ID: 2ec98bb0-c23b-d2fe-ad62-6df797f1a4ad
* Content: [Updates Publisher - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/tools/updates-publisher)
* Content Source: [sccm/sum/tools/updates-publisher.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/tools/updates-publisher.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @tathvik for the feedback. I'll investigate.

**Comment by aczechowski** [comment]
Right now there aren't any SCCM-specific APIs for third-party updates. This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. 

We use a WSUS API to generate and parse the SDP files. For more information, see [SoftwareDistributionPackage Class](https://docs.microsoft.com/previous-versions/windows/desktop/bb530824(v=vs.85)). The XML file is static text, so you can just look at an existing catalog. Similarly with the JSON, which is optional for better performance on import, look at an existing CAB file to see the general formatting. 

I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by tathvik** [comment]
Thanks Aaron!
As suggested, I've posted the same ask on the product's feedback page. Hoping for things to work out.

**Comment by tathvik** [comment]
Aaron, I had one other question whether there were any APIs available to import a SCUP (.cab) file into the SCUP tool and SCCM?

**Comment by aczechowski** [comment]
SCUP doesn't have any APIs and isn't scriptable. Sorry

**Comment by Staja** [comment]
@tathvik https://docs.microsoft.com/en-us/previous-versions/windows/desktop/bb902486(v=vs.85)
Could be used third SCCM-CB/MCEM's new Third Party Updates feature.
