### ISSUE TITLE
Terms "pre-production" and "production" might not be best in this context

### ISSUE THREAD

**Issue by davidpaMSFT** [MicrosoftDocs/SCCMdocs#1128]
Understanding this feedback has both product (UI) and doc implications...

Although we use term "piloting" in the package name, and there are references to term "staging" internally (database) as well, for UI/settings we are using term "pre-production". Althoug same "instance" of SCCM implementation/hierarchy can be used to manage multiple environments (development, QA, pre-production, production etc.) using term "pre-production" within the same instance of SCCM implementation/hierarchy can be confusing since it's technically still the same SCCM environment (whereas "pre-production" implies a different environement). This is especially confusing for customers who have separate/isolated SCCM instances/hierarchies managing their pre-production environements (DEV, QA, etc.). 

Therefore, the suggestion is to replace use of term "pre-production" and possibly "production" with different terms. One idea would be to allign them with Windows/Office and use terms "targeted' or "pilot" and "broad" or "main"

This way, customers with individual/isolated environments would all have a pilot and broad client deployment in each environment as opposed to an environment that is considered production having a pre-production (and production) client deployment and environments that are considered pre-production having (pre-production and) production client deployment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c6ecf9a-a586-1f34-5c41-b41081cb5e55
* Version Independent ID: e29256cd-00f0-0dc9-88ea-988425858d64
* Content: [Test client upgrades pre-production collection - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/upgrade/test-client-upgrades)
* Content Source: [sccm/core/clients/manage/upgrade/test-client-upgrades.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/upgrade/test-client-upgrades.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @davidpaMSFT for the feedback. That's generally product feedback, and I want to make sure it gets directly into the hands of the engineering team. See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress.

I usually close product feedback issues as it's not actionable for docs. In this instance, the UI uses the "pre-production" term, and for best searchability and reference I want to make sure those terms are included in this article. But if you think it warrants a tip to better explain this concept, then I'll keep this issue open for that purpose.

**Comment by davidpaMSFT** [comment]
I don't think we need to change anything in the docs unless the UI changes. No need to keep this issue open. Thanks.
