### ISSUE TITLE
EvidenceSource not clear

### ISSUE THREAD

**Issue by LeviStevens** [MicrosoftDocs/SCCMdocs#1136]
The values are 25 characters.  Please specify for each character, which property it maps to. E.g. 0 = Product Name, 1 = Product Version, etc.  There is some information shared by MSFT contractor who looked at the source code, but the information is incomplete and should be in the documentation.  https://social.technet.microsoft.com/Forums/systemcenter/en-US/b2eb460b-1b99-494e-abe9-570bff377efc/meaning-of-values-in-vgsinstalledsoftwareevidencesource0?forum=configmgrgeneral

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19fe162-e24a-64b5-c0a9-b6cf00f30993
* Version Independent ID: a4e7a0d3-79d2-de54-4ac6-79423804593b
* Content: [SMS_InstalledSoftware Class - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/core/clients/client-classes/sms_installedsoftware-client-wmi-class#feedback)
* Content Source: [sccm/develop/reference/core/clients/client-classes/sms_installedsoftware-client-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/core/clients/client-classes/sms_installedsoftware-client-wmi-class.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
