### ISSUE TITLE
SQL Native Client and other ConfigMgr roles

### ISSUE THREAD

**Issue by josesonic** [MicrosoftDocs/SCCMdocs#1150]
Since it says "Applies to: Central administration site, primary site, secondary site", is it safe to assume there is no need to also update the SQL Native Client on ConfigMgr servers with other roles, such as Distribution Point, Management Point, Reporting Services Point, Software Update Point, etc. ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db678f94-700f-ad35-9fdc-d165893b5373
* Version Independent ID: 2ee761db-4b3b-6fa0-c195-ad85ebbac70d
* Content: [Prerequisite checks - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/list-of-prerequisite-checks#sql-native-client)
* Content Source: [sccm/core/servers/deploy/install/list-of-prerequisite-checks.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/list-of-prerequisite-checks.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Correct, SCCM doesn't do the work itself because updating the SQL Native Client can require a restart, and that would break the SCCM setup flow. Thus the warning and manual prereq. 

As for the site roles that have it, the list is longer than I anticipated, I'm glad I asked:
- SMS SQL Server
- SMS Site Server
- SMS Management Point
- SMS Device Management Point
- SMS State Migration Point
- SMS Provider
- SMS Software Update Point
- SMS Multicast Service Point
- AI Update Service Point
- SMS SRS Reporting Point
- SMS Application Web Service
- SMS Enrollment Server
- SMS Endpoint Protection Point
- SMS Dmp Connector
- SMS Notification Server
- SMS Certificate Registration Point
- Data Warehouse Service Point

**Comment by aczechowski** [comment]
This issue is closed because I made a bunch of revisions to the article, including adding the list of roles for this check. The changes should publish live tomorrow (Wednesday 3 April) around 11am Pacific time.
