### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by amank143** [MicrosoftDocs/SCCMdocs#1153]
Please provide the examples that how can we use the above wmi class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc349cbc-4591-b718-1720-4455199d63a5
* Version Independent ID: 27c17aaf-b7a1-7405-0330-c820fc6df91f
* Content: [SMS_AppDeploymentAssetDetails Class - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/apps/sms_appdeploymentassetdetails-server-wmi-class)
* Content Source: [sccm/develop/reference/apps/sms_appdeploymentassetdetails-server-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/apps/sms_appdeploymentassetdetails-server-wmi-class.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
