### ISSUE TITLE
Could be improved by providing int values for SourceId's

### ISSUE THREAD

**Issue by JuliusPIV** [MicrosoftDocs/SCCMdocs#1174]
Hi Team.  The CreateRelationship Method in the SMS_UserMachineRelationship Server WMI Class could be improved by providing the integer values for the SourceId's.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af80898f-39e4-92c1-5541-0af9cfb7abf4
* Version Independent ID: d253a90f-9c3d-3e6c-f21a-5e432fe1ccf5
* Content: [CreateRelationship Method - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/core/clients/manage/createrelationship-method-in-class-sms_usermachinerelationship)
* Content Source: [sccm/develop/reference/core/clients/manage/createrelationship-method-in-class-sms_usermachinerelationship.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/core/clients/manage/createrelationship-method-in-class-sms_usermachinerelationship.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
