### ISSUE TITLE
Anytime you talk about Ports and Firewall rules, y 

### ISSUE THREAD

**Issue by scarneol** [MicrosoftDocs/SCCMdocs#1177]
Anytime you talk about Ports and Firewall rules, you should always include the direction of traffic.

-- &gt; Indicates that one computer initiates communication and the other computer always responds
&lt; -- &gt; Indicates that either computer can initiate communication  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db8471b5-b50c-b319-c91f-63e1079bed7a
* Version Independent ID: fcaf4dea-8abe-9816-5e6f-77c6cc8a166d
* Content: [Windows client firewall and port settings - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/deploy/windows-firewall-and-port-settings-for-clients#ports-used-during-configuration-manager-client-deployment)
* Content Source: [sccm/core/clients/deploy/windows-firewall-and-port-settings-for-clients.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/windows-firewall-and-port-settings-for-clients.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
