### ISSUE TITLE
Summary Type info missing

### ISSUE THREAD

**Issue by Skatterbrainz** [MicrosoftDocs/SCCMdocs#1178]
What do SummaryType values 1 and 2 denote?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc9994ef-1281-f93c-f899-2c10515eb188
* Version Independent ID: 6e1c3716-049d-ed07-38cc-eed5394eb501
* Content: [SMS_DeploymentSummary Class - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/apps/sms_deploymentsummary-server-wmi-class)
* Content Source: [sccm/develop/reference/apps/sms_deploymentsummary-server-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/apps/sms_deploymentsummary-server-wmi-class.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Skatterbrainz for the feedback. We unfortunately have a large backlog of work for the SDK content, but are looking at ways to improve it in the future.

**Comment by Skatterbrainz** [comment]
I understand.  Docs must be a huge responsibility to manage.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
