### ISSUE TITLE
Update Port Diagram for Current Branch

### ISSUE THREAD

**Issue by scarneol** [MicrosoftDocs/SCCMdocs#1179]
A lot of us liked this doc (see link below) from the SCCM 2007 days which has a diagram that shows all the connections between the servers, server roles, client, console, cloud...etc. Really helps to illustrate the complexity of the SCCM environment.

https://docs.microsoft.com/en-us/previous-versions/system-center/configuration-manager-2007/bb632618(v=technet.10)

There have been quite a few role changes since this diagram was created and was hoping Microsoft would update it and include it in this thread. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f658ee4b-d051-0d7c-4656-19a846908469
* Version Independent ID: 3478e881-199c-f0c4-b218-0dd609eb0427
* Content: [Ports used for connections - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/ports)
* Content Source: [sccm/core/plan-design/hierarchy/ports.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/ports.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by shiyuxiang520** [comment]
Scarneol's idea is very good, agree to update it!
Hope administrators could see and add it, thank you for your efforts!

Best regards,
Yuxiang

**Comment by aczechowski** [comment]
Thank you @scarneol for the great idea! I too love that old diagram. I have an idea about how we might be able to resource this in the near future. Stay tuned.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don’t think we’ll realistically ever address. If you’re passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
