### ISSUE TITLE
LastSyncState not described well?

### ISSUE THREAD

**Issue by Skatterbrainz** [MicrosoftDocs/SCCMdocs#1181]
is there any additional info on LastSyncState?  One of my servers shows 6702 but no idea what that means.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f00500b5-0ea6-c05e-f16b-4246901a8118
* Version Independent ID: ccdc3c42-d384-37b3-75b5-ead22f34aab2
* Content: [SMS_SUPSyncStatus Class - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/sum/sms_supsyncstatus-server-wmi-class)
* Content Source: [sccm/develop/reference/sum/sms_supsyncstatus-server-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/sum/sms_supsyncstatus-server-wmi-class.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
