### ISSUE TITLE
IIS not installed on data warehouse - how to create self-signed cert

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/SCCMdocs#1187]
What if IIS isn't installed on the server that hosts the data warehouse point? I think it'd be good to have steps to create the self-signed cert without using IIS, but also assume this workaround won't be needed at all after this bug is fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a4274db-5f5b-c169-c69e-68146e92836f
* Version Independent ID: a28966e9-88cc-6910-c270-7f14818f832a
* Content: [Data warehouse - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/data-warehouse)
* Content Source: [sccm/core/servers/manage/data-warehouse.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/data-warehouse.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
