### ISSUE TITLE
SQL Server change tracking cleanup

### ISSUE THREAD

**Issue by Garthmj** [MicrosoftDocs/SCCMdocs#1191]
How do you know when the spDiagChangeTracking SP is done? it great that you can see stuff within vLogs but how do you know when it is done? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db678f94-700f-ad35-9fdc-d165893b5373
* Version Independent ID: 2ee761db-4b3b-6fa0-c195-ad85ebbac70d
* Content: [Prerequisite checks - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/list-of-prerequisite-checks#bkmk_changetracking)
* Content Source: [sccm/core/servers/deploy/install/list-of-prerequisite-checks.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/list-of-prerequisite-checks.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Revised title for the specific check in question.

Based on some additional info from @Garthmj, it looks like this may require some additional time for a maintenance task to run. I'm trying to confirm the details with engineering.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
