### ISSUE TITLE
What are the AvailabilityState options?

### ISSUE THREAD

**Issue by Skatterbrainz** [MicrosoftDocs/SCCMdocs#1198]
I see values 0,1,2,3, and 4 but no explanation for them anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1601b2f1-500e-60d0-6411-6834adac3466
* Version Independent ID: 234656c4-800a-7746-5274-1bede1c4c7c5
* Content: [SMS_SiteSystemSummarizer Class - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/core/servers/manage/sms_sitesystemsummarizer-server-wmi-class)
* Content Source: [sccm/develop/reference/core/servers/manage/sms_sitesystemsummarizer-server-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/core/servers/manage/sms_sitesystemsummarizer-server-wmi-class.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by Skatterbrainz** [comment]
any update on this?

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
