### ISSUE TITLE
Add languages for Office 365 update downloads - specifically for proofing tools only

### ISSUE THREAD

**Issue by cfield80** [MicrosoftDocs/SCCMdocs#1202]
Hi,

the "Add languages for Office 365 update downloads" details the required steps to ensure SCCM will download the required content to service additional languages but is this for instances where the language is completely different, a language pack is installed and/or only proofing language has also been installed?

thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1da48af-4783-bd17-67f3-f265df93503f
* Version Independent ID: 17432b22-04cb-f47f-1634-e5b7fc99c37d
* Content: [Manage Office 365 ProPlus updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/manage-office-365-proplus-updates)
* Content Source: [sccm/sum/deploy-use/manage-office-365-proplus-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/manage-office-365-proplus-updates.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by danxavy** [comment]
This would help soooooo much. We have a monthly updates package that includes our company supported language packs but there are some countries that want their language pack which we cannot add as the package will become way to large to distribute globally. Adding some proofing tools would solve this to a point. Please add this function!

**Comment by miaminemo** [comment]
Danxavy - submit this through userVoice, you'll get more attention there than in these comments.

**Comment by mestew** [comment]
Thanks again for the feedback. We moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
