### ISSUE TITLE
.NET 4.5.2 required for sms_provider (1810)

### ISSUE THREAD

**Issue by chboeye** [MicrosoftDocs/SCCMdocs#1203]
As part of SCCM 1810, the sms_provider is now also installing the "somewhat" new provider using the following service : SCCMProviderGraph.exe.
Installation still ok but process will not be able to run and "sms_rest_provider" component will throw lots of error for not beeing able to lauch the "Administration service"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9070eb9b-0e5f-a877-e02e-2d1cea2a2b38
* Version Independent ID: df251762-f2d6-9f06-4fa9-ec5cea2cca0a
* Content: [Site prerequisites - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/site-and-site-system-prerequisites#bkmk_2012smsprovpreq)
* Content Source: [sccm/core/plan-design/configs/site-and-site-system-prerequisites.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/site-and-site-system-prerequisites.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @chboeye for the feedback. The new administrative service is currently only required for one scenario, [email notifications for app approvals](https://docs.microsoft.com/sccm/apps/deploy-use/app-approval#bkmk_email-approve). This scenario notes these prerequisites. Otherwise those errors are harmless.

**Comment by chboeye** [comment]
I understand what you mean and maybe I was a bit ahead of things because it will eventually become more important/mandatory (we all hope it will!), meaning this won't be a simple warning in the next version.
I was just pointing out the fact that it's not in the docs dedicated to global prerequisites for each role but it's fine for me. Case closed. :)

**Comment by aczechowski** [comment]
Let's keep it open. Still valid feedback. 😄 Three options/benefits to leaving it open:
1. When I next revise this article, I'll fix this issue. (I ma also get to it when I doc more on the admin service)
2. Someone in the community adds this prereq 😉 [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute)
3. Others who are reading the article can more easily see this open feedback

**Comment by aczechowski** [comment]
I made changes for this 1810 feature that will publish tomorrow, so the issue is closed.

**Comment by YanZeng1025** [comment]
We did search in SCCM 1810 Hotfix KB4488598 redist folder, and confirmed it contains .Net Framework 4.5.2 offline installation file, "NDP452-KB2901907-x86-x64-AllOS-ENU.exe".

We prefer to install .Net Framework 4.5.2 instead of 1810 hotfix KB4488598, to avoid longer outage and potential risk on SCCM database replication failure.
