### ISSUE TITLE
Clarify BDR vs delta replication

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#1209]
The section regarding binary differential replication (BDR) is misleading. Reference [comment](https://github.com/MicrosoftDocs/SCCMdocs/issues/1044#issuecomment-453457229) from @martinkupka on another issue. 

After discussion with engineering:

### Binary differential replication
- Our term for Windows “Remote Differential Compression”
- *Block*-level diffs
- Always enabled for apps
- Optional on legacy packages
- If a file already exists on the DP, and there’s a change, this is used to replicate the block-level change instead of the entire file. 

### Delta replication
- *File*-level diffs
- On by default, not configurable
- When a package changes, check for changes to the individual files instead of the entire package.
    - If a file changes, use BDR to do the work
    - If there’s a new file, copy the new file

I'll do a search across all of our content to see how we’re using these terms, and make sure I clarify. 

The admin console uses the BDR term  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff2f1985-822a-f9aa-8368-9abf85c50118
* Version Independent ID: 3401e963-f1cf-a15d-01f2-c1754a7d9336
* Content: [Content management fundamentals - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management#binary-differential-replication)
* Content Source: [sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by WattsG** [comment]
Thanks for taking a look at this one Aaron! I've been thinking about how I'd write it up to make the most sense of the two.  Back in 2007 it was always recommended to only use manual BDR for things like OSD (WIMs and ISOs) as there's a lot of processing overhead.  Not sure if processing overhead is still a thing with how far we've come either.  It didn't make sense to me that Software Update packages have the option since it's file level changes either, just as a side note.
