### ISSUE TITLE
Certificates: Enhanched https

### ISSUE THREAD

**Issue by ReneKierstein** [MicrosoftDocs/SCCMdocs#1212]
Do you have some information about the certificates used by "Enhanced https"
I miss information about the Cert types encryption level etc.

(admin edit: adding metadata for article link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cfc73c1-e15c-5dde-2a22-5cfc3eb7eb1c
* Version Independent ID: 50df732f-9232-74f6-f7d2-dda59c9b125b
* Content: [Enhanced HTTP - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/enhanced-http)
* Content Source: [sccm/core/plan-design/hierarchy/enhanced-http.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/enhanced-http.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ReneKierstein for the feedback. We'll look at adding some additional details on these certificates.

**Comment by torontojc** [comment]
If I'm not mistaken there are no certificates used in enhanced HTTP. Instead it uses token based authorization.

**Comment by aczechowski** [comment]
@ReneKierstein, we purposefully don't document the technical details of these certificates as they are managed and maintained by Configuration Manager. If you need such technical detail of how it works, then you probably should go the route of enabling PKI-based HTTPS support for the site and clients. 

I'll keep this issue open though, because in discussion with the engineering team, I'll add the following information after the two bullet point goals at the top of the article:

> All other client communication is over HTTP. Enhanced HTTP isn't the same as enabling client communication or a site system for HTTPS. 

p.s. @torontojc it's a form of token-based authentication that's used. That's just a level of technical detail that we purposefully didn't want to wade into for this article at this time. 😃 

FYI the site does generate certificates, the following paragraph is towards the end of the article:
> You can see these certificates in the Configuration Manager console. Go to the Administration workspace, expand Security, and select the Certificates node. Look for the SMS Issuing root certificate, as well as the site server role certificates issued by the SMS Issuing root.

**Comment by ReneKierstein** [comment]
Thnx for the update

**Comment by aczechowski** [comment]
This issue is closed because I made some changes to the article to add this note. The updated article will publish live tomorrow around 11am Pacific.
