### ISSUE TITLE
SCCM CB OS Upgrade

### ISSUE THREAD

**Issue by cbenammar** [MicrosoftDocs/SCCMdocs#1223]
[We'll need also to reinstall SMS_Provider from the reset command options.
I uninstalled BITS feature exiension, restarted the server then added it back,
after that I removed MP role and added it back]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71096754-a158-0c4f-9d87-6a0575139573
* Version Independent ID: 4e148fe9-9c18-228a-60ea-eecc081291e1
* Content: [Upgrade on-premises infrastructure - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/upgrade-on-premises-infrastructure)
* Content Source: [sccm/core/servers/manage/upgrade-on-premises-infrastructure.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/upgrade-on-premises-infrastructure.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
