### ISSUE TITLE
Configure auto-enrollment of devices to Intune - Step 4

### ISSUE THREAD

**Issue by adamfowlerit** [MicrosoftDocs/SCCMdocs#1230]
Not all tenants have that option as per forum thread below, and we were stuck for ages trying to work out why. As far as I can tell, newer tenants have it and if you don't, it's not needed?

https://social.technet.microsoft.com/Forums/en-US/2b01d554-8f1d-4333-9570-101d91ca1e6b/difference-between-intune-and-intune-enrollment-at-aad-gt-mdm-setting?forum=microsoftintuneprod

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f5f810-0397-1cb0-3dc8-ca3a06fce1da
* Version Independent ID: fb6d937b-7681-5a5c-0fb5-ac7fa5faf7b9
* Content: [Tutorial: Co-management path 1 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/comanage/tutorial-co-manage-clients)
* Content Source: [sccm/comanage/tutorial-co-manage-clients.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/comanage/tutorial-co-manage-clients.md)
* Product: **configuration-manager**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by jenyalex80** [comment]
Step 4 is incorrect. These devices are AD joined devices and for auto-enrollment to work as explained in Step4 the devices have to be AAD joined not AD joined. This section should be replaced with the steps the GPO method as given in this article: https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy

**Comment by aczechowski** [comment]
@adamfowlerit the response I got from the feature team to clarify those two options:
- “Microsoft Intune” is how Administrators configure MDM app for AAD, this is also how they can configure 3rd party.  
- “Microsoft Intune Enrollment” is specific AAD app that is created when MFA policies are applied for iOS and Android enrollment.  

@jenyalex80 - the auto-enrollment here is to Intune, so that when the device enrolls to Azure AD it automatically enrolls to Intune as well. The earlier sections in the article help you configure hybrid Azure AD, and then [Configure Client Settings to direct clients register with Azure AD](https://docs.microsoft.com/en-us/sccm/comanage/tutorial-co-manage-clients#configure-client-settings-to-direct-clients-register-with-azure-ad).

**Comment by adamfowlerit** [comment]
Interesting, not sure what MFA policies need to be applied specifically - but then the step should be adjusted to show that it's only needed if the option exists?


Thanks

Adam Fowler

________________________________

**Comment by aczechowski** [comment]
A submitted a change for this issue. It will publish live tomorrow (Wednesday) around 11:00 Pacific time.
