### ISSUE TITLE
Integrate information from Collection Evaluation Overview article

### ISSUE THREAD

**Issue by nano9g** [MicrosoftDocs/SCCMdocs#1237]
Please add the information that was covered in this now-defunct Collection Evaluation Overview blog post: https://blogs.technet.microsoft.com/scott/2017/09/13/collection-evaluation-overview-configuration-manager/
It did a great job of explaining the collection evaluation cycle and what factors could affect it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbccb59f-9513-3990-28b3-822f5cd44c69
* Version Independent ID: 89404c66-cedd-c696-a98a-c4ac8d062eb6
* Content: [Collections best practices - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/collections/best-practices-for-collections)
* Content Source: [sccm/core/clients/manage/collections/best-practices-for-collections.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/collections/best-practices-for-collections.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don’t think we’ll realistically ever address.

However, we do have a vendor team, I'm going to check with them if they can assist in migrating this content to docs. 😉
