### ISSUE TITLE
Custom icons not possible with Packages/Programs

### ISSUE THREAD

**Issue by Ringosystems** [MicrosoftDocs/SCCMdocs#1251]
You can only add custom icons to Applications, not packages.

**Comment by aczechowski** [comment]
Is there a specific article that you're referencing?

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
