### ISSUE TITLE
SupportID

### ISSUE THREAD

**Issue by Garthmj** [MicrosoftDocs/SCCMdocs#1254]
The SupportID is missing from this doc. Can this ID be used for my own purposes to identify sites? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45804e55-39f4-8929-f245-88b72e627ac2
* Version Independent ID: ccd9d1c5-e677-cac9-4219-0145e1a5e6a9
* Content: [SMS_Identification Class - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/core/servers/configure/sms_identification-server-wmi-class)
* Content Source: [sccm/develop/reference/core/servers/configure/sms_identification-server-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/core/servers/configure/sms_identification-server-wmi-class.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Garthmj for the feedback. We unfortunately have a large backlog of work for the PowerShell & SDK content, but are looking at ways to improve it in the future.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
