### ISSUE TITLE
Future Enhancements: Install Process and Reboot Handling

### ISSUE THREAD

**Issue by bryandam** [MicrosoftDocs/SCCMdocs#1296]
Great work team.  When you heal up and can stomach the thought of revisiting this I have a suggestion.  It would be helpful to expand on the actually installation process as it loops through the updates.  If for no other reason to explain what the double reboot problem is and why and how to use the SMSTSWaitForSecondReboot task sequence variable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65b66efc-196e-af74-3b6c-9ce815c1e6e3
* Version Independent ID: a5bb1635-7abf-424c-f337-f7e48ad8017a
* Content: [Install Software Updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/understand/install-software-updates)
* Content Source: [sccm/osd/understand/install-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/understand/install-software-updates.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @bryandam for the feedback. 😃

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
