### ISSUE TITLE
Download of CMTrace

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/SCCMdocs#1303]
Need to make this available outside of the CD.Latest folder on the site server.  This is used for cloud-only intune customers that don't have a site server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c47a4fa-cc4b-49f7-d850-312dcf59ac8c
* Version Independent ID: 26c1bc31-5c98-346b-6a27-50de3da938e0
* Content: [Configuration Manager Tools - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/support/tools#feedback)
* Content Source: [sccm/core/support/tools.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/support/tools.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for taking the time to provide feedback on Configuration Manager! This is an interesting idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by danmyhre** [comment]
Done

https://configurationmanager.uservoice.com/forums/300492-ideas/suggestions/37035970-cmtrace-availability

**Comment by guilhermeferreyra** [comment]
404 not found :D

**Comment by aczechowski** [comment]
@guilhermeferreyra if you're referring to the UserVoice idea, it's still there
