### ISSUE TITLE
Settings requirement unclear

### ISSUE THREAD

**Issue by ninjacat00** [MicrosoftDocs/SCCMdocs#1307]
If pre-prod is selected, and upgrade all clients is also selected, which takes precedent?  Can both be selected and only pre-prod will be upgraded?  If so, does upgrade all take precedent after the client is promoted?  None of this detail is given above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c6ecf9a-a586-1f34-5c41-b41081cb5e55
* Version Independent ID: e29256cd-00f0-0dc9-88ea-988425858d64
* Content: [Test client upgrades pre-production collection - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/upgrade/test-client-upgrades#feedback)
* Content Source: [sccm/core/clients/manage/upgrade/test-client-upgrades.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/upgrade/test-client-upgrades.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ninjacat00 for the feedback. You can enable both options, but there's no conflict because they apply at different times to different resources. 

In the section, [To install a Configuration Manager update that includes a new version of the client](https://docs.microsoft.com/sccm/core/clients/manage/upgrade/test-client-upgrades#to-install-a-configuration-manager-update-that-includes-a-new-version-of-the-client)
> After the wizard complete, clients in the pre-production collection will begin to deploy the updated client. 
So that setting only applies after you update the site.

Then, when you're comfortable with testing the new version of the client, the third section [To promote the new client to production](https://docs.microsoft.com/sccm/core/clients/manage/upgrade/test-client-upgrades#to-promote-the-new-client-to-production) explains that process. This action then makes the new client available for all clients (that aren't excluded) over the period of time you specify. 

I think the information is present in this article, so I'm closing this issue. Feel free to reopen if you have additional details.

**Comment by ninjacat00** [comment]
I tested this in my lab.  If the production client version and the pre-prod client version are the same, and both options are checked, it upgrades all clients.  If the versions are different, meaning the production version is lower than the pre-prod client version, and both options are checked, only the pre-prod clients get upgraded.  Once you promote the pre-prod clients and the versions then match, all clients get upgraded.  This is the type of detail needed in the documentation in my opinion.

**Comment by aczechowski** [comment]
Right, what you state is all accurate. And I'm saying that the text I shared above from the article says that. 😄 

So personally I think the article is clear on this behavior. But I may be too close to it, so I asked a colleague for her input. She suggested that we could add some clarity under the second section, with a reference to [Test client upgrades pre-production collection](https://docs.microsoft.com/sccm/core/clients/manage/upgrade/test-client-upgrades#to-install-a-configuration-manager-update-that-includes-a-new-version-of-the-client), and make it crystal clear that you need to use the option to **test in pre-production** and specify a collection. 

Do you think that would help your point? Otherwise, can you provide some more specific suggestions? Specific section and sentence of the article that need clarification. I feel like there's possibly some miscommunication, so perhaps that would help clarify.

**Comment by ninjacat00** [comment]
Yes, I'd agree more detail to provide clarity on what will happen given the details I provided.  Maybe a good way to document it is to put in scenarios.  Just spitballing, but maybe something like this.......Scenario #1 - You have not checked pre-prod during a prior upgrade.  This means your prod and pre-prod client will be the same version on the auto client upgrade settings.  As a result, you should only select the pre-prod option for testing.  Then, when you are ready to upgrade the entire client fleet, you can additionally select the prod client option to upgrade all your clients.  NOTE, there would be no promotion of the pre-prod client in this scenario.  Also note, for subsequent upgrades, it is important you configure the pre-prod client collection in the installation wizard.  In this manner, only the pre-prod collection devices will be upgraded and you can follow the normal process of promoting the pre-prod client at your leisure.  Scenario #2 - You have checked the pre-prod client option in a prior upgrade.  This means that your prod client and pre-prod client are not the same version.  Your prod client will be still be the client version from the previous version of ConfigMgr while your pre-prod client will be the new client that is part of the latest ConfigMgr upgrade.  As a result, if you have both the prod client and the pre-prod client options selected, only the pre-prod devices will install the client.  When ready, promote the pre-pod client.  Once this occurs, the prod client will then leverage the latest client version and the being to update the remaining devices in the fleet.

I hope this is helpful.  The main issue is that there is a gap in the docs when an admin who has been upgrading ConfigMgr has been skipping the pre-prod client configuration and wants to use auto client upgrade after the upgrade, but prior to the subsequent upgrade.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
