### ISSUE TITLE
Why only used powershell 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/SCCMdocs#1322]
Why the  author  used  powershellcmdlets . If you provide command prompts  commands lines  or  Dism commands its  usefull to me and others .
This article has  very high exceptional   powershell cmdlets , those  are  beyond my  knowledge .I think i have  to forgot my mathemattics  knowledge to learn this . 
I think all authors  are  very experienced . Thanks  to the  authors for  this  article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc2393d-6a81-c9c9-87bb-b40b66f26d68
* Version Independent ID: fda85f4c-33ec-d0aa-b793-381d2bebb57d
* Content: [MDT Samples - Microsoft Deployment Toolkit](https://docs.microsoft.com/en-us/sccm/mdt/samples-guide#feedback)
* Content Source: [sccm/mdt/samples-guide.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdt/samples-guide.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by baardhermansen** [comment]
PowerShell have been used simply because it's the THE tool for automation. If you still today don't know PowerShell, start learning it. Sounds rude perhaps, but without PS knowledge, you'll find yourself outdated. 
BTW: This article contains super simple PS commandlets and a tiny bit of SQL, absolutely nothing here is complicated.

@officedocsbot close

**Comment by RAJU2529** [comment]
Yes this issue can be close
