### ISSUE TITLE
 Office products on lifecycle dashboard - MSI only?

### ISSUE THREAD

**Issue by SCCMAdmin** [MicrosoftDocs/SCCMdocs#1344]
"The product lifecycle dashboard now includes information for installed versions of Office 2003 through Office 2016."

Hi Team, is this MSI only?
What about for outdated Click-to-Run technology?
Do you expect C2R to only be utilised/visualised and actioned under the Software Library &gt; Overview &gt; Office 365 Client Management node only ?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3bc5b76-c08b-5fd9-3b87-f327b094e67e
* Version Independent ID: 96bd2543-d38f-a154-6067-91522d2284bb
* Content: [Technical preview 1901 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/get-started/2019/technical-preview-1901#bkmk_lifecycle)
* Content Source: [sccm/core/get-started/2019/technical-preview-1901.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/2019/technical-preview-1901.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Yes, those versions are MSI only. 

Regarding support for C2R versions, please file [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback). I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. 

I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by SCCMAdmin** [comment]
Thank you.
