### ISSUE TITLE
"Call support to help change the MDM authority"

### ISSUE THREAD

**Issue by sleeplesstwo** [MicrosoftDocs/SCCMdocs#1356]
This step at the end of the proccess is apparently incorrect according to support, who just spent 2 months attempting to do it and then told me it needed to be done before changing the MDM authority during the time you are testing in mixed MDM authority using the Switch-MdmDeviceAuthority Powershell command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b82df45-3900-c15c-5838-6983b6a862f5
* Version Independent ID: 86ff67a2-f224-096b-7905-ec5d6523c4bd
* Content: [Change your MDM authority to Intune - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/deploy-use/migrate-change-mdm-authority#feedback)
* Content Source: [sccm/mdm/deploy-use/migrate-change-mdm-authority.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/deploy-use/migrate-change-mdm-authority.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the feedback. Let me check with the engineering team

**Comment by aczechowski** [comment]
We discontinued the hybrid MDM service in September 2019. For more information, see the main [hybrid MDM](https://docs.microsoft.com/sccm/mdm/understand/hybrid-mobile-device-management) article. We plan to completely retire the documentation in a couple of months. Since we're no longer maintaining this content, I'm closing this issue.
