### ISSUE TITLE
5th Bit in ProgramFlags

### ISSUE THREAD

**Issue by MrWyss-MSFT-zz** [MicrosoftDocs/SCCMdocs#1362]
What is the 5th bit (0x10, 16 dec) ProgramFlags, seems to be on by default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3db73783-fe87-5231-286c-779c1a4b1bd4
* Version Independent ID: b716873c-d994-83e8-0a84-a86706c570f5
* Content: [SMS_TaskSequencePackage Class - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/osd/sms_tasksequencepackage-server-wmi-class#feedback)
* Content Source: [sccm/develop/reference/osd/sms_tasksequencepackage-server-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/osd/sms_tasksequencepackage-server-wmi-class.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @MrWyss-MSFT for the feedback. We unfortunately have a large backlog of work for the PowerShell & SDK content, but are looking at ways to improve it in the future.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
