### ISSUE TITLE
Deprecating the previous version of Software Center.

### ISSUE THREAD

**Issue by emmanuelrd** [MicrosoftDocs/SCCMdocs#1365]
Any chance you will be reconsidering deprecating the previous version of Software Center? The new Software Center is not supported and does not work on Server Core installations while the previous version of Software Center works just fine, leaving us without access to Software Center on Server Core installations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46761dfa-340e-5156-a555-455e7f953aac
* Version Independent ID: 7ebf80eb-7d7c-847e-8e90-eada2ed48359
* Content: [Deprecated features - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/changes/deprecated/removed-and-deprecated-cmfeatures)
* Content Source: [sccm/core/plan-design/changes/deprecated/removed-and-deprecated-cmfeatures.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/changes/deprecated/removed-and-deprecated-cmfeatures.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @emmanuelrd for taking the time to provide feedback on Configuration Manager! This idea is interesting, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
