### ISSUE TITLE
How do I stop a script?

### ISSUE THREAD

**Issue by iamtechy** [MicrosoftDocs/SCCMdocs#1413]
I just started a script in ConfigMgr 1806 and don't know how to stop it. It's running on 6000 machines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c7d1db7-6812-ff3c-9aac-0f55800ed665
* Version Independent ID: a4499cf7-ed5a-710c-66e0-005563b9c015
* Content: [Create and run scripts - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/create-deploy-scripts#feedback)
* Content Source: [sccm/apps/deploy-use/create-deploy-scripts.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/create-deploy-scripts.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @iamtechy for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I generally close such support requests, but I think in this instance we can check to see if there is a supported method for stopping a script, and include that detail in the documentation. I just can't promise any sort of turnaround on that followup, thus the information about about support options.

**Comment by aczechowski** [comment]
Scripts are currently unstoppable. I suggest filing product feedback. We'll look at adding a note for this issue to this article.

**Comment by Hedkandi** [comment]
You can cancel scripts or at least it looks like it, i have not checked in any logs that its actually cancelled but if you go to Monitoring and then to Client Operations. Here you can right click and select cancel on Run Script actions. You can not see which script it refers to but it shows the time it was initiated.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.

Thinking through this some more, the Client Operations node is for all fast channel (BGB) actions. So cancelling an action most likely just stops any client that hasn't already received from starting. In this instance, if the client has already received the instruction and the script is running, there's nothing currently out of the box to stop it.
