### ISSUE TITLE
Named Pipes Required!!!

### ISSUE THREAD

**Issue by Daren9m** [MicrosoftDocs/SCCMdocs#1422]
Please note, it is necessary to enable Named Pipes on the SQL DB via SQL Server Configuration Manager otherwise it FAILS!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8ae7a97-3f78-b756-a468-79989cd0dcef
* Version Independent ID: 63ff7753-2f9d-c533-2c3b-99b10d46878d
* Content: [Collection Evaluation Viewer - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/support/ceviewer#feedback)
* Content Source: [sccm/core/support/ceviewer.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/support/ceviewer.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Daren9m for the feedback. Let me check with the engineering team for more info

**Comment by Daren9m** [comment]
PS - This is an 1806 with Hotfix and SQL on box.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.

I unfortunately wasn't able to track down anyone that knows the tool well enough to confirm.
