### ISSUE TITLE
Update Frequency

### ISSUE THREAD

**Issue by Anoni-Mouse** [MicrosoftDocs/SCCMdocs#1440]
If the product release is really 3 times a year, this might be OK, but each release has two or three fixes, which makes it around 8 updates/year. This is frustrating for customers with tons of geographical locations and the link is slow as most of the fixes and all major releases contain client updates which is 160 MB!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8547d77-65a2-19b5-dc97-abbf455eb13d
* Version Independent ID: 6e4458d1-e8b6-12eb-0c59-5601c14186d6
* Content: [Updates and servicing - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/updates)
* Content Source: [sccm/core/servers/manage/updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Anoni-Mouse for taking the time to provide feedback on Configuration Manager! I'm sorry for your frustration, and I want to make sure your feedback gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
