### ISSUE TITLE
Possible to pass a task sequence variable to PowerShell script via parameter?

### ISSUE THREAD

**Issue by jholl016** [MicrosoftDocs/SCCMdocs#1442]
When using the "Run PowerShell Script" step, is it possible to pass a task sequence variable via the parameters field?  For example:

-ParameterName %myTaskSequenceVariable%

Also, the "Run PowerShell Script" documentation needs to be updated to reflect changes in 1902.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1187d55d-d8b3-ebc8-37e8-8de14807be4e
* Version Independent ID: daff4a99-10ac-b424-f08a-9024407e667a
* Content: [Task sequence steps - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/understand/task-sequence-steps#feedback)
* Content Source: [sccm/osd/understand/task-sequence-steps.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/understand/task-sequence-steps.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jholl016 for the feedback. I'm checking with the engineering team on your question. 

To your other point, we're still working to update the core docs with 1902 content. From [What's new with 1902](https://docs.microsoft.com/sccm/core/plan-design/changes/whats-new-in-version-1902):
> This article currently lists all significant features in this version. However, not all sections yet link to updated content with further information on the new features. Keep checking this page regularly for updates. Changes are noted with the [Updated] tag. This note will be removed when the content is finalized.

**Comment by aczechowski** [comment]
Thanks for taking the time to provide feedback on Configuration Manager! This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
