### ISSUE TITLE
ClientCheckPass - State 3

### ISSUE THREAD

**Issue by MikelRbrts** [MicrosoftDocs/SCCMdocs#1452]
A ClientCheckPass state of 3 is not listed on the page. It appears these are PCs that are in a questionable state in the SCCM console, is that correct? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a86de707-38f0-4422-b825-56c3ba94280b
* Version Independent ID: e7fae6e6-f413-42e5-164a-31b1e676068f
* Content: [SMS_CombinedDeviceResources Class - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/core/clients/collections/sms_combineddeviceresources-server-wmi-class#feedback)
* Content Source: [sccm/develop/reference/core/clients/collections/sms_combineddeviceresources-server-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/core/clients/collections/sms_combineddeviceresources-server-wmi-class.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @MikelRbrts for the feedback. We unfortunately have a large backlog of work for the PowerShell & SDK content, but are looking at ways to improve it in the future.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
