### ISSUE TITLE
Broken Links (troubleshoot-endpoint-client.md)

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/SCCMdocs#1475]
In File:
SCCMdocs\sccm\protect\deploy-use\troubleshoot-endpoint-client.md

The following links are broken, could not find a replacement:

http://go.microsoft.com/fwlink/?LinkID=87341
http://go.microsoft.com/fwlink/?LinkID=87342

(admin edit: add metadata for article link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 940822dc-f344-a2ee-b63d-bc65e2705584
* Version Independent ID: 1f85b90e-b13f-f89f-99e9-d0e11d1fab1e
* Content: [Troubleshooting Windows Defender or Endpoint Protection client - Configuration Manager](https://docs.microsoft.com/en-us/sccm/protect/deploy-use/troubleshoot-endpoint-client)
* Content Source: [sccm/protect/deploy-use/troubleshoot-endpoint-client.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/troubleshoot-endpoint-client.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
This might be a better single target, instead of two separate (and it covers multiple product versions): https://www.microsoft.com/wdsi/definitions (make sure to not include any locale such as en-us in the URL in markdown).

Interestingly, those two fwlinks are in that page for SCEP 2012, and do work. But I think this is a good change regardless.

**Comment by aczechowski** [comment]
This is already fixed
