### ISSUE TITLE
Broken Links (upgrade-to-configuration-manager.md)

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/SCCMdocs#1484]
The file:
SCCMdocs\sccm\core\servers\deploy\install\upgrade-to-configuration-manager.md

Contains the following broken links:
https://docs.microsoft.com/previous-versions/system-center/system-center-2012-R2/gg712686
https://docs.microsoft.com/previous-versions/system-center/system-center-2012-R2/hh846234

(admin edit: add metadata for article link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37b73c31-552d-0eda-c477-f44da966acb3
* Version Independent ID: adc49b42-8ca6-702e-d8de-c65e5df69050
* Content: [Upgrade to Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/upgrade-to-configuration-manager)
* Content Source: [sccm/core/servers/deploy/install/upgrade-to-configuration-manager.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/upgrade-to-configuration-manager.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
This issue is because of the complexity of the links on the previous-versions site. There's a parameter at the end of the URL that in markdown needs to be escaped properly. (So there are probably other instances of this elsewhere in our content 😢 )

Here's the functional link: https://docs.microsoft.com/previous-versions/system-center/system-center-2012-R2/hh846234(v=technet.10)

But in markdown, needs to be:
```markdown
[Configure database replicas for management points](https://docs.microsoft.com/previous-versions/system-center/system-center-2012-R2/hh846234\(v=technet.10\))
```
(Note the two backslashes `\` before the parentheses on the end "v" parameter)

Rinse and repeat for the other link
