### ISSUE TITLE
Broken Link (about-scap.md)

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/SCCMdocs#1485]
The file:
SCCMdocs\sccm\compliance\plan-design\scap\about-scap.md

Contains the following broken link:
https://docs.microsoft.com/previous-versions/system-center/system-center-2012-R2/mt228311

(admin edit: add metadata for article link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a689124-c901-d2e0-508f-998b39852315
* Version Independent ID: 6f6dc930-ad34-e747-f03f-93c46a3e237c
* Content: [SCAP extensions - Configuration Manager](https://docs.microsoft.com/en-us/sccm/compliance/plan-design/scap/about-scap)
* Content Source: [sccm/compliance/plan-design/scap/about-scap.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/compliance/plan-design/scap/about-scap.md)
* Product: **configuration-manager**
* Technology: **configmgr-compliance**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
This issue is because of the complexity of the links on the previous-versions site. There's a parameter at the end of the URL that in markdown needs to be escaped properly. (So there are probably other instances of this elsewhere in our content 😢 )

Here's the functional link: https://docs.microsoft.com/previous-versions/system-center/system-center-2012-R2/mt228311(v=technet.10)

But in markdown, needs to be:
```markdown
[Configure database replicas for management points](https://docs.microsoft.com/previous-versions/system-center/system-center-2012-R2/mt228311\(v=technet.10\))
```
(Note the two backslashes `\` before the parentheses on the end "v" parameter)

**Comment by ChrisKibble** [comment]
@aczechowski - appears this is a non-issue, the parenthesis are escaped properly on this page now.
