### ISSUE TITLE
Client apps

### ISSUE THREAD

**Issue by gutjahr** [MicrosoftDocs/SCCMdocs#1530]
Can you please provide more detailed information about how co-management will affect application deployments. For most workloads it's either Intune or SCCM managing it, but never both at the same time. For apps, this article makes it sound like you will be able to use both Intune (Company Portal) and SCCM (Software Center) at the same time.

SideNote: currenly on a co-managed device (pre-release app workload not enabled), Win32 apps (through Sidecar) can be deployed through Intune while native Intune apps like MSI/APPx/O365 show up as 'Not Applicable'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70ebc3e6-359e-3067-3cfd-149052df1123
* Version Independent ID: 723165f6-6bfa-ed78-fbda-23c12bc07b9d
* Content: [Co-management workloads - Configuration Manager](https://docs.microsoft.com/en-us/sccm/comanage/workloads)
* Content Source: [sccm/comanage/workloads.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/comanage/workloads.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @gutjahr for the feedback. I'll check with the feature team.

**Comment by gutjahr** [comment]
The following article contains some useful information. Would be nice to consolidate this into the official documentation: https://techcommunity.microsoft.com/t5/Intune-Customer-Success/Support-Tip-Configuring-workloads-in-a-co-managed-environment/bc-p/713351

**Comment by TechTrooper** [comment]
When can we expect Client Apps to enter release status? 
It has been pre-release feature for over a year now.

**Comment by JBerners** [comment]
@aczechowski do you have an answer from the product Team? Is ist possible to use both SCCM and Intune for application deployments?
Thx
Jochen

**Comment by gabrielmccoll** [comment]
How long does it take for workload changes to be reflected inside Intune. I changed the Device Management over couple hours ago but the devices in Intune don't show it yet. still just compliance

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.

Beginning with version 2002, it's no longer a pre-release feature.

We also added a [Diagram for app workloads](https://docs.microsoft.com/mem/configmgr/comanage/workloads#diagram-for-app-workloads)
