### ISSUE TITLE
Missing Pre-requisite - SQL Server 2012 Native Client for site systems

### ISSUE THREAD

**Issue by jrosser1221** [MicrosoftDocs/SCCMdocs#1533]
Hello,

We check for the existence of the SQL Server 2012 Native Client in the pre-requisite checker during upgrade readiness check; it should probably be listed here as a site system pre-requisite.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9070eb9b-0e5f-a877-e02e-2d1cea2a2b38
* Version Independent ID: df251762-f2d6-9f06-4fa9-ec5cea2cca0a
* Content: [Site prerequisites - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/site-and-site-system-prerequisites#feedback)
* Content Source: [sccm/core/plan-design/configs/site-and-site-system-prerequisites.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/site-and-site-system-prerequisites.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @jrosser1221 for calling this out. Agreed. 

Reference https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/list-of-prerequisite-checks#sql-server-native-client

**Comment by mestew** [comment]
@aczechowski @jrosser1221 
The link that Aaron pointed to states that the SQL Native client gets automatically installed by ConfigMgr when you install a new site. However, we don't update it once it's installed.

So would it really be a prereq if CM installs it for you? I'm assuming we still do this @jrosser1221 let me know if you are not seeing that happening. 

But yeah, I do think we should make mention of the SQL native client even if it is just to say something like "hey check your version because we install it but dont update it..see this [article](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/list-of-prerequisite-checks#sql-server-native-client) for more info"

**Comment by cliffhobbs** [comment]
@mestew IMHO if we install something, we should also upgrade it or least flag it needs to be updated.

Also, even if we install something we need if it's missing, I still think it should be listed as a prereq. 

Maybe put these under a separate section such as "Installed automatically by the installation/upgrade process"?

I can see folks potentially getting caught out as they are not aware of things installed automatically by us which could catch them out later, say on a security/compliance review, or a patch gets missed as folks aren't aware the component is installed in their environment.

**Comment by aczechowski** [comment]
This issue is closed because I submitted a change for it that will publish tomorrow
