### ISSUE TITLE
Insufficient Cache Size

### ISSUE THREAD

**Issue by jorlando82** [MicrosoftDocs/SCCMdocs#1535]
About client cache section covers behavior for insufficient cache size, but only for programs and applications. Can we get clarification for client behavior for task sequences in the event the cache is too small? Might be helpful to cover software updates too. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b9fdee-e834-affe-d7cd-61854d4a6925
* Version Independent ID: 1fb998eb-2449-1e17-fc6d-48a3a5c4f4e5
* Content: [Manage clients - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/manage-clients#feedback)
* Content Source: [sccm/core/clients/manage/manage-clients.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/manage-clients.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jorlando82 for the feedback, let me check with the engineering teams

**Comment by aczechowski** [comment]
Thanks again for the feedback. We moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
