### ISSUE TITLE
SUP Fallback Example vs DP Fallback Example

### ISSUE THREAD

**Issue by chboeye** [MicrosoftDocs/SCCMdocs#1537]
https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/boundary-groups#example
https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/boundary-groups#example-of-using-boundary-groups
I'm scratching my head around this but cannot find a good way to rephrase it. The fallback DP example is clear and simple and I think a "note" for the specific SUP behavior would be better than this explanation. The most important point is : There is a minimum hard coded threshold of 120 min before a fallback is (automatically) happening. Everything under 120 min can be used for manual fallback via push or other method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7db5025d-eff5-5acb-dd57-0895828e1657
* Version Independent ID: 1b5e1df8-e30a-6eef-b5c6-5f3a4c89131c
* Content: [Configure boundary groups - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/boundary-groups#feedback)
* Content Source: [sccm/core/servers/deploy/configure/boundary-groups.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/boundary-groups.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @chboeye for the feedback. Did you see the [section on SUP behaviors](https://docs.microsoft.com/sccm/core/servers/deploy/configure/boundary-groups#software-update-points) in that article? I think it covers the scenario fairly well. 

In discussing with the feature team, the one thing I think we could better describe is the timing of the [manual switch](https://docs.microsoft.com/sccm/sum/plan-design/plan-for-software-updates#BKMK_ManuallySwitchSUPs). It happens on the next scan cycle for the client. 

We should also explicitly add this info to the article that talks about the [manual switch](https://docs.microsoft.com/sccm/sum/plan-design/plan-for-software-updates#BKMK_ManuallySwitchSUPs) process.

Additional note: the link in *this* BG article to the SUM article for the manual switch uses the wrong anchor. It should be `#BKMK_ManuallySwitchSUPs` instead of `#manually-switch-clients-to-a-new-software-update-point`.

**Comment by aczechowski** [comment]
This issue is closed because I made a change to the articles to address this feedback. The updated articles should publish live in the next hour.
