### ISSUE TITLE
Remote Content Library - Support for Distribution Point Role

### ISSUE THREAD

**Issue by JeissonL** [MicrosoftDocs/SCCMdocs#1572]
Hi team, currently I have a scenario with a shared network route from NAS for save all content of my Distribution Point. However can you confirm us please if this scenario it's supported by Microsoft, or definitely I need storage directly attached to my Distribution Point Role server?. 
Thank you in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92260657-2102-c15f-a844-5fa3aff64aae
* Version Independent ID: a4597d2d-9441-61f2-718d-c0a54a46d3fd
* Content: [The content library - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/the-content-library#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/the-content-library.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/the-content-library.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
It's not something we explicitly test, so technically not supported. And we don't generally document what we don't support. However, as long as the storage is presented to the Windows server in such a way that it can access it like any local disk, and then subsequently share that content to clients, then it should work. Supportability becomes a bit of a grey area there. If you had some problem with the DP and called support, if the problem was traced back to how the storage is presented to the server, then that will impact the support engineer's ability to help. 

I'm closing this issue as there's nothing actionable for docs at this time.
