### ISSUE TITLE
Manage Office 365 ProPlus with Configuration Manager

### ISSUE THREAD

**Issue by HeatherAllemang** [MicrosoftDocs/SCCMdocs#1597]
customers want to know if the notifications can be suppressed.  It should be in the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1da48af-4783-bd17-67f3-f265df93503f
* Version Independent ID: 17432b22-04cb-f47f-1634-e5b7fc99c37d
* Content: [Manage Office 365 ProPlus updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/manage-office-365-proplus-updates#feedback)
* Content Source: [sccm/sum/deploy-use/manage-office-365-proplus-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/manage-office-365-proplus-updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.

We're working with the Office team to revise/replace this article. I hope that this sort of information will be included in that future revision.
