### ISSUE TITLE
Clarify how to make a admin connection to SQL

### ISSUE THREAD

**Issue by Jim-Webb** [MicrosoftDocs/SCCMdocs#1598]
I've read the instructions multiple times and am still not clear on how to make the needed admin connection to my CM database. I've tried connection via SSMS using the Admin:Servername\instance but that doesn't work. I've also tried admin:servername since we are running on the default instance but I get the following message "Dedicated administrator connections are not supported via SSMS as it establishes multiple connections by design." I think the documentation needs clarification on the exact steps to take to make the proper connection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db678f94-700f-ad35-9fdc-d165893b5373
* Version Independent ID: 2ee761db-4b3b-6fa0-c195-ad85ebbac70d
* Content: [Prerequisite checks - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/list-of-prerequisite-checks#feedback)
* Content Source: [sccm/core/servers/deploy/install/list-of-prerequisite-checks.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/list-of-prerequisite-checks.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by Jim-Webb** [comment]
This page has the info needed to connect.
https://www.codeproject.com/Tips/1136361/How-to-Establish-Dedicated-Admin-Connection-DAC-to

"Using SSMS (SQL Server Management Studio), do not try to connect using the standard connection from object explorer. With this connection type, SSMS uses several simultaneous connections which isn’t possible when using DAC.

Initiate the connection for example from File menu using New / Database Engine Query. This ensures that you take only single connection."

**Comment by aczechowski** [comment]
Hi @Jim-Webb thanks for the feedback, and sorry that you had problems with this. We conferred with our colleagues on the SQL team, and what we currently have is technically accurate: 
> The easiest method is to use SQL Server Management Studio's Database Engine Query Editor...
The **Query Editor** is needed instead of the **Object Explorer**. Something that an experienced SQL admin probably understands, but perhaps too subtle of a distinction for most SCCM admins (who aren't generally SQL experts). So while I don't want to recreate the SQL content that we link to for more details, I think we can probably find a better balance of explaining this piece a bit further.

**Comment by mestew** [comment]
Thanks again for the feedback. We moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
