### ISSUE TITLE
1810+ behavior with SMS Provider

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#1613]
In 1810/1902, we do install SMS Provider on the passive site server, this is in case the previous SMS provider is co-located with active site server and the machine goes down. Admin can still use admin console to point to passive site server and do promotion of the passive site server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c416209-7476-14b2-a60b-9f3477dc79be
* Version Independent ID: 765534af-f933-c768-0994-fa8d0a5712a0
* Content: [Site server high availability - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/site-server-high-availability#process-to-promote-the-site-server-in-passive-mode-to-active-mode)
* Content Source: [sccm/core/servers/deploy/configure/site-server-high-availability.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/site-server-high-availability.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by SMSAgentSoftware** [comment]
So that's kinda correct. The SMS Provider appears to install, but it doesn't register itself properly. In the SCCM console, the SMS provider role is not listed against the passive server, and it's not there in the Site properties either. So you still need to run Configuration Manager setup to modify the SMS provider configuration - it will tell you the role is already installed on the server and ask if you want to reinstall it. After reinstall, the role appears in the console.

**Comment by jholl016** [comment]
I just ran through this in 1910 and the SMS Provider was properly installed and registered automatically, so no reinstall of the provider role was needed. Not sure which release/hotfix actually addressed this, but it's fixed now if you're on CB.
