### ISSUE TITLE
Discussion: Removing VBScript Examples

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/SCCMdocs#1614]
Looking for community and Microsoft (@aczechowski, @mestew, and all) comment on if you all think we should remove VBS examples as we update articles with PowerShell or if they should both stay.  My vote is for removal - we should be discouraging the older scripting technologies and encouraging new, and leaving both just lengthens docs unnecessarily.

**Comment by cliffhobbs** [comment]
Rather than removing them (and all that potentially valuable content), why not create a separate "VBScript Examples" section on docs? Then as articles get updated for PowerShell, move the VB stuff and insert a xref?

I'm sure there are some that are not fully proficient with all of PowerShell (me included) and seeing things done in a different way might also aid learning/understanding. Just because PowerShell is the MS way of doing things, doesn't always mean customers agree/are so keen to follow IMHO ;-)

**Comment by aczechowski** [comment]
Good question @ChrisKibble. I'll amplify on Twitter to get more input. 

One thought: what about Windows PE? Does everyone add .NET/PowerShell to their boot images? If not, then VBScript would be the primary language of choice I think.

**Comment by bryandam** [comment]
Might be worth providing a link to an example of what we're talking about.

I have vague memories of a tabbed control that would show the same sample in different languages.  If that's a thing then I don't see why you wouldn't have both with PoSH being the default.

@aczechowski: No, not everyone.  A _lot_ do, especially if you want to get serious about running scripts.  I don't have telemetry the back it up but if I were to hazard a guess it would be that the most used scripting language in OSD is PowerShell.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
