### ISSUE TITLE
Degradation

### ISSUE THREAD

**Issue by si-chan** [MicrosoftDocs/SCCMdocs#1615]
Is this statement correct? Connection to the site database is surely a one-time thing and shouldn't affect running performance.

"Degradation in performance can occur, because the site server must find the active node of the SQL Server cluster before it connects to the site database."

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd44b7f-08df-21d7-f10f-99b5864302d8
* Version Independent ID: 33b26f62-4485-a7cf-9767-07de1c9b5be3
* Content: [SQL Server cluster - Configuration Manager](https://docs.microsoft.com/en-gb/sccm/core/servers/deploy/configure/use-a-sql-server-cluster-for-the-site-database)
* Content Source: [sccm/core/servers/deploy/configure/use-a-sql-server-cluster-for-the-site-database.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/use-a-sql-server-cluster-for-the-site-database.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
