### ISSUE TITLE
There is no way to republish if extend the CAS hierarchy.

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/SCCMdocs#1640]
Hi team, 
I'm moving this from here https://github.com/MicrosoftDocs/SCCMDocs.ja-jp/issues/29 since the contributor is making a suggestion on the original documentation.

@tahakogi commented 10 hours ago
Once the update has been published in a standalone hierarchy, the content download source is registered as WSUS content on the server.

If you then extend the CAS hierarchy, the download source of the content is fixed with the information in the standalone hierarchy and can not be republished.
We need to edit SUSDB to fix this.
For this reason, it should be stated that it is necessary to re-install SUP and WSUS in the scenario of expanding the hierarchy as a premise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 054797d3-c4d8-2c2e-9940-e8763f6f3881
* Version Independent ID: 9751d801-35de-ebd8-29ea-57e459f845dc
* Content: [Enable third party updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/third-party-software-updates)
* Content Source: [sccm/sum/deploy-use/third-party-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/third-party-software-updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
Thanks again for the feedback. We moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
