### ISSUE TITLE
"ConfigMgrInstallation.adm" can´t handle strings larger than 255 characters

### ISSUE THREAD

**Issue by PehDeh** [MicrosoftDocs/SCCMdocs#1648]
"ConfigMgrInstallation.adm" can´t handle strings larger than 255 characters
VALUENAME SetupParameters
MAXLEN 255

This causes that you can´t enter Multiple Parameters for example long CCMCERTISSUERS.

I worked arround it by setting it to:
VALUENAME SetupParameters
MAXLEN 511

But maybe this old adm-Template needs a refresh.

(admin edit: adding metadata to link with target article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d990303-ea50-35f3-fc68-1b983c7fa6db
* Version Independent ID: 58425268-9a47-1ce6-f489-1a2c3ae9c6bb
* Content: [Deploy clients to Windows - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/deploy/deploy-clients-to-windows-computers#BKMK_Provision)
* Content Source: [sccm/core/clients/deploy/deploy-clients-to-windows-computers.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/deploy-clients-to-windows-computers.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @PehDeh for the feedback. That's a good tip to include in this article.

To share your idea about refreshing the group policy template, I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress.

**Comment by PehDeh** [comment]
Done, thanks for the quick reply.

**Comment by aczechowski** [comment]
I added this tip to the article, it should publish live tomorrow
