### ISSUE TITLE
Documentation should note this needs to be run on the SCCM server and the console needs to be installed

### ISSUE THREAD

**Issue by Typhoon87** [MicrosoftDocs/SCCMdocs#1666]
Was trying to use RBAViewer.exe on  my desktop and it crashes instantly every time at the splash screen, tried opening by double click, by right click run as admin, and by command line all crashed. Had to remote to the SCCM site server works fine. 

Documentation does not currently note any such restriction. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 821e8aae-f478-6b3e-8338-09b11f71cd42
* Version Independent ID: 123a8ff1-11fc-076a-32e9-df86b609f981
* Content: [Role-based Administration Tool - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/support/rbaviewer#feedback)
* Content Source: [sccm/core/support/rbaviewer.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/support/rbaviewer.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by Typhoon87** [comment]
Its been a couple of weeks wanted to check the status of this?

**Comment by Typhoon87** [comment]
Closing in on 2 months any update on this item?

**Comment by aczechowski** [comment]
I haven't been able to track down anyone yet that can speak authoritatively to that tool. 

And keep in mind that the documentation feedback is not a formal escalation process. If the problem is reproducible, [send a frown](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) in the Configuration Manager console. If you need more immediate assistance, contact [Microsoft Support](https://aka.ms/cmcbsupport).

**Comment by aczechowski** [comment]
@mestew is going to add a note that this tool has to be run from the site server.
