### ISSUE TITLE
Prerequisites : Security scope

### ISSUE THREAD

**Issue by chboeye** [MicrosoftDocs/SCCMdocs#1668]
This sentence is not 100% accurate. You need more that "all" security scope. You either need "all Instances" (The "All" Built-in one) or "All" for "security scope", + "All System" for "collections" + "All Users and User groups" for  "collections"

(admin edit: added anchor to specific section in question)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f81e6681-918f-4996-f3e1-b41e8f1e4d22
* Version Independent ID: b45a2ed7-8385-d0a5-1d26-06745d91220c
* Content: [Create phased deployments - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/deploy-use/create-phased-deployment-for-task-sequence#security-scope)
* Content Source: [sccm/osd/deploy-use/create-phased-deployment-for-task-sequence.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/create-phased-deployment-for-task-sequence.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
Thanks again for the feedback. We moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
