### ISSUE TITLE
How to expire third party software updates manually in SCCM 1806 and higher

### ISSUE THREAD

**Issue by manishr38** [MicrosoftDocs/SCCMdocs#1689]
Hi there,
We have used SCUP with SCCM 2012 R2. SCUP had a option to expire update, is there similiar function / option available in SCCM 1806 or higher? 

Since we dont need SCUP to sync third party updates. 

Please add steps in the help document as well.

**Comment by manishr38** [comment]
@aczechowski any updates? We are waiting for your inputs, Actually we are stuck and donno how to manually expire third party software updates in SCCM 1806.

**Comment by aczechowski** [comment]
@manishr38 I'm sorry that you're having problems, but this feedback mechanism is not for support escalations. We're investigating whether any doc updates are needed, but we don't provide any SLAs on responses. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

**Comment by mestew** [comment]
Thanks again for the feedback. We moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
