### ISSUE TITLE
V3 certificate templates still required for code signing applications?

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/SCCMdocs#1714]
Can this be validated?  Not sure how it applies since v1710 allows for v3 templates for other aspects of CM.

> When you code-sign applications to deploy them to mobile devices, don't use a certificate that was generated by using a Version 3 template (Windows Server 2008, Enterprise Edition). This certificate template creates a certificate that's incompatible with Configuration Manager applications for mobile devices.
> 
> If you use Active Directory Certificate Services to code-sign applications for mobile device applications, don't use a Version 3 certificate template.
> 

Related, #549 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b63a5c3-b4c4-d60b-fac9-f625edb74022
* Version Independent ID: ca712b3a-aa29-9ef2-dbf0-d0a8589245d1
* Content: [Plan for application management - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/plan-design/plan-for-and-configure-application-management#feedback)
* Content Source: [sccm/apps/plan-design/plan-for-and-configure-application-management.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/plan-design/plan-for-and-configure-application-management.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ChrisKibble, good point. That note is at least from the [SCCM 2012 doc](https://docs.microsoft.com/previous-versions/system-center/system-center-2012-R2/gg682145\(v=technet.10\)), so my guess is that it no longer applies. But let me check with the engineering team to confirm.

**Comment by aczechowski** [comment]
I did get a response from engineering, apologies for not responding sooner. This may still apply for on-prem MDM, which is really the only mobile device scenario we support. It's not a scenario we actively test. That said, engineers said that we don't really look at the cert, but let Windows handle validation. But they weren't sure why this issue is noted. Since it's not generally tested and the usage for on-prem MDM is super low, I'm going to close this issue. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
