### ISSUE TITLE
Enrolling Intune managed endpoints

### ISSUE THREAD

**Issue by BHoggs** [MicrosoftDocs/SCCMdocs#1727]
Hi, this article only explains how to enroll devices using Configuration Manager. Although it lists the individual settings required, there should be a guide on using Intune to configure devices for enrollment.
This is necessary for customers who have fully adopted Modern Management with Intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 113ad599-a2ac-a376-70d7-86088c90f06e
* Version Independent ID: 3e781a76-9e2c-50f8-7afa-a52cb944008b
* Content: [Enroll devices in Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/sccm/desktop-analytics/enroll-devices#feedback)
* Content Source: [sccm/desktop-analytics/enroll-devices.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/enroll-devices.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @BHoggs for taking the time to provide feedback on Desktop Analytics! Right now, Desktop Analytics only integrates with Configuration Manager.

This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress.

I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by BHoggs** [comment]
Hi @aczechowski - isn't Desktop Analytics supposed to be the direct successor to Windows Analytics? 
We're already using Windows Analytics with Intune-Managed endpoints so I would have thought this would definitely be supported!

**Comment by iceorbital** [comment]
@BHoggs - Desktop Analtyics is the replacement for Windows Analytics. While Desktop Analytics builds on top of the concepts introduced with Windows Analytics, but the requirements have evolved. For our initial release, ConfigMgr is a requirement to enroll devices in Desktop Analytics. While support for Intune managed devices is in our backlog, we can't comment on timelines.
