### ISSUE TITLE
Some updates to help ease installation

### ISSUE THREAD

**Issue by kabluton** [MicrosoftDocs/SCCMdocs#1729]
Because of a couple of the pre-reqs now you should update SQL to SP4
This tool was SUPER useful to help install pre-reqs https://gallery.technet.microsoft.com/ConfigMgr-2012-R2-e52919cd

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e9b7de4-5860-4eda-a0e5-d34f69a63fd5
* Version Independent ID: b3140976-dc93-deab-1f90-d5479c8403af
* Content: [Set up your lab - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/get-started/set-up-your-lab#feedback)
* Content Source: [sccm/core/get-started/set-up-your-lab.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/set-up-your-lab.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @kabluton for the feedback. We should probably revise this article with more recent versions all around.

**Comment by aczechowski** [comment]
I'm closing this since it's in the retired repo and there's another issue filed on the article in the new repo (see the link above). Still hope to revise the article, just consolidating the feedback. If you want to receive updates on the issue, follow the link to MicrosoftDocs/MEMDocs#159 and select the button in the right side menu to subscribe to notifications.
