### ISSUE TITLE
Support for Server 2019?

### ISSUE THREAD

**Issue by CaptainUnlikely** [MicrosoftDocs/SCCMdocs#1738]
the information on this page currently excludes 2019.  Would it be possible to update the page to state that 2019 either is supported for these features, or isn't supported for $reasons?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34b2caf-beee-6525-8546-d9a7d919d4a0
* Version Independent ID: 285b669d-42d3-e8fb-d52b-589740e37f6c
* Content: [Support for Windows features - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/support-for-windows-features-and-networks#bkmmk_datadedup)
* Content Source: [sccm/core/plan-design/configs/support-for-windows-features-and-networks.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/support-for-windows-features-and-networks.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @CaptainUnlikely for the feedback, I think it is supported for those scenarios. We'll need to double-check with the feature teams, but I suspect we can just remove specific versions from this article, and point to the supported configurations. Then we don't have to worry about maintaining versions in this separate article.

**Comment by ChrisKibble** [comment]
Should we state all supported versions of Windows Server?

**Comment by aczechowski** [comment]
@ChrisKibble, yeah, I think some statement along those lines with a link to the [supported configs](https://docs.microsoft.com/configmgr/core/plan-design/configs/supported-configurations) would suffice

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.

I realized that there's really one mention of a specific version, and that says "2012 or later" so I think we're ok here.
