### ISSUE TITLE
SkipFinalSummary issue

### ISSUE THREAD

**Issue by baardhermansen** [MicrosoftDocs/SCCMdocs#1742]
The wording for SkipFinalSummary is "Indicates whether the Operating system deployment completed successfully wizard page is skipped.", however further down the page, we find the following explanation for how to skip pages: 
"Operating system deployment did not complete successfully - SkipFinalSummary".

This does not seem to be correct though, as when there are errors, the final summary is always visible. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4452b34-bc38-4e06-a053-c216312dcfc7
* Version Independent ID: ab55107e-272d-1f8f-21dd-dba39a95077d
* Content: [Toolkit reference - Microsoft Deployment Toolkit](https://docs.microsoft.com/en-us/sccm/mdt/toolkit-reference?fbclid=IwAR0d1gqdzERkimFQw_2WklKN06G0SeMieeUJ8vo3k9XnSRAVrQJNQLLtbPE#feedback)
* Content Source: [sccm/mdt/toolkit-reference.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdt/toolkit-reference.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
