### ISSUE TITLE
Missing info

### ISSUE THREAD

**Issue by SirJewDanielBerg** [MicrosoftDocs/SCCMdocs#1743]
Hi.

Why does this page not clarify what the following options do:
-perform windows setup compatibility scan without starting upgrade
-dynamically update windows setup with windows update
-override policy and use default microsoft update

The point of docs.microsoft.com should be to document everything.
Everything should be listed and explained, clarified, as not everything is always self-explanatory.
For example, I didn't realize that ticking -perform windows setup compatibility scan without starting upgrade will just result in my OS upgrade TS doing nothing. I thought it would perform a compatibility scan, and, if all is fine, continue and upgrade.
It turns out it won't.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfe3442-b59d-0d77-d9af-f18e787ec99d
* Version Independent ID: 60cb54a2-d1fd-92b5-b027-de8a85c7af64
* Content: [Create an OS upgrade task sequence - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system#feedback)
* Content Source: [sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @SirJewDanielBerg, thanks for the feedback, and I'm sorry for the misperception and issues you're having. The point of docs.ms isn't to document *everything*. The level of detail provided for a particular product/service, solution, scenario, or feature varies depending upon a number of factors. Certainly customer feedback is a part of that, but also things like product strategy and available resources (people, time, etc.).

If you notice under the bullet that talks about how to "Perform an inline compatibility assessment" there's a link "for more information". That link goes to more info about the step itself, which includes more details about the setting. Note the name of the setting is [Perform Windows Setup compatibility scan *without starting upgrade*](https://docs.microsoft.com/sccm/osd/understand/task-sequence-steps#perform-windows-setup-compatibility-scan-without-starting-upgrade). The point of the /compat scanonly option is to only do a compatibility scan, write information to the Windows update logs, and return an error code to summarize the outcome.

I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

If you think the product itself should handle this process better, I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress.

I'm closing this issue as there's nothing actionable for docs at this time.

If you have specific suggestions on how we can improve this article for this scenario, please either reopen this issue with further detail, or file a separate issues with additional feedback.
