### ISSUE TITLE
Suppport for CIFS share missing from this page. It doesn't seems to be supported, however, since it is not mentioned in the document customers are trying to use it and it eventually doesn't work when moving content library to remote location. Please see if the information regarding it could be added here.

### ISSUE THREAD

**Issue by Sansing1** [MicrosoftDocs/SCCMdocs#1747]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34b2caf-beee-6525-8546-d9a7d919d4a0
* Version Independent ID: 285b669d-42d3-e8fb-d52b-589740e37f6c
* Content: [Support for Windows features - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/support-for-windows-features-and-networks)
* Content Source: [sccm/core/plan-design/configs/support-for-windows-features-and-networks.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/support-for-windows-features-and-networks.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by Sansing1** [comment]
Suppport for CIFS share missing from this page. It doesn't seems to be supported, however, since it is not mentioned in the document customers are trying to use it and it eventually doesn't work when moving content library to remote location. Please see if the information regarding it could be added here.

**Comment by aczechowski** [comment]
Thanks @Sansing1 for the feedback. We honestly don't mention CIFS anywhere in our documentation, which leads me to believe that we don't support it because the engineering team doesn't test it. But I'll double-check to confirm.

Also, I'm noting the proper article for [moving the content library](https://docs.microsoft.com/sccm/core/plan-design/hierarchy/the-content-library#bkmk_remote)

**Comment by aczechowski** [comment]
Yep, as I suspected, we don't test CIFS, thus not technically supported. And as is always the case, we (generally) don't document what we don't support. Especially things that aren't tested. (We will document things that aren't supported when we know for sure.) 

Initial feedback from engineering: I'm sure the file operations will work, but the operations on ACLs and permissions may or may not work.

If you're passionate about product support for CIFS, see the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress.

I'm closing this issue as there's nothing actionable for docs at this time.
