### ISSUE TITLE
Consider adding more information on how to configure proxy on devices

### ISSUE THREAD

**Issue by davidpaMSFT** [MicrosoftDocs/SCCMdocs#1757]
For user proxy authentication and device proxy authentication, where specific device configurations are suggested, consider adding steps or links to documentation on how to make those specific configurations, i.e. "configure devices to use the signed-in user's context for proxy authentication", "configure a system-level proxy server on the devices" and "configure these devices to use device-based outbound proxy authentication".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf24a1d9-b5e0-7031-fe6d-dd49cfb8b58f
* Version Independent ID: 5d1a29bf-4299-6700-2797-7e24b931f598
* Content: [Enable data sharing - Configuration Manager](https://docs.microsoft.com/en-us/sccm/desktop-analytics/enable-data-sharing#feedback)
* Content Source: [sccm/desktop-analytics/enable-data-sharing.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/enable-data-sharing.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @davidpaMSFT for the feedback. I'll check if there are any articles that already exist we can link to. I don't want to add any content here, as it's really how Windows makes this connection.

**Comment by ganeshgkb** [comment]
we are not using any proxy server so no need to add above sites right?
clients are not reporting to Desktop Analytics and Configure manager.
please help.

**Comment by aczechowski** [comment]
@ganeshgkb, I'm sorry you're having trouble. I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

**Comment by AquinoN** [comment]
Looking for more insights on how to troubleshoot.  Once clients show "awaiting enrollment" - it's all black box for me from there.  I see nothing in DA online and no new status in ConfigMgr.  Not sure how to test those sites in the list since some of them come up as 404 no matter what network I'm on (4G, Library, Office, Home, Etc...) - No proxy server involved (from what customer states).

**Comment by aczechowski** [comment]
Earlier this year we made some big changes to this article for proxy. And we recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. So I'm going to close this issue. If you think content still requires additional clarification, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
