### ISSUE TITLE
Erroneous step reference under Delaying Domain Join to Avoid Application of Group Policy Objects

### ISSUE THREAD

**Issue by baardhermansen** [MicrosoftDocs/SCCMdocs#1759]
In step 13, there's a reference to step 9, but that would take the reader several steps back. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc2393d-6a81-c9c9-87bb-b40b66f26d68
* Version Independent ID: fda85f4c-33ec-d0aa-b793-381d2bebb57d
* Content: [MDT samples - Microsoft Deployment Toolkit](https://docs.microsoft.com/en-us/sccm/mdt/samples-guide#delaying-domain-join-to-avoid-application-of-group-policy-objects)
* Content Source: [sccm/mdt/samples-guide.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdt/samples-guide.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by jpcast88** [comment]
@aczechowski @baardhermansen I believe this should forward the user to step 16 rather than backwards to step 9.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
