### ISSUE TITLE
Required permissions for AdminService.log

### ISSUE THREAD

**Issue by AquinoN** [MicrosoftDocs/SCCMdocs#1764]
In my lab environment, I had to grant the service account that I'm using for the administration service with read permissions on the AdminService.log file.  Since it rolls, I had to grant read on the logs directory.  The AdminService.log file indicates specifically that "Error: System.UnauthorizedAccessException:Access to the path '...\logs\AdminService.log' is denied."

When I grant read permissions to the service account, it works.

**Comment by AquinoN** [comment]
FYI - this is related to this article: https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/plan-for-the-sms-provider

**Comment by aczechowski** [comment]
Hi @AquinoN, that sounds like a product bug. I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. We don't generally document product bugs, other than specific circumstances, so I'm closing this issue.
