### ISSUE TITLE
Server SP1 has very high anti-malware CPU

### ISSUE THREAD

**Issue by baardhermansen** [MicrosoftDocs/SCCMdocs#1789]
There seems to be a need for adding exclusions to the anti-malware engine, as it sits up around 50% CPU for hours on end.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0102ce75-ee5b-675a-0ea2-c4f57a6e9087
* Version Independent ID: 04cdc4e8-6092-fe00-b560-abe5270748d3
* Content: [Create a lab in Azure - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/get-started/azure-template)
* Content Source: [sccm/core/get-started/azure-template.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/azure-template.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @baardhermansen for taking the time to provide feedback on Configuration Manager! I think this would best be captured as *product feedback*, and I want to make sure it gets directly into the hands of the engineering team. See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
