### ISSUE TITLE
External Trusted Domain scenario is missing

### ISSUE THREAD

**Issue by Inderpreet-S** [MicrosoftDocs/SCCMdocs#1796]
Didn't find the scenario for external trusted domain client-configmgr communication.
I have tested the scenario with following steps and it worked.

eg. a.A.com and b.B.com has two way external trust (No forest trust). configmgr is in A.a.com and Client is in b.B.com.
Step 1 - Created System Management container in b.B.com
Step 2 - Gave b.B.com\sccmadmin account full permissions to this container.
Step 3 - Extended schema of b.B.com
Step 4 - Added b.B.com forest in the configmgr with b.B.com\sccmadmin account.
Step 6 - Created boundary and boundary groups for clients in b.B.com.
Step 7 - Clients started communicating to MP which is in a.A.com.

This scenario should be added to the document for customer ease.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d18ae0ff-df2d-dbae-7d45-816b0d15ad65
* Version Independent ID: dfcaba91-fdf5-a6c4-9d60-57e1542f1914
* Content: [Communications between endpoints - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/communications-between-endpoints#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/communications-between-endpoints.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/communications-between-endpoints.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Inderpreet-S for the feedback

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
