### ISSUE TITLE
Device Compliance Status

### ISSUE THREAD

**Issue by ChristineBoersen** [MicrosoftDocs/SCCMdocs#1797]
(using 1902) Can we have the Device Compliance status not count non-agent enabled machines in the count?

Currently every networking and non-windows device shows in non-compliant which is a little annoying

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e48c839-f6ee-2d03-6f5b-e0ffb05ec595
* Version Independent ID: 13547c80-3295-92e8-59c9-20e99948f2e8
* Content: [Monitor software updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/monitor-software-updates#feedback)
* Content Source: [sccm/sum/deploy-use/monitor-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/monitor-software-updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @ChristineBoersen for taking the time to provide feedback on Configuration Manager! This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
