### ISSUE TITLE
ConfigMgr + SSRS custom port issue (workaround)

### ISSUE THREAD

**Issue by imakaron** [MicrosoftDocs/SCCMdocs#1799]
One of my customers had faced an issue when they tried to change a Default TCP port of SSRS to custom. SSRS is working well but in the ConfigMgr srsrp.log we saw this error message: 
Reporting Services URL from Registry 
The request failed with HTTP status 404. Not found 
(!) SSRS not detected as running 

Workaround is
Option 1: change ReportServerUri parameter at registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\SMS\SRSRP
Like this: http://server:**/ReportServer
Option 2: remove/install ConfigMgr reporting service point

Could you please add this to the docs as a note?

**Comment by mestew** [comment]
Thanks @imakaron for the feedback.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.

**Comment by ahnvcc** [comment]
@imakaron 
This registry edit also works when ConfigMgr enters the wrong port for the ReportServer during installation and you want it on the default 443. Thanks
