### ISSUE TITLE
Software Center does not display applications and packages as available that are deployed to user or user group collections.

### ISSUE THREAD

**Issue by ThomasKur** [MicrosoftDocs/SCCMdocs#1812]
I'm not sure, but in my test environment this is working fine. So, perhaps you can remove this restriction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 980e2274-7f4a-08cb-4c3d-cdf23e6552c7
* Version Independent ID: f6c565a3-f371-1c56-cac3-84c08338016a
* Content: [CNG certificates overview - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/network/cng-certificates-overview)
* Content Source: [sccm/core/plan-design/network/cng-certificates-overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/network/cng-certificates-overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
I'm checking with the engineering team to confirm

**Comment by aczechowski** [comment]
Thanks again for the feedback. We moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
