### ISSUE TITLE
Please include permissions needed

### ISSUE THREAD

**Issue by phoenix79** [MicrosoftDocs/SCCMdocs#1814]
I'm not sure where else I can put this, so it's going here. Please include which SCCM permissions are needed for the various tasks. The client notification page (https://docs.microsoft.com/en-us/sccm/core/clients/manage/client-notification) lists permissions needed for each line item. That is very handy for being able to drill down non-admin permissions. If this documentation exists elsewhere, I have not been able to find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40b09ab0-2f1f-253b-a9a5-f42f9d3c704c
* Version Independent ID: eeea0bf0-0544-f251-9c62-5f4a42b4d2e1
* Content: [Configure client settings - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/deploy/configure-client-settings#feedback)
* Content Source: [sccm/core/clients/deploy/configure-client-settings.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/configure-client-settings.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @phoenix79, thanks for the feedback. I get what you're saying, but unfortunately it's not really actionable in its current form. For new features, we try to collect and document the necessary permissions. There are likely historical content for older features that don't list it. There was a spreadsheet that one of the former writers put together years ago, which I don't think is still publicly available, that listed the permissions for the default roles. That was a massive project to put together, and would be a similarly large project to update. 
I don't think this issue is actionable because it's too broad, I don't think we could easily track it towards resolution. So I'm going to close this issue. If you come across a specific article/feature that doesn't list the required permissions but you think it should, please file an issue for that specific instance, and then we can work on resolving them in that manner. I think that's a more actionable process.
