### ISSUE TITLE
Please update for Windows 10

### ISSUE THREAD

**Issue by Field5555** [MicrosoftDocs/SCCMdocs#1815]
&lt;EOM&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 050dc241-8019-e6b2-1cfd-39f95f6fb41d
* Version Independent ID: 7d358f76-efc4-7492-d416-106523d17181
* Content: [Quickstart - LTI - Microsoft Deployment Toolkit](https://docs.microsoft.com/en-us/sccm/mdt/lite-touch-installation-guide#feedback)
* Content Source: [sccm/mdt/lite-touch-installation-guide.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdt/lite-touch-installation-guide.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
