### ISSUE TITLE
no alerting for failed upstream synchronizations with msft updates in sccm

### ISSUE THREAD

**Issue by chadparris** [MicrosoftDocs/SCCMdocs#1816]
Within sccm alerting, there is no option to alert and subscribe to failed upstream synchronizations. There is a bug where when product categories change in the update point catalog, the upstream synch fails. If you don't catch this, you are not getting updates.
This is not listed as one of the current alerts.

**Comment by aczechowski** [comment]
Thanks @chadparris for taking the time to provide feedback on Configuration Manager! This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
