### ISSUE TITLE
icons in sccm device view are not sortable

### ISSUE THREAD

**Issue by chadparris** [MicrosoftDocs/SCCMdocs#1817]
within the device view in sccm, you can clearly see an icon that appears to have functions. I observe the base differences to be:
1) It can be nothing, which means no client no data but discovered or added to sccm somehow.
2) client but not online
3) client but no discovery data
4) client and online

What's odd is that when you try to sort by this column, it lines up in no particular order. Odd. Either the icons mean something, and you can sort by them, or they don't.

**Comment by aczechowski** [comment]
Hi @chadparris 
We already have client status documented here: https://docs.microsoft.com/sccm/core/clients/manage/monitor-clients#bkmk_indStatus
If you have concerns with the details of that article, please file feedback from that article (to properly link the article with the issue). For more information on filing doc issues, see https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_docfeedback

Otherwise, if the product currently doesn't allow sorting by that column, then that's product feedback. I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress.

I'm closing this issue as there's nothing actionable for docs at this time.
