### ISSUE TITLE
sccm client actions menu not available within deployment status windows

### ISSUE THREAD

**Issue by chadparris** [MicrosoftDocs/SCCMdocs#1818]
from the deployments list, you cannot open the "in progress", "error" or "unknown" list of clients and perform client actions against them.
These are normally referred to as "right click" functions by operators, because most people have recast tools installed and this is how to call them up.
Additionally, once you have a list of these open, for example, the "in progress" ones, you cannot go back to the deployment status page and pull up the "unknown" ones without closing the node.
This is also the case for multiple failure codes within "error". Once you have one error code open, you have to "close all nodes" to get the next ones.
Being able to open ALL THE CLIENTS that have an error, regardless of type, and run the right-click function against them would be very helpful. Like, "restart sccm client" or "reboot" or "fix remote comms issues" or "update compliance status" or "run update evaluation". Most of us use tools like Client Center for Config Manager for this, but it will not action 50 clients at once. Would be cool if it did or if sccm did it directly.

**Comment by aczechowski** [comment]
Thanks @chadparris for taking the time to provide feedback on Configuration Manager! This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
