### ISSUE TITLE
SCCM device discovery and inventory maintenance suggested improvements

### ISSUE THREAD

**Issue by chadparris** [MicrosoftDocs/SCCMdocs#1819]
SCCM system discovery works very well once you get your non-windows objects out of your discovery OU's so they don't keep getting discovered.

That said, when you are doing lifecycle or rebuild operations in your environment you can end up with a lot of stale records. These are NOT the laptops that go offline for 3 months and then come back...these are systems that have been rebuilt from W7 to W10 or from W10 LTSB to W10 {current release}. Unless sccm cleans itself up vs AD then the objects stay there until the maintenance job clears them out, and you can't have it be aggressive with AD discovered objects separately from inactive objects.

I would suggest that if a system is ADDED by AD System Discovery, it should be REMOVED by the same process when the AD object is removed. This basically means if a system is deleted from AD, and it was added via AD discovery, it will automatically be removed from SCCM when deleted from AD. Or at least the next time system discovery is run, if it's not there, it will be removed.

For workgroup machines, they should have to be manually removed or aged out.

For inactive machines & laptops that go on vacation, the existing maintenance aging jobs are just fine.

Some systems have a concept of "how added" which i observe in this schema as well. Using the "how added" to also "how removed" is what we are asking for here.

This prevents us from having to hack scripts on every site server to remove things that are in SCCM but NOT in AD anymore. Everyone is probably doing this exact same thing.

**Comment by aczechowski** [comment]
Thanks @chadparris for taking the time to provide feedback on Configuration Manager! This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
