### ISSUE TITLE
Logging information

### ISSUE THREAD

**Issue by Barleyologist** [MicrosoftDocs/SCCMdocs#1835]
This article does not do a good job of listing ConfigMgr logs to monitor for deployment. There is a small mention if error 0x80041001 in DcmWmiProvider.log but does not describe much more for logging information.  

E.i. Which log shows that it received the policy?  What do I look for?  this article says it might take two hours to process... can I see in the log somewhere that it processed the policy and will apply at x time?

Basically I am stuck trying to troubleshoot a deployment and this article is not helping me for what I should be looking for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f49b9244-7797-8fbb-afb9-dd245692be2f
* Version Independent ID: 5c7d7bde-2fe5-54f6-55fe-db4b2631f9a7
* Content: [Upgrade Windows devices to a different version - Configuration Manager](https://docs.microsoft.com/en-us/sccm/compliance/deploy-use/upgrade-windows-version)
* Content Source: [sccm/compliance/deploy-use/upgrade-windows-version.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/compliance/deploy-use/upgrade-windows-version.md)
* Product: **configuration-manager**
* Technology: **configmgr-compliance**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
