### ISSUE TITLE
DOINC for ISP

### ISSUE THREAD

**Issue by omidkosari** [MicrosoftDocs/SCCMdocs#1855]
Is it possible to use DOINC in an ISP for serving ISP customers without client setting change ? 
I am looking for a way or workaround to create a repository of Microsoft updates and our ISP clients automatically use it because it is nearest too them and helps us to save bandwidth.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3da55fd-6184-9baa-9278-9d807a7e44db
* Version Independent ID: 115bdf2d-7766-0053-11b2-5d36260fe4f8
* Content: [Delivery Optimization In-Network Cache - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/delivery-optimization-in-network-cache)
* Content Source: [sccm/core/plan-design/hierarchy/delivery-optimization-in-network-cache.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/delivery-optimization-in-network-cache.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @omidkosari, can you please define what you mean by "ISP"?

**Comment by omidkosari** [comment]
> 
> 
> Hi @omidkosari, can you please define what you mean by "ISP"?

Hi @aczechowski , I mean "Internet Service Provider" for example a company which buys 10Gb of Internet over fiber and then sells it over wireless/dsl/fiber to 1000 customers each one 10Mb .

I know lots of these ISPs around the world that Microsoft updates can take more than 50% of their overall bandwidth in peak times. Their current solution is throttle Microsoft updates or try to use unofficial workarounds.

Please also see https://configurationmanager.uservoice.com/forums/300492-ideas/suggestions/38537455-delivery-optimization-cache-as-public-cdn

**Comment by aczechowski** [comment]
Thanks @omidkosari for the clarification. I'm working with the feature team to get more information.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.

ConfigMgr doesn't support this functionality, but Windows might support it otherwise.
