### ISSUE TITLE
Server 2019 DC Core

### ISSUE THREAD

**Issue by pfurches** [MicrosoftDocs/SCCMdocs#1856]
Windows Server Datacenter Core 2019 supports WDS according to: 
https://docs.microsoft.com/en-us/windows-server/get-started-19/editions-comparison-19#server-roles
Is the statement "Distribution points on this OS don't support PXE or multicast with the default Windows Deployment Services" still valid for Server DC Core 2019 and ConfigMan 1902/1906?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dc0edfd-7799-9246-2e23-f202e31517f9
* Version Independent ID: 8c401426-fcf8-79a9-08fa-95a724b5756d
* Content: [Supported site system servers - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/supported-operating-systems-for-site-system-servers#feedback)
* Content Source: [sccm/core/plan-design/configs/supported-operating-systems-for-site-system-servers.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/supported-operating-systems-for-site-system-servers.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @pfurches for taking the time to provide feedback on Configuration Manager! While it might technically work, it's not supported because we haven't tested it. 

I suggest filing [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) to get this feedback directly into the hands of the engineering team. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress.

I'm closing this issue as there's nothing actionable for docs at this time.
