### ISSUE TITLE
Schema mapping between Windows Analytics and Desktop Analytics

### ISSUE THREAD

**Issue by elang-bmrn** [MicrosoftDocs/SCCMdocs#1859]
There are several differences in the Azure Log Analytics schemas between Windows Analytics and Desktop Analytics.

Could you please add a section to this page that describes and depicts how these two map to each other, so that custom solutions can leveraging this data can be updated to use Desktop Analytics?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8d7ece-b19f-1431-a619-e57ce6469c28
* Version Independent ID: 86a3d7a5-695b-d3d9-498c-e6b6e03169f8
* Content: [Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/sccm/desktop-analytics/overview#feedback)
* Content Source: [sccm/desktop-analytics/overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @elang-bmrn for taking the time to provide feedback on Desktop Analytics! After discussing with the feature team, I'm going to treat it as product feedback. I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by elang-bmrn** [comment]
Hi Aaron,

Could you please see support case # 119090624000410 before I submit this as product feedback on UserVoice?

Thanks,

Edward
