### ISSUE TITLE
wrong logging 

### ISSUE THREAD

**Issue by KONIKPK** [MicrosoftDocs/SCCMdocs#1860]
This is not helpful in 1906.
There must be some changes to logging.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0bd4ec1-b40c-548c-2c3b-91f061d3789d
* Version Independent ID: 97757717-5fbc-7586-b341-a4633cec8fe4
* Content: [Troubleshooting CMPivot - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/cmpivot-tsg)
* Content Source: [sccm/core/servers/manage/cmpivot-tsg.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/cmpivot-tsg.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @KONIKPK for taking the time to share your feedback with the Configuration Manager documentation team.

If you think the product itself needs changes to logging, please file [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) to make sure it gets directly into the hands of the engineering team. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress.

If you’re having problems, I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time. If there is something specific in the documentation that you think we need to improve, please reopen this item with additional detail.

**Comment by mestew** [comment]
-Reopening. There have been changes. Looking into this now. I know 1906 had a change for the smsprov.log where it seems to be "client operation 145" rather than 135. I also know state messages are only used when data returned is something like > 80kb, otherwise we use the "fast channel"/client notification.  You can see the info in the client in ccmnotificationagent.log and I'm pretty sure on the server side you see the result in bgbserver.log.  I am trying to get a list of changes in each version since 1810.
![image](https://user-images.githubusercontent.com/33289333/64633233-ad324080-d3af-11e9-8cf5-661713596c69.png)

**Comment by mestew** [comment]
@KONIKPK I have these doc changes lined up. I suspect the article will be updated early next week.
