### ISSUE TITLE
'Type' property details are missing in the documentation

### ISSUE THREAD

**Issue by SavindraSingh** [MicrosoftDocs/SCCMdocs#1886]
When we run below command on a server where we have some pending patches:
Get-WmiObject -Namespace root\ccm\clientsdk -class Ccm_SoftwareUpdate -Filter ComplianceState=0
It is showing several properties and values including 'Type: 2'.
However, in the document above, I can't see the details of 'Type' property and what does value 2 indicates.
Can someone please add these details in the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd02010e-cce1-6aa0-cd07-8a07858100e7
* Version Independent ID: 68c70bef-34c4-9eb9-117a-7d7955399e64
* Content: [CCM_SoftwareUpdate Class - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/core/clients/sdk/ccm_softwareupdate-client-wmi-class)
* Content Source: [sccm/develop/reference/core/clients/sdk/ccm_softwareupdate-client-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/core/clients/sdk/ccm_softwareupdate-client-wmi-class.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
