### ISSUE TITLE
Adding indexes and removing Expired updates from Replica (additional SUP) that uses WID does not work by default

### ISSUE THREAD

**Issue by BroadArc** [MicrosoftDocs/SCCMdocs#1888]
1. Using SCCM 1906
2. The Main SUP DB is located within SQL Server that also has the SCCM DB
3. Windows Server 2016 Secondary MP/SUP use WID (server name is: SUP2.domain.com)

How does one go about to make this work?

Indexing Failed. Could not connect to SUSDB. SqlException thrown while connect to SUSDB in Server: <SUP2.domain.com>. Error Message: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)

Could not Delete Obselete Updates because ConfigManager could not connect to SUSDB: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) UpdateServer: <SUP2.domain.com>

**Comment by aczechowski** [comment]
Thanks @BroadArc for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by AquinoN** [comment]
Same exact issue with ConfigMgr2006 - We have three SUPs - one on Primary (active) and two downstream (replicas).  Because they are replica servers, you cannot manually decline the updates.  We're working on 29k updates that we need to get rid of.

The referring article on the issue with 1906 is here (still issue with 2006):
https://docs.microsoft.com/en-us/mem/configmgr/sum/deploy-use/software-updates-maintenance#known-issues-for-version-1906

It directs you here:  
https://docs.microsoft.com/en-US/troubleshoot/mem/configmgr/wsus-maintenance-guide

We created the custom indexes, reindexed, queried for updates (29k) but can't decline them with the script.

**Comment by aczechowski** [comment]
Hi @AquinoN, I'm sorry that you're having problems. As I mentioned above, it's probably best to engage with Microsoft Support to investigate your issue.

@mestew shared the following with me in regards to your description:

WSUS Replicas inherit declinations from their upstream. If its not happening, you need to call support because you probably have a sync issue, or you're hitting a 10 minute hard coded timeout on syncing hidden items from the upstream (which is an old bug rarely seen today but its possible to still hit it)

[Windows Server Update Services (WSUS) maintenance guide for Configuration Manager](https://docs.microsoft.com/troubleshoot/mem/configmgr/wsus-maintenance-guide#decline-superseded-updates):

> You don't need to run the PowerShell script on WSUS servers that are set as replicas, such as secondary site SUPs. To determine whether a WSUS server is a replica, check the **Update Source** settings.
