### ISSUE TITLE
"Remote control anywhere using Cloud Management Gateway" section - Not working with SCCM Admin Console (version 5.1906.1096.1600)

### ISSUE THREAD

**Issue by irfan-fakih** [MicrosoftDocs/SCCMdocs#1901]
Hi, 
Based on the current Microsoft documentation (above page) - https://docs.microsoft.com/en-us/sccm/core/get-started/2019/technical-preview-1906#remote-control-anywhere-using-cloud-management-gateway

I would like to provide some feedback of remote control functionality using CMG.  I noticed, when I tried to take remote control of an ONLINE laptop that is successfully connected to CMG (confirmed), the "Remote Control Address Connection" dialog box does not give options to select items like "Connect via CMG or HTTPS MP", etc.  (it is the same old dialog box).  I also verified the "standalone remote control viewer" file from adminconsole\bin\i386\CmRcViewer.exe, and this also gives the same old dialog box.

But, I am running a newer CM CB 1906 Admin Console (version 5.1906.1096.1600).  
Please advice.  Thank You - Irfan.Fakih@hotmail.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 665f93d6-3748-8bf8-c0db-fac2a4702d61
* Version Independent ID: 527f481e-e003-6b4d-a2d2-273dc1134b01
* Content: [Technical preview 1906 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/get-started/2019/technical-preview-1906#feedback)
* Content Source: [sccm/core/get-started/2019/technical-preview-1906.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/2019/technical-preview-1906.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for taking the time to provide feedback on Configuration Manager! I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
