### ISSUE TITLE
Maintenance Windows

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/SCCMdocs#1905]
Doc should define what the impact is if there are now MWs configured for the endpoint.  In reference to:

---
The following settings must be shorter in duration than the shortest maintenance window applied to the computer:

Display a temporary notification to the user that indicates the interval before the user is logged off or the computer restarts (minutes)
Display a dialog box that the user cannot close, which displays the countdown interval before the user is logged off or the computer restarts (minutes)
---

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3f43b73-de34-a8b0-13c6-c647724161e0
* Version Independent ID: 39e43e5b-626b-b5b9-67de-f7f7a39950cd
* Content: [Device restart notifications - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/deploy/device-restart-notifications#feedback)
* Content Source: [sccm/core/clients/deploy/device-restart-notifications.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/device-restart-notifications.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.

These settings are explained else where in the article, this bit just calls out the necessary configuration if you're using maintenance windows.
