### ISSUE TITLE
The list of ObjectTypes seems to be missing a few items

### ISSUE THREAD

**Issue by SamuelPoulin** [MicrosoftDocs/SCCMdocs#1924]
As found here: https://stackoverflow.com/questions/52101914/powershell-move-collection-to-another-folder-in-sccm

ObjectTypes 5000, 5001, 6000 and 6001 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ca84dd2-c6a5-1f36-11e0-dae1b53d1a35
* Version Independent ID: ed1abc60-7fd1-d860-30a0-e0248aa38642
* Content: [SMS_ObjectContainerItem Class - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/core/servers/console/sms_objectcontaineritem-server-wmi-class)
* Content Source: [sccm/develop/reference/core/servers/console/sms_objectcontaineritem-server-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/core/servers/console/sms_objectcontaineritem-server-wmi-class.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
