### ISSUE TITLE
Unable to get MDM Authority

### ISSUE THREAD

**Issue by pedrr** [MicrosoftDocs/SCCMdocs#1956]
Hi, we want to switch the MDM authority, but receiving the error "Unable to get MDM Authority"
As we found out with MS Support, the described workflow doesn't work anymore after 1. Sept. and a Service Request ist necessary.
Can you please update the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b82df45-3900-c15c-5838-6983b6a862f5
* Version Independent ID: 86ff67a2-f224-096b-7905-ec5d6523c4bd
* Content: [Change your MDM authority to Intune - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/deploy-use/migrate-change-mdm-authority#feedback)
* Content Source: [sccm/mdm/deploy-use/migrate-change-mdm-authority.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/deploy-use/migrate-change-mdm-authority.md)
* Product: **configuration-manager**
* Technology: **configmgr-hybrid**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @pedrr, sorry for the problems. We announced hybrid MDM deprecation in August 2018, and discontinued the service in September 2019. For more information, see the main [hybrid MDM](https://docs.microsoft.com/sccm/mdm/understand/hybrid-mobile-device-management) article. We plan to completely retire the documentation in a couple of months. Since we're no longer maintaining this content, I'm closing this issue.
