### ISSUE TITLE
Use Multiple SMS Providers

### ISSUE THREAD

**Issue by ITOpsReborn** [MicrosoftDocs/SCCMdocs#1959]
What number is considered many?

"Many administrative users need to use the Configuration Manager console and connect to a site at the same time."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 070c2bc6-3086-7237-d19c-951f000b4531
* Version Independent ID: 95c62945-77dc-0ce0-e4ee-1116343b7ea6
* Content: [Plan for the SMS Provider - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/plan-for-the-sms-provider#BKMK_MultiSMSProv)
* Content Source: [sccm/core/plan-design/hierarchy/plan-for-the-sms-provider.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/plan-for-the-sms-provider.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks again for the feedback. We moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
