### ISSUE TITLE
Is Cumulative Updates considered security or feature updates?

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/SCCMdocs#1989]
Are Cumulative Updates considered quality/ security or feature updates? 

We defer security updates for 5 days, and feature updates for 15 days. 
[KB4522355 (OS Build 18362.449)](https://support.microsoft.com/en-us/help/4522355/windows-10-update-kb4522355) was released october 24th, we've still not received it, even when manually triggering "check for updates" in Windows Updates.
* Are cumulative updates considered feature updates?

Some clearification about this in the documentation would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85ae5b79-2cc7-1a6b-10e2-3ff434dbc521
* Version Independent ID: 588472d2-8f23-56e8-ed59-1501a9557c3f
* Content: [Integrate Windows Update for Business - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/sum/deploy-use/integrate-windows-update-for-business-windows-10)
* Content Source: [sccm/sum/deploy-use/integrate-windows-update-for-business-windows-10.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/integrate-windows-update-for-business-windows-10.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@o-l-a-v 
Hey Olav,
We try to keep this type of info listed in the [products and classifications article](https://docs.microsoft.com/configmgr/sum/get-started/configure-classifications-and-products#to-configure-classifications-and-products-to-synchronize). But I suspect some detail can be added to it. 

- Cumulative Updates are't considered Feature Updates. Feature Updates are pretty much always in classification = *upgrades*. OS CUs are usually in the *Security Updates* Classification or the *Updates* classification.
- Typically speaking, most Windows 10 CUs released on the second Tuesday (A.K.A. "B week" or "Patch Tuesday") are in the *Security Updates* Classification. CUs not released in B week are usually in the *Updates* classification, like [KB4522355](https://support.microsoft.com/en-us/help/4522355/windows-10-update-kb4522355).
    - Easy way to look at the classifications and product an update is under is just to search the KB number at https://catalog.update.microsoft.com 
    - You can also check the bottom of the KB article, usually they list the product & classification, along with if the update auto-syncs for WSUS or not. 
- A lot of people don't sync the *Updates* classification, so that's the first thing I would double check 
   - Basically verify it's in the CM console, if not, make sure the product and classification are both selected in the SUP properties for sync. 
   - If the client is scanning against a child primary, I would also verify that the SUP sync from CAS to Pri is ok and that I see the update in the primary site's WSUS server. 
- If the update is in CM and WSUS, I would start verifying that the client is scanning successfully and actually sees the UpdateID of it in the logs.
- The client itself determines if the update is applicable to it or not. I like to see what the CCM client thinks about the update by looking at it in WMI under the ROOT\CCM\SoftwareUpdates\UpdatesStore namespace. I just dump it all out to a csv file with the following cmd `wmic /namespace:\\root\ccm\softwareupdates\updatesstore path CCM_UpdateStatus get status, Article, Bulletin, UniqueId >c:\updatecompliance.csv` CCM gets the info right from the Windows Update Agent so it saves me from digging into a verbose windowsupdate.log/etl (unless I really need to determine why an update isn't applicable to a machine and I think something pretty unusual is going on). 

If you're interested, there is an old software updates white paper that walks through almost every step for software updates. It was published for CM 2012 R2, but the basic info is still the same. We've just added more bells and whistles in the past few years, like the ability to install upgrades for Windows 10 and delta content : https://www.microsoft.com/en-us/download/details.aspx?id=44578

Hope this helps! Let me know if you have specific details that you think should be added to the products and classifications page.

**Comment by o-l-a-v** [comment]
Thanks for the clearification @mestew.

So that means if we're currently enrolled in Windows Update for Business update ring "SAC" or the deprecated "SAC-T" with 0 days deferral on quality updates, we should get .449 tomorrow?
