### ISSUE TITLE
Several SCCM instances

### ISSUE THREAD

**Issue by JoakimSandberg** [MicrosoftDocs/SCCMdocs#1990]
We´re using several Configuration manager instances and we only have 1 AzureAD tenant. When will support for several instances? We don´t want to get a separate tenant just for this and it feels bad to leave out 3/4 of the company.

**Comment by aczechowski** [comment]
Hi @JoakimSandberg, thanks for taking the time to provide feedback on Configuration Manager! I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
