### ISSUE TITLE
Method no longer exists

### ISSUE THREAD

**Issue by ultimal** [MicrosoftDocs/SCCMdocs#2003]
I'm looking at the WMI object on SCCM and this method doesn't exist on any of the instances of this class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28e531bb-6cd0-b5d7-22ca-5d4bf2d650a7
* Version Independent ID: 411f20be-e8b1-9cd3-3649-cad394ff1d5e
* Content: [SMS_DistributionPoint class - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/develop/reference/core/servers/configure/sms_distributionpoint-server-wmi-class#feedback)
* Content Source: [sccm/develop/reference/core/servers/configure/sms_distributionpoint-server-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/core/servers/configure/sms_distributionpoint-server-wmi-class.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @ultimal, which method? This doc for the SMS_DistributionPoint class lists two: VerifyPackage & CancelDistribution

**Comment by aczechowski** [comment]
Thanks for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.

**Comment by ultimal** [comment]
It was my fault for not knowing how to call it using Powershell. Those
methods are available and correctly documented.

Thanks for looking at it, sorry for the trouble.

Haider Raza
