### ISSUE TITLE
Max Allowed Runtime vs overlapping MW

### ISSUE THREAD

**Issue by DanielKaro** [MicrosoftDocs/SCCMdocs#2016]
Hi,
The Maximum allowed run time does not handle the overlapping MWs as one.
If you have 3 61min long overlapping MWs and the Maximum allowed runtime is the default 120 min the deployment fail but this document says the overlapping MWs are handled as one which is not true in this case.

(admin edit: adding article metadata to properly link issue)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a69524-75f1-5c55-5091-66b7c3326a7b
* Version Independent ID: 48b982d2-1ee9-7d2a-a1f9-14cdf0dadb6a
* Content: [Use maintenance windows - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/manage/collections/use-maintenance-windows)
* Content Source: [sccm/core/clients/manage/collections/use-maintenance-windows.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/collections/use-maintenance-windows.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @DanielKaro - can you help clarify which article you're referencing? This setting is mentioned in multiple places.

p.s. if you use the feedback option labeled **this page** it automatically links with the current article. if you leave feedback directly on GitHub, it just creates the issue without creating that link.

**Comment by DanielKaro** [comment]
Hi Araon,
Sorry i thought i opened the request directly from the link.
This is document i was referring to:
https://docs.microsoft.com/en-us/configmgr/core/clients/manage/collections/use-maintenance-windows

Regards,
Daniel

Aaron Czechowski <notifications@github.com> ezt írta (időpont: 2019. nov.
25., H, 20:52):

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.

If the behavior that you're seeing isn't the same as documented, it may be a bug. Please [file a frown](https://docs.microsoft.com/mem/configmgr/core/understand/find-help#product-feedback).
