### ISSUE TITLE
Details on Drivers as Assets

### ISSUE THREAD

**Issue by CCDFischer** [MicrosoftDocs/SCCMdocs#2034]
The Next Steps section links to "Assets" and indicates that this will give more information about devices, drivers, and apps. However that section does not contain a section for drivers, only for devices and apps. This seems to reflect what is available in the main interface of Desktop Analytics, however driver information is of critical importance to us to asses blocking drivers that may be on our endpoints.
Can you please provide additional information about how drivers are pulled into DA and how we can get the information we need?

(admin edit: changing metadata to link to the better target article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98e17ff5-05a2-d064-b8c8-4bc750887c67
* Version Independent ID: b55eabd7-0528-b61a-e420-112ebc1c8dc7
* Content: [Assets in Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/desktop-analytics/about-assets)
* Content Source: [sccm/desktop-analytics/about-assets.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/about-assets.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @CCDFischer for the feedback. I'll check with the PM team about developing some more detail on this topic.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
