### ISSUE TITLE
It doesn't answer the question "What happened to the Ready for Windows website?"

### ISSUE THREAD

**Issue by dombat** [MicrosoftDocs/SCCMdocs#2040]
The very first heading is "What happened to the Ready for Windows website?" but it is not answered, it just says "use these other tools". Does it still exist?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68cda745-d67b-253d-1bf8-4f4704b541d2
* Version Independent ID: 15dc7df4-e435-9ddc-4a00-826e8802cf14
* Content: [Ready for Windows - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/desktop-analytics/ready-for-windows#feedback)
* Content Source: [sccm/desktop-analytics/ready-for-windows.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/ready-for-windows.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by iceorbital** [comment]
The readyforwindows.com site is no longer available. We've heard from IT admins they want these insights integrated with the tools they already use to plan their deployments. Use Desktop Analytics and Office 365 ProPlus readiness features in Configuration Manager to plan and manage your Windows 10 and Office 365 ProPlus upgrades

**Comment by aczechowski** [comment]
@dombat it's also implicit in that the URL redirects to this article.

**Comment by laitnetoPx** [comment]
The real question here is this..

Two weeks after someone downloads the evaluation iso for Windows 10 Enterprise, when they receive an email from Windows for Business encouraging them to use the Ready for Windows Directory, which starts with a big box around a hyperlink that says "Directory search>" and ends with another hyperlink to the same webpage as the first one that says "Find supported applications now"; should the webpage that is the target of the two links say in big bold letters below the Windows logo and Microsoft name "Ready for modern desktop retirement FAQ" and then begin by asking "What happened to the Ready for a Windows website?" and at the bottom have a comments section that, despite the docs.microsoft.com url of the page, requires logging in with a github account to be able to comment?

I'm just assuming the answer is "Absolutely not, because that would be sloppy, unprofessional and confusing."

Smh... little things like this might seem trivial and probably don't have much influence, but something so avoidable should be avoided.  Are people going to cut ties with Microsoft because of something like this? Probably not.  But it could definitely have a negative influence on someone currently evaluating Windows 10 Enterprise, which could be a new customer or an existing customer, and could be enough to make them consider other options, or evaluate other options, or even actually choose another option over Windows and Microsoft.  Even if it only had such an impact on one customer or even if nobody cared at all, isn't just that little bit of risk of negative impact enough to justify the cost of paying someone to make sure avoidable outward facing mistakes are in fact avoided?
