### ISSUE TITLE
Express installation vs Full file content 

### ISSUE THREAD

**Issue by Anoni-Mouse** [MicrosoftDocs/SCCMdocs#2053]
I'm a bit confused here, probably due to English being my thirst language here. What confuses me is this sentence:

Due to the nature of express installation files, their content size is considerably larger than traditional full-file content.

How can anything be larger than the full file size? Logically anything else should be either less or at most equal in size to the full file. So how can an express update be larger than the full file? I'm not the only one confused here, I've spoken to many people confused like me. Can you please explain better? 

Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: def581b6-f8e0-f512-2113-9c3495be54c2
* Version Independent ID: 8effe9f9-9e7b-3d6e-033c-639b56acd648
* Content: [Optimize Windows 10 update delivery - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/sum/deploy-use/optimize-windows-10-update-delivery#feedback)
* Content Source: [sccm/sum/deploy-use/optimize-windows-10-update-delivery.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/optimize-windows-10-update-delivery.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @Anoni-Mouse for the feedback. We'll work on revising to clarify. Maybe we just need to remove "full-file" from the description? @mewtew is the expert in this area. 😄

For your immediate info, an express update is a different format than a traditional update. The express update format includes more content, to allow for more dynamic usage. The server can host one *large* express update file. Then depending upon the specific client build, the client downloads only a portion of the express update content that it needs.

With a traditional update, the client just downloads the entire content and unpacks it. So express files help to reduce the content transfer in the final communication to the client. But they do require more backend storage due to their larger size.

**Comment by mestew** [comment]
@Anoni-Mouse yeah, we should probably tweak this. That should probably read "self-contained" rather than "traditional full-file content". Express files are much bigger than what most people would consider "traditional content files" for updates...although express files have been around in the WSUS world for a very long time, so the word "traditional" is relative =) 
For giggles,  I randomly selected a security update and peeked at the file info in WSUS just to get a quick picture of how the sizes differ.  You'll notice that the 2 express files needed for the update are larger than the single self contained content file. This massive difference in the payload is pretty much the norm for every update with express files.   
![image](https://user-images.githubusercontent.com/33289333/70187323-bf680600-16a2-11ea-8dd7-6ce78912545f.png)

**Comment by mestew** [comment]
Updating this shortly. Also added WSUS doc link that discuses trade offs for express files.
