### ISSUE TITLE
Client Data Sources

### ISSUE THREAD

**Issue by tunnelofsludge** [MicrosoftDocs/SCCMdocs#2069]
If a client uses a Microsoft Connected Cache server, does it report as Delivery Optimization or Distribution Point under Monitoring, Distribution Status, Client Data Sources?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1fbe6e8-4883-644e-8412-2e69759fe482
* Version Independent ID: 41f3fdea-c476-bd2b-131b-1100bbede7b2
* Content: [Microsoft Connected Cache - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/hierarchy/microsoft-connected-cache#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/microsoft-connected-cache.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/microsoft-connected-cache.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @tunnelofsludge for taking the time to provide feedback on Configuration Manager! I checked with the engineering team, Connected Cache server data usage isn't reported in the client data source dashboard today. 

This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress.

I'm closing this issue as there's nothing actionable for docs at this time.
