### ISSUE TITLE
Express Updates Port

### ISSUE THREAD

**Issue by pctec100** [MicrosoftDocs/SCCMdocs#2091]
This document is missing port 8005 used by the client for downloading express updates. The default port conflicts with systems running Apache Tomcat. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f658ee4b-d051-0d7c-4656-19a846908469
* Version Independent ID: 3478e881-199c-f0c4-b218-0dd609eb0427
* Content: [Ports used for connections - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/hierarchy/ports#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/ports.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/ports.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @pctec100 for the feedback. You can change the port that ConfigMgr uses with a client setting, see https://docs.microsoft.com/configmgr/core/clients/deploy/about-client-settings#port-that-clients-use-to-receive-requests-for-delta-content

**Comment by DavidHBaur** [comment]
The Port is not documented though and since it is an SCCM Port (even if it can be changed, still need to be added) as it is required for "Express Updates". Reference: https://docs.microsoft.com/en-us/configmgr/core/clients/deploy/about-client-settings#port-that-clients-use-to-receive-requests-for-delta-content   "Port that clients use to receive requests for delta content

(Introduced in version 1902)

This setting configures the local port for the HTTP listener to download delta content. It's set to 8005 by default. You don't need to open this port in the client firewall.  (is this true, no Firewall Port for any clients?)


７ Note

This client setting replaces Port used to download content for Express installation files.
"

**Comment by aczechowski** [comment]
I put in a change for this issue. It should publish live later this afternoon.
