### ISSUE TITLE
What about IBCM?

### ISSUE THREAD

**Issue by DavidHBaur** [MicrosoftDocs/SCCMdocs#2092]
Can you also "can download packages on-demand from a content-enabled CMG or a cloud distribution point." from an Internet Based Client Management Point that is also a DP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06c7ad2d-6857-22cb-003d-c1af09776c4f
* Version Independent ID: 2ac480ac-14d8-dea5-5163-9a83a17e00cc
* Content: [Deploy a task sequence - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/osd/deploy-use/deploy-a-task-sequence#deploy-windows-10-in-place-upgrade-via-cmg)
* Content Source: [sccm/osd/deploy-use/deploy-a-task-sequence.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/deploy-a-task-sequence.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @DavidHBaur, thanks for the feedback. This specific scenario is only tested with CMG. It might still work with IBCM, but not something we've tested. Since we generally don't document what we don't test/support, I'm closing this issue.
If you'd like the scenario to be considered for support, please file [product feedback](https://docs.microsoft.com/configmgr/core/understand/find-help#product-feedback).
