### ISSUE TITLE
Important! TS Installs Image Deployment Option

### ISSUE THREAD

**Issue by dr-raypc** [MicrosoftDocs/SCCMdocs#2114]
"For a task sequence that installs an OS image, don't use the deployment option to Download content locally when needed by the running task sequence. When the task sequence wipes the disk before it applies the OS image, it removes the client cache. Since the content is gone, the task sequence fails."  seems to be backwards. If the SCCM content is being downloaded locally and is then wiped, i would believe donwloading content locally when needed by running task sequence would begin downloading whatever that was wiped/cached.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4313411e-8322-21b1-da7f-4a1f21c58b10
* Version Independent ID: cfc0fe3f-667f-ff01-b623-75a315b8e1f6
* Content: [Configure pre-cache content - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/osd/deploy-use/configure-precache-content#feedback)
* Content Source: [sccm/osd/deploy-use/configure-precache-content.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/configure-precache-content.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @dr-raypc for taking the time to provide feedback on Configuration Manager! That behavior is how the task sequence works today.

If you want to suggest a product change, I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by dynas2001** [comment]
I think he was saying above your NOTE is in correct.  You have to select that setting or your content gets wiped out when the drive is cleaned.  It's the "download all content locally before starting task sequence" that should NOT be select, which isn't even an option anymore so the note can probably just be deleted. 

"download content locally when needed by the running task sequence" is the only option even anyway because the other option to download all content is what actually broke.

**Comment by aczechowski** [comment]
Hi @dynas2001, I just double-checked a few things. Here's my internal note on this issue from engineering:

> From doc bug 4092495, note that for a wipe & load TS, don't use pre-caching with "download on demand" deployment option on the distribution points tab. The wipe part will remove the cache, when the client package is required the local path is returned (SMB location), since the content is no gone the task sequence will fail.

And the deployment options are dynamic based on a number of factors. Here's a screenshot from the most recent build:
![image](https://user-images.githubusercontent.com/26784733/77950873-0d220300-727e-11ea-8bed-e15fc7276518.png)
I'm not able to snip a screenshot that shows both options in the list, but for this deployment, I can select:
- Download content locally when needed by the running task sequence
- Download all content locally before starting task sequence

If you're not seeing an option that you expect to see, please leverage available support channels for further assistance:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

**Comment by aczechowski** [comment]
FYI, I revised the warning in this article, and made a big updates to the [Deploy task sequence](https://docs.microsoft.com/mem/configmgr/osd/deploy-use/deploy-a-task-sequence) article section on deployment options. Thanks for the feedback, I hope this revision will help clarify for others. The changes should publish live tomorrow morning.
