### ISSUE TITLE
Microsoft Edge - NOTE 

### ISSUE THREAD

**Issue by JordanTheITGuy** [MicrosoftDocs/SCCMdocs#2117]
Starting in 1910 - Under the Microsoft Edge Management folder, you MUST set the download location to be the bottom of the folder tree. 

If you set it to anything else that has content in it you will receive an error message that just says "Invalid Location"

Submitted a bug through the console as well however it might be a good idea to mark a note that it must be an empty directory. 

https://docs.microsoft.com/en-us/configmgr/apps/deploy-use/deploy-edge?toc=https://docs.microsoft.com/DeployEdge/toc.json&bc=https://docs.microsoft.com/DeployEdge/breadcrumb/toc.json

(admin edit: add metadata for article linkage)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b7bd107-2a52-dcac-92a9-3b756a84114a
* Version Independent ID: 024860de-ea76-6bf5-06ad-0cc08d1a7949
* Content: [Deploy and update Microsoft Edge, version 77 and later - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/apps/deploy-use/deploy-edge)
* Content Source: [sccm/apps/deploy-use/deploy-edge.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/deploy-edge.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
Thanks again for the feedback. We moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
