### ISSUE TITLE
Task Sequences

### ISSUE THREAD

**Issue by Staja** [MicrosoftDocs/SCCMdocs#2178]
This document lacks any information on utilising MBAM in SCCM 1910 Task Sequences. The Pre-Provision BitLocker step does not backup the TPM owner password file to MBAM in SCCM 1910 it seems. How do we do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c7e528c-a28a-3b1a-372d-b17e4101a565
* Version Independent ID: a57fb032-3cf6-29b8-9114-b1ceb78ab2e4
* Content: [Deploy BitLocker management - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/protect/deploy-use/bitlocker/deploy-management-agent#feedback)
* Content Source: [sccm/protect/deploy-use/bitlocker/deploy-management-agent.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/bitlocker/deploy-management-agent.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Staja, a couple of notes:
- As of Windows 10 version 1607 we haven't backed up TPM passwords for security reasons. Reference the following Windows articles:
    - https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/manage-tpm-lockout#reset-the-tpm-lockout-by-using-the-tpm-mmc
    - https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/change-the-tpm-owner-password#about-the-tpm-owner-password
- The task sequence does nothing different with respect to BitLocker. Those tasks continue to work the same as they always have. If you want to submit a product suggestion for this integration, see the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress.

I'm closing this issue as there's nothing actionable for docs at this time.
