### ISSUE TITLE
The sample code of assign a package to a distribution point is never work

### ISSUE THREAD

**Issue by allencharp** [MicrosoftDocs/SCCMdocs#218]
SCCMdocs/sccm/develop/core/servers/configure/how-to-assign-a-package-to-a-distribution-point.md

The sample code above could successfully register a package to SCCM but the package could never be deployed to client after registration, because the package content could not be downloaded to client cache

We will have to create a content reference  with ContentRef object to solve the problem

**Comment by arob98** [comment]
@lleonard-msft Take a look at this issue and post an update.

**Comment by lleonard-msft** [comment]
@allencharp - I'm reviewing this now and will update when there's news to share.

**Comment by ameltzerMSFT** [comment]
@allencharp What is the specific scenario in the UI that you're trying to automate? Is it the "Distribute Content" option for a package?

In other words, this:
![image](https://user-images.githubusercontent.com/26661268/27348170-02d3d806-55a8-11e7-9e27-a0a72306febd.png)

**Comment by allencharp** [comment]
Hi, 

Currently I have a msi package, I want to use sdk to register the msi package into SCCM

I follow the sample code and also set the distribute content, the registeration seems successful

When I move the client machine for available installation, the msi could not be downloaded on cache folder, and show me the error code of 0x87D01106(-2016407290).

I search the problem, and find the site http://blog.lechar.nl/2012/04/11/application-wont-download-content/  complains the same problem as I am facing, and the site also gives me the solution to use "ContentRef"

**Comment by ameltzerMSFT** [comment]
@allencharp 

So you're trying to deploy an application or a package? In other words, if you were to do this manually in the console, which of these paths would you follow:
1, Software Library -> Application Management -> Applications
2. Software Library -> Packages

This is an important distinction because these both require very different methods to automate. 

The code sample you're referring to applies to scenario 2, while the site you linked to applies to scenario 1. As an aside, I'm not entirely sure that the code sample is even valid anymore.
