### ISSUE TITLE
OS image installation

### ISSUE THREAD

**Issue by mvagafonov** [MicrosoftDocs/SCCMdocs#2184]
We should consider to not advise to use client on the OS image but install it after OS deployment.  
https://docs.microsoft.com/en-us/configmgr/core/clients/deploy/deploy-clients-to-windows-computers#BKMK_ClientImage

**Comment by aczechowski** [comment]
Hi @mvagafonov, can you provide more detail as to why? It's technically a valid method. The current "important" note makes it somewhat invalid for an end-to-end scenario with ConfigMgr. But if you use ConfigMgr to create the image and then use that image for another purpose, then installing the client in the image might be applicable.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
