### ISSUE TITLE
TopicID 1701

### ISSUE THREAD

**Issue by choppystyx** [MicrosoftDocs/SCCMdocs#2194]
Are there any updates to the StateIDs for TopicID 1701? Have seen StateIDs 1,2,4,5,6 and 100 for 1701 within v_statemessagestatistics view.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 027e6f34-5116-a286-096d-b885e2f0b6e4
* Version Independent ID: d823689b-1074-2b99-d693-c71e4565fc83
* Content: [State messages - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/hierarchy/state-messaging-system-center-configuration-manager#1702-state_topictype_app_ci_enforcement)
* Content Source: [sccm/core/plan-design/hierarchy/state-messaging-system-center-configuration-manager.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/state-messaging-system-center-configuration-manager.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @choppystyx for the feedback. We unfortunately have a large backlog of work for the SDK type content. We're looking at ways to improve it in the future. I'll keep this issue open for now to track the gap, but I can't make any promises on when we might be able to mitigate.

If you or someone from the community determine the information, you can submit a change for this issue. For more information, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute).

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
