### ISSUE TITLE
Data Dedup for Site Servers

### ISSUE THREAD

**Issue by Yupiter2005** [MicrosoftDocs/SCCMdocs#2207]
Shouldn't we document/support running OS dedup on site servers (having Content Library on them) without having a DP installed?

I believe installing DP onto a site server doesn't make much of a difference for OS dedup.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34b2caf-beee-6525-8546-d9a7d919d4a0
* Version Independent ID: 285b669d-42d3-e8fb-d52b-589740e37f6c
* Content: [Support for Windows features - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/configs/support-for-windows-features-and-networks#bkmmk_datadedup)
* Content Source: [sccm/core/plan-design/configs/support-for-windows-features-and-networks.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/support-for-windows-features-and-networks.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks again for the feedback. We moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
