### ISSUE TITLE
More Info around SMS_WinPEPeerCacheConfig

### ISSUE THREAD

**Issue by Stroell** [MicrosoftDocs/SCCMdocs#2211]
Please provide more information how to configure SMS_WinPEPeerCacheConfig for a specific client setting.
I cannot find anything on the internet how the WMI Class can be used.
In my point of view, these settings should be configurable in the console directly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29b8c8d-60fa-4403-29a7-8e7c61b2f638
* Version Independent ID: c7610ca2-5607-d1fe-f629-9d0614a26569
* Content: [Client Peer Cache - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/hierarchy/client-peer-cache#limited-access-to-a-peer-cache-source)
* Content Source: [sccm/core/plan-design/hierarchy/client-peer-cache.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/client-peer-cache.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Stroell for the feedback. We unfortunately have a large backlog of work for the PowerShell & SDK content, but are looking at ways to improve it in the future.

Regarding your last point on being configurable in the console, please share [product feedback](https://docs.microsoft.com/configmgr/core/understand/find-help#product-feedback) on that.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
