### ISSUE TITLE
Multiple client log files undocumented

### ISSUE THREAD

**Issue by ChadSimmons** [MicrosoftDocs/SCCMdocs#2223]
There are many client side log files that exist but are not not even referenced in the documentation.  Can we please get these included?

- [x] DALOperationProvider.log #2218 
- [x] CcmSqlCE #2155 
- [x] CcmUsrCse
- [x] CCMVDIProvider
- [x] CertEnrollAgent
- [x] CIStateStore
- [x] CIStore
- [x] ClientServicing
- [x] CMBITSManager
- [x] ComplRelayAgent
- [x] InventoryProvider
- [ ] Oobmgmt
- [ ] PeerDPAgent
- [x] SmsClientMethodProvider
- [ ] Smssha
- [x] StateMessageProvider
- [ ] UpdateTrustedSites 
- [ ] UpdateTrustedSites
- [x] UserAffinityProvider

(admin edit, adding task list to track work in progress)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 972d8899-c8a4-28c5-fabe-5ab294bac22d
* Version Independent ID: 7f772e7a-836c-a18d-df8d-c3d115cb3d9f
* Content: [Log file reference - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/hierarchy/log-files#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/log-files.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/log-files.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ChadSimmons for the feedback. I need to get all feature teams to review this article and provide input on missing pieces.

**Comment by aczechowski** [comment]
I'm making a change to add info for most of the logs you noted. At least as best as I can determine.
I didn't include a few because I think they are deprecated/irrelevant:
- OobMgmt - AMT
- PeerDPAgent - branch DP
- Smssha - NAP
- UpdateTrustedSites - app catalog

This issue will auto close when my change merges. The changes will go live with the next daily publishing process, which at this point should be later today.
Thanks again for the feedback!
