### ISSUE TITLE
Windows 10 with UWF support

### ISSUE THREAD

**Issue by sccmfan** [MicrosoftDocs/SCCMdocs#2226]
It would be great to have proper UWF exclusions for Windows 10.
Current documentation is only for Windows Embedded and it takes quite some effort to generate proper exclusion list, especially for Windows 10 LTSC 2019 which seem to differ from previous versions :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06054b07-e62e-6444-54c1-2f9f95c6a0d2
* Version Independent ID: 71d76827-704c-3496-a2dc-cd821d734efd
* Content: [Planning client deployment to Windows Embedded devices - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/deploy/plan/planning-for-client-deployment-to-windows-embedded-devices)
* Content Source: [sccm/core/clients/deploy/plan/planning-for-client-deployment-to-windows-embedded-devices.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/plan/planning-for-client-deployment-to-windows-embedded-devices.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @sccmfan for the feedback

**Comment by aczechowski** [comment]
Thanks again for the feedback. We moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
