### ISSUE TITLE
Count & Substring

### ISSUE THREAD

**Issue by Garthmj** [MicrosoftDocs/SCCMdocs#2228]
Do both Count and Substring work in CM console? None of my test show that this works in CM console. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5ef23a9-ab26-8350-4a96-f6a8213b5bd4
* Version Independent ID: 8f795ead-9001-214c-56fd-7768994c90a9
* Content: [Extended WMI Query Language - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/develop/core/understand/extended-wmi-query-language?source=docs)
* Content Source: [sccm/develop/core/understand/extended-wmi-query-language.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/core/understand/extended-wmi-query-language.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by Garthmj** [comment]
BTW, I tested this again. The Substring ONLY works with the Where and Join sections of the query.

**Comment by aczechowski** [comment]
Thanks for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
