### ISSUE TITLE
Why ER gatway is a pre-requisite?

### ISSUE THREAD

**Issue by kprpg** [MicrosoftDocs/SCCMdocs#2230]
The tool only lists VNETs with an ER gateway. 
(a) Why is that so? 
(b) Is that a limitation of the tool?
(c) If b is true, is there another way to point to a VNET?
(d) Is there a plan to remove this limitation?

Thanks,
KPRPG

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8805a794-36df-d394-c109-6713f55b5875
* Version Independent ID: 36d2d111-a908-3727-8933-ed51cc7cc1a0
* Content: [Extend and Migrate on-premises site to Microsoft Azure - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/support/azure-migration-tool)
* Content Source: [sccm/core/support/azure-migration-tool.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/support/azure-migration-tool.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @kprpg for taking the time to provide feedback on Configuration Manager! I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
