### ISSUE TITLE
The examples are not formatted properly

### ISSUE THREAD

**Issue by ultimal** [MicrosoftDocs/SCCMdocs#2232]
The examples in the properties are not formatted properly making it very hard to read/use. Also there is no index of all the properties, like there is usually for powershell cmdlets so it is very hard to look for specific properties. The properties are also not separated by Bootstrap.ini and CustomSettings.ini properties. These were all things that original documentation had.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4452b34-bc38-4e06-a053-c216312dcfc7
* Version Independent ID: ab55107e-272d-1f8f-21dd-dba39a95077d
* Content: [Toolkit reference - Microsoft Deployment Toolkit](https://docs.microsoft.com/en-us/configmgr/mdt/toolkit-reference#properties-60)
* Content Source: [sccm/mdt/toolkit-reference.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdt/toolkit-reference.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
