### ISSUE TITLE
Always on Recovery feature can't recreate a new database with automatic seeding mode

### ISSUE THREAD

**Issue by mandyliu-CMSE** [MicrosoftDocs/SCCMdocs#2242]
the feature said Site recovery can recreate the database on a SQL Always On group. This process works with both manual and automatic seeding. But when I set Availability group to Automatic seeding mode  , the New Availability Group Database UI can't show in SCCM  . The UI only shows in manual seeding mode .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce365c35-765b-50f2-3793-aaa28f022758
* Version Independent ID: d1245006-b640-dba8-8c76-3988ad4b7050
* Content: [What's new in version 1906 - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/changes/whats-new-in-version-1906#feedback)
* Content Source: [sccm/core/plan-design/changes/whats-new-in-version-1906.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/changes/whats-new-in-version-1906.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
There was an internal thread on this same topic earlier this year. What you describe is the expected behavior, the setup/recovery wizard page only applies to manual seeding configuration. With auto seeding, there's no shared database backup, so that page of the wizard isn't shown. I'll add this note to our main article on SQL Always On. Thanks for the feedback.
