### ISSUE TITLE
Interrupted Countdown

### ISSUE THREAD

**Issue by jorlando82** [MicrosoftDocs/SCCMdocs#2295]
Can we get clarification on this page as to what happens when a restart countdown is interrupted by sleep/laptop lid shut. Lets say you are 2 hours into a 4 hour countdown and the user puts the laptop away (Sleep or hibernate) for the day. When they open the lid the following day what's the status of the countdown? Past deadline? New grace period? Picks up where it left off? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3f43b73-de34-a8b0-13c6-c647724161e0
* Version Independent ID: 39e43e5b-626b-b5b9-67de-f7f7a39950cd
* Content: [Device restart notifications - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/deploy/device-restart-notifications#feedback)
* Content Source: [sccm/core/clients/deploy/device-restart-notifications.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/device-restart-notifications.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @jorlando82 for the feedback. I'm making a change to the article to address this question. This issue will auto close when my change merges. It will then go live with the next daily publishing cycle (should be tomorrow morning Pacific at this point).

Basically, the countdown doesn't pause/interrupt. In your example (which I borrowed in the note), the device will restart when it wakes up, since it's past the deadline.
