### ISSUE TITLE
More information on Detectoids and Bundles

### ISSUE THREAD

**Issue by asjimene** [MicrosoftDocs/SCCMdocs#2296]
Im looking for a bit more in-depth information on how Detectoids are processed, specifically Detectoids specifying a rerequisite update. Does specifying a prerequisite update effect the order that updates are installed if both an update and it's prerequisite are deployed at the same time? In that same situation, would both updates show as applicable, or would the update with a prerequisite require another software update scan after the prerequisite is installed?

For bundles, are all updates in the bundle downloaded regardless of applicability? If updates have a prerequisite that is included in the same bundle, will all of the the updates in the bundle be downloaded/staged regardless of their applicability?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a342b0a1-6b74-2326-c582-577d26fd1f3d
* Version Independent ID: 9b26042b-811f-8324-2fa2-3f89f00f44f5
* Content: [Create updates - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/sum/tools/create-updates-with-updates-publisher#feedback)
* Content Source: [sccm/sum/tools/create-updates-with-updates-publisher.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/tools/create-updates-with-updates-publisher.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
Hey Andrew, 
Determining applicability and the downloading of bundles is all the function of the Windows Update Agent and slightly outside the scope of this doc. However, there are some pretty good docs in the Windows repositories on that agent. 

Start with this one: https://docs.microsoft.com/en-us/windows/deployment/update/how-windows-update-works 
Then move to the next few articles in the doc table of contents especially the log file one: https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-logs
Lastly start poking the WUA API docs: https://docs.microsoft.com/en-us/windows/win32/wua_sdk/searching--downloading--and-installing-updates

That being said, I can help you a bit since updates are kind of a little hobby of mine. =) DM me on Twitter if you need more info than this and need to talk specifics.

It's a bit simplistic explanation, but just assume single child bundle and single prereq for "UpdateB":
If a machine is missing "PrereqUpdateA" for "UpdateB", then when the client scans, "UpdateB" will not be applicable to the machine. "PrereqUpdateA" will be applicable and offered assuming the machine meets all the requirements for it. Once "PrereqUpdateA" is installed (note: sometimes a reboot is needed before an update is actually installed completely), on the next scan "UpdateB" will be applicable to the machine. 

For downloading the bundled files, we need to split the conversation into 2 different threads: 
1. The WSUS side (let's take CM out of the loop for this conversation)
2. The client side. 

Assume your update logic looks like this: 
- ParentUpdate1 is applicable to the client if **at least one** of the bundles is applicable. 
   - Bundle1 is applicable if the client is x86
       -  x86.msi is the file for Bundle1
   - Bundle2 is applicable if the client is x64
       -  x64.msi is the file for Bundle2
 
1. **WSUS side:** In WSUS, you approve ParentUpdate1 to All Computers with an ASAP deadline. Both x86.msi and x64.msi are downloaded into the WSUSContent directory so you have the full content for all parts of ParentUpdate1.
2. **Client side:** 
   - x86Client1 scans and ParentUpdate1 is applicable since Bundle1 is applicable (but not Bundle2 of course)
      - x86Client1 downloads only the content for the applicable bundle, so only x86.msi. 
   - The same logic is true for x64Client1, except it will get Bundle2 instead of Bundle1. 

In a verbose WindowsUpdate.log you can see the applicability pretty clearly for ParentUpdate1. What you will see is the update ID is either “IsInstallable” or “NotApplicable” next to it (Installed, of course, means it is installed). Note that you are looking for the latest “Final Detection state” for that update ID. 
 
Ex1: Final detection state for update 457030 (updateId = {BE64E778-4AB8-4B44-A24F-25ABC1C2BE0D}.102) is "NotApplicable" 
Ex2: Final detection state for update 457038 (updateId = {F278F751-8670-477E-8DBB-F5C4DEAF5EA6}.102) is "Installable"

You'll also see the applicability for the updateIDs of each bundle as well, so search for them in the verbose log too. If you don't see the bundles, that means the applicability is cached in the Windows Update Agent's data store, which is that .edb file that sits in C:\Windows\SoftwareDistribution\DataStore. Easiest way to clear it is to stop the Windows Update Agent, delete the client's SoftwareDistribution folder, then restart the agent. 

Installation order of updates is where it gets a little interesting. Typically, this is dependent on how the search and install was called. Remember that API doc I recommended?  That call batches updates into what amounts to collections of updates that fits the search criteria. Look for "Criteria =" in the WindowsUpdate.log to see examples of this (it's really clear if Defender is the one doing the search and install).  It could also be that you are only searching for a specific update to install: https://docs.microsoft.com/en-us/windows/win32/wua_sdk/searching--downloading--and-installing-specific-updates 
There is also a flag to require exclusive handling for an update. In SCUP you can see it when authoring updates (optional info page, impact option) Basically it gets installed by itself. I haven't played with that one in years so I forget if it just needs the install thread restarted, the WUA process, or an actual reboot to occur before installing another update.
