### ISSUE TITLE
Primary and secondary site codes

### ISSUE THREAD

**Issue by codaamok** [MicrosoftDocs/SCCMdocs#2298]
In a couple of places the `/ps` and `/sc` parmaeters are referenced. There's some confusion in the doc because while the doc explicitly suggests "primary site code" must be passed for both of these parameters, I can't help but think `/sc` should accept just the secondary site code, and not the primary site code.

Also, the descriptions for them don't make logical sense either. They're clear and well written, but for example under "Optional parameters" heading the description for `/ps` and `/sc` suggests to use them when cleaning a DP at a primary site. However reading about these parameters under "Required parameters" heading, it suggests the only use these parameters when cleaning a DP from a secondary site.

I would make a PR but I don't have a secondary site to test with unfortunately so can't confirm. 

Also, the brief example for how to use these parameters is a little confusing, e.g. `/sc &lt;primary site code&gt;`, should that be secondary site code? Again, I'm not sure, I could be wrong, I can't test.

So lines of the .md file I propose for review are: 97, 98, 113 and 114.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15d31569-af98-8c15-a224-f68b83827caa
* Version Independent ID: cd2099fe-d6c5-0983-948c-45617a6c0e11
* Content: [Content library cleanup tool - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/hierarchy/content-library-cleanup-tool#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/content-library-cleanup-tool.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/content-library-cleanup-tool.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @codaamok, it's technically accurate, just subtle. The /ps parameter takes the FQDN of the primary site server. The /sc parameter takes the site code. You *can* specify these params when running it for a DP at a primary site, but it's not necessary. That's why they show in the optional list.

When you run the tool for a DP at a secondary site, the tool needs to connect to the parent primary site to get necessary details. So in that scenario, these params are required.

I'm just kind of rephrasing/summarizing what's already in the article. So I'm going to close this issue. If you have any suggestions on how to further/better clarify, open a new issue on the [current doc in memdocs](https://docs.microsoft.com/mem/configmgr/core/plan-design/hierarchy/content-library-cleanup-tool), or open a PR over there. 😉
