### ISSUE TITLE
I believe MessageState on SMS_DistributionDPStatus should be 1, 2 and 4

### ISSUE THREAD

**Issue by MartinKorsgaard** [MicrosoftDocs/SCCMdocs#2299]
According to the docs MessageState on SMS_DistributionDPStatus is 

1 | Success
2 | InProgress
3 | Error

but in fact it should be

1 | Success
2 | InProgress
4 | Error

Correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a487579-92fb-3014-f0f9-68c5a5eca0ce
* Version Independent ID: 00f8a666-dc84-47f6-9e5b-fe18827f6878
* Content: [SMS_DistributionDPStatus Class - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/develop/reference/core/servers/configure/sms_distributiondpstatus-server-wmi-class)
* Content Source: [sccm/develop/reference/core/servers/configure/sms_distributiondpstatus-server-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/core/servers/configure/sms_distributiondpstatus-server-wmi-class.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
