### ISSUE TITLE
can u pepare power bi report us sap b1 

### ISSUE THREAD

**Issue by bhavaniarun** [MicrosoftDocs/SCCMdocs#2303]

**Comment by mestew** [comment]
Hi @bhavaniarun could you tell me which ConfigMgr article and which Power BI report you are referring to?

**Comment by bhavaniarun** [comment]
Hi meghan

I was telling about how can u support in getting power BI report done through sap b1 using sql data base on premise

**Comment by mestew** [comment]
Thanks for the clarification @bhavaniarun

Using Power BI with SAP B1 wouldn't be something that the Configuration Manager team would typically test or document. Best bet is to ask the Power BI team rather than CM. The link below should get you a step closer to finding out the answer to what you're asking:
https://docs.microsoft.com/power-bi/desktop-sap-bw-connector

#please-close
