### ISSUE TITLE
 Configuration Manager Client SDK WIM class  doesn't have request method

### ISSUE THREAD

**Issue by taoyongd** [MicrosoftDocs/SCCMdocs#2330]
I checked the API  in https://docs.microsoft.com/en-us/configmgr/develop/reference/core/clients/sdk/install-method-in-class-ccm_application which shows the install methods, but I didn't find the request methods when a deploy is created target user collection with approval needed. Then in the software center, when we click the application, a request button will show. What's the corresponding API when the end-user click request?

**Comment by aczechowski** [comment]
Thanks for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
