### ISSUE TITLE
SCCM with MBAM pin and intune workloads. 

### ISSUE THREAD

**Issue by FristVoid** [MicrosoftDocs/SCCMdocs#2338]
Dear Team, it is great to see the progression of the SCCM and MBAM integration.

We have piloted Co-Management and came across an issue.  If we move the workloads in relation to Antivirus this also moves MBAM.   This wouldn't be an issue except that we are required by various laws to make all efforts to secure our systems according to the standards set out.  Here the standard is set by Microsoft for systems that are lost that contain sensitive information:  https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-countermeasures  

This in turn means we can't apply Tamper protection.  We are aware you can use tenant attach for this but then you can't apply antivirus policies.   

So with co-management enabled is it possible to disable the MBAM portion of the workload or in intune provide a way to enter the PIN in user-mode like MBAM currently does?   Otherwise we can't see a way to meet these requirements short of using a 3rd party or writing our own MBAM service.  e.g. here:  https://oliverkieselbach.com/2019/08/02/how-to-enable-pre-boot-bitlocker-startup-pin-on-windows-with-intune/

Thank you again for your efforts and I hope you can help us find an solution for this scenario.

**Comment by aczechowski** [comment]
Thanks @FristVoid for taking the time to provide feedback on Configuration Manager! This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.

The Endpoint Protection workload includes Windows Encryption which includes BitLocker management. For more information, see [Co-management workloads - Endpoint Protection](https://docs.microsoft.com/mem/configmgr/comanage/workloads#endpoint-protection).

Also, this repository is not actively used anymore. In the future, please share doc feedback in the MEMDocs repo. For more information, see [How to use the docs](https://docs.microsoft.com/mem/use-docs#about-feedback).
