### ISSUE TITLE
Prerequisite Section could be more clear 

### ISSUE THREAD

**Issue by AnoopCNair** [MicrosoftDocs/SCCMdocs#421]
Co Management should work and it's supported to have Intune Standalone or MIXED mode. 

#MVPHackaDoc

**Comment by aczechowski** [comment]
Hi @AnoopCNair 
Officially, co-management is only supported with Intune standalone. This is specifically mentioned as a note https://docs.microsoft.com/en-us/sccm/core/clients/manage/co-management-overview#general-prerequisites
Let us know if there's something else you are suggesting, otherwise I'll close this issue.
@mestew for visibility

**Comment by AnoopCNair** [comment]
Hey Aaron ! - I thought Dev said (during yesterday’s session) co-mgmt is supported with two modes.

Intune stand-alone and Mixed ! 

Can you please confirm ?

KR
Anoop

**Comment by aczechowski** [comment]
I confirmed with PMs, and have a change in to reword the Note in the prereqs section:

If you have a hybrid MDM environment (Intune integrated with Configuration Manager), you cannot enable co-management. However, you can start migrating users to Intune standalone and then enable their associated Windows 10 devices for co-management. For more information about migrating to Intune standalone, see Start migrating from hybrid MDM to Intune standalone.

**Comment by AnoopCNair** [comment]
That makes sense !

Thank you!
