### ISSUE TITLE
The article needs a complete rewrite to separate scenarios

### ISSUE THREAD

**Issue by sccmentor** [MicrosoftDocs/SCCMdocs#424]
SCCMdocs/sccm/core/servers/deploy/configure/database-replicas-for-management-points.md

See my comment in the article.  I think it would be better to create separate posts that refer to MP with local replica DB and another with MP and remote replica DB to avoid any confusion.

#MVPHackaDoc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e05b125-c8e8-0eab-5b2b-2bc60fe33654
* Version Independent ID: fcf9f58f-1ab5-9132-7de8-539a32b57862
* Content: [Management point database replicas - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/database-replicas-for-management-points)
* Content Source: [sccm/core/servers/deploy/configure/database-replicas-for-management-points.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/database-replicas-for-management-points.md)
* Service: **unspecified**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @sccmentor 
I'm checking on this. Stay tuned
@mestew for visibility

**Comment by aczechowski** [comment]
Filed doc bug 510600 to track

**Comment by aczechowski** [comment]
Preserved relevant comments from the previous feedback system:


Paul_Winstanley Dec 6, 2016
I found this post a struggle to work through and I think it would be better to create separate posts that refer to MP with local replica DB and another with MP and remote replica DB to avoid any confusion.


Tom_Gibson Feb 25, 2017
I have documented this for my own purposes since the 2012 days and I agree it is cumbersome. I think the thing that makes it difficult is the switching back and forth between servers - also the above documentation tries to address scenarios when you have an MP on one server and the DB on a different server - who does this? That makes this even more complicated. If improvements can be made I would focus on more automation - creating the subscription should be the same for everyone - just need to change the server name and database name. Then setup some kind of automation to create the certificates without having to switch to different servers.
Finally, I would love to see more direction on WHEN you should have an MP replica. Is there a performance metric that can be run on the DB that would say over this threshold you need to offload your MP traffic?  Having MP replication, especially now with updates coming 3 times a year, means doing these steps 3 times a year - WHAT A PAIN. Only those that really need it should do it and more guidance for that would be great. At this point when I have > 50,000 clients I want my primary and my database servers dedicated so I offload everything to other servers. But maybe my DB server is powerful enough where that is overkill. I just don't know.
the one advantage so far with MP replicas is I have a different server running SQL where I can do a testdbupgrade - oh that is now unnecessary in 1610 and later - so advantage gone.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
