### ISSUE TITLE
Please clarify which Microsoft Support department to speak to...

### ISSUE THREAD

**Issue by dstreefkerk** [MicrosoftDocs/SCCMdocs#493]
It'd be great if you guys could explicitly state which Support option we need to be choosing in order to request our license keys. Is it Technical Support? Is it a Subscription?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3b9a7fa-9585-a2fb-590e-0b74e128035d
* Version Independent ID: 9aae8e97-de68-c274-b4c6-cd925568c75b
* Content: [Product and Licensing FAQ - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/understand/product-and-licensing-faq)
* Content Source: [sccm/core/understand/product-and-licensing-faq.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/product-and-licensing-faq.md)
* Service: **unspecified**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
@dstreefkerk thanks for filing this. I started an email thread with some folks based on the Twitter responses to see if there's something we can do to help connect the dots. Stay tuned.

**Comment by JBFulc** [comment]
I am in the same situation. No one really knows who is supposed to deal with this when talking to support on the phone.
I've been passed on to 8/9 different places so far and almost got sent back to the number I originally dialed. My current agent, Pamela, seems determined to sort this out for me so here's to hoping.

**Comment by JBFulc** [comment]
@aczechowski @dstreefkerk Any news on this. No one I have spoken to both at microsoft or our CSP have a clue.

**Comment by aczechowski** [comment]
Thanks @JBFulc for checking back, and sorry for the trouble with this. When you talk with Microsoft Support, ask them to reference the internal article ID 4033838.

**Comment by JBFulc** [comment]
> Thanks @JBFulc for checking back, and sorry for the trouble with this. When you talk with Microsoft Support, ask them to reference the internal article ID 4033838.

To this day no one has been able to help me with activation. quoting that ID to my CSP and others has not helped me for whatever reason. The activation date is coming up soon and I dont really know what to do.

**Comment by aczechowski** [comment]
Hm, I got pinged by someone in support yesterday as well, I wonder if for the same? There's an issue with the KB, I'm trying to help track down some additional info. I'm sorry for the challenges.

**Comment by JBFulc** [comment]
> Hm, I got pinged by someone in support yesterday as well, I wonder if for the same? There's an issue with the KB, I'm trying to help track down some additional info. I'm sorry for the challenges.

Thanks, do appreciate it.

**Comment by JBFulc** [comment]
> Hm, I got pinged by someone in support yesterday as well, I wonder if for the same? There's an issue with the KB, I'm trying to help track down some additional info. I'm sorry for the challenges.

Hi @aczechowski  any update, I haven't got any further an have only a week left on the evaluation!

Thanks.

**Comment by aczechowski** [comment]
Sorry @JBFulc, I'm trying to track down someone who can help. Your best avenue for urgent help is Microsoft Support or your Microsoft account team.

**Comment by aczechowski** [comment]
@JBFulc call Microsoft support, tell them to open internal KB 4033838. Step 5 of that internal KB answers the question: How can customers who purchase EMS/M365 via direct and CSP licensing model obtain the key for System Center Configuration Manager? It should be as easy as that. But you need to talk to Microsoft Support.

**Comment by JBFulc** [comment]
> @JBFulc call Microsoft support, tell them to open internal KB 4033838. Step 5 of that internal KB answers the question: How can customers who purchase EMS/M365 via direct and CSP licensing model obtain the key for System Center Configuration Manager? It should be as easy as that. But you need to talk to Microsoft Support.

Thank you. I will give it a go.

**Comment by aczechowski** [comment]
Closing this issue as it was fixed back in March

**Comment by mdcowdrey** [comment]
I hate to bring an issue back from the dead, but I've spent two weeks on and off with Office 365 support, spoke with four different Office 365 Ambassadors, Business Support, and VLSC, referenced 4033838 dozens of times--and no one has any idea how to get me a key for SCCM purchased via Enterprise Mobility + Security E3. 

One of the pertinent issues is at least one of the ambassadors was unable to open the internal article 4033838 when I referenced, but I have no way to verify that.

I'm really at my wits ends with this, any help from others would be amazing!

**Comment by aczechowski** [comment]
Hi @mdcowdrey, sorry for the troubles. Here's the specific internal URL that you can share with them. I don't know the permissions on these articles, so if they are a Microsoft partner they may not have access.
https://internal.support.services.microsoft.com/en-us/help/4033838
I just opened it, so know it's still there. Step 5 is what they need.

**Comment by mdcowdrey** [comment]
@aczechowski Thanks for the quick response!

It's funny you should send that link, as an Office 365 Support Engineer sent the exact same link to me to see if I could open it, as she could not. (I certainly cannot.)

What do you think? Should I keep asking around? I'd really like my CSP to be able to open the article to avoid all this.

**Comment by aczechowski** [comment]
Tell them to email me internally. I'm the only one in the GAL with this name :)
I checked with someone in CSS, vendors can access internal KBs, as long as they're signed in.

**Comment by Spork-Schivago** [comment]
@aczechowski ,

anyway you could help us get that SCCM product key sir?   We have tried referencing the internal article ID, the URL for that article ID, we have sent emails, we have called various numbers, we just get the run around.   It isn't clear what Microsoft number we're supposed to call, so we have called Office 365 Support, then they told us to call Microsoft Support, at 1-800-765-7768, who told us to call Office 365 Support, who referenced us back to Microsoft Support.   Very frustrating.

**Comment by Spork-Schivago** [comment]
For what it's worth, after three separate attempts, each lasting for a couple days, I was finally able to obtain the key myself.   The number I had originally was always the correct number, which is the Microsoft 365 Technical Support Phone Number: 1-800-865-9408

Each attempt, I would start with calling my Account Representative who provides me with our CSP licenses.   They would provide us with the Microsoft number to call after a few days.   They would have to research if we were entitled to a license and product key, and then who to contact for that product key.

At that point, I'd call the Microsoft number and then I'd get bounced back and forth for a couple days.   They'd send me to the Microsoft team that deals with VLMs, then back to the Microsoft 365 Technical Support.   Occasionally, I'd get sent to the Office 365 Technical Support department.

Microsoft 365 Technical Support logged into my PC to see what article I was talking about, because they had no idea what SCCM was.   They said they could not provide a product key, nor could they access any internal articles.   However, before we disconnected, I pasted the following URL into the chat window:

https://internal.support.services.microsoft.com/en-us/help/4033838

They called back maybe 15 minutes later saying they reached out to other departments and obtained the product key for me!   I am not certain if they actually did this or just discovered they had access to the internal support articles. 

I only share my story hoping that this information can be used to try and figure out where the problem lies on Microsoft's end.   The absolute hardest part is getting the Microsoft employee to actually try and view the internal article.   None of them think they have access to it.

Thanks!!!!

**Comment by mdcowdrey** [comment]
@Spork-Schivago 

I can't reiterate Spork's comments enough. Most departments can read the article, but searching for the document number doesn't return any results: they need to be sent the link. I finally was able to speak with a technical lead on both the SCCM and Office 365 side, both of whom were able to help me move forward after I sent them the article link directly. 

Helpful note, don't bother trying to explain anything until you've verified they are reading the article--you'll waste weeks. 

@aczechowski, I appreciate the offer to be a resource but no one seemed to be interested in emailing you directly. 

I'd mention that SQL Server 2017 has an entitlement usage from SCCM installation, but I think I've had enough for the next few months.
