### ISSUE TITLE
How do you edit a script/versioning

### ISSUE THREAD

**Issue by rbreneman** [MicrosoftDocs/SCCMdocs#498]
Would like to see information regarding editing an existing script. I see the concept of versioning when looking at an existing script but I'm unable to figure out how to edit. I assume there would be another approval needed for edits?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c7d1db7-6812-ff3c-9aac-0f55800ed665
* Version Independent ID: a4499cf7-ed5a-710c-66e0-005563b9c015
* Content: [Create and run scripts - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/create-deploy-scripts)
* Content Source: [sccm/apps/deploy-use/create-deploy-scripts.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/create-deploy-scripts.md)
* Service: **unspecified**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Checking with feature team

**Comment by kensel** [comment]
Is there any update on this?  Currently I have to delete the script and re create it every time I have an update to the script or create a new script with the version in the name.  Deleting the script cause the Script Status under the Monitoring tab to be deleted also and loose the run history of the script.

**Comment by aczechowski** [comment]
Thanks for bumping this. That functionality is currently on the product backlog. 

I want to make sure your feedback gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback]( https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. 

I'm closing this issue as there's nothing actionable for docs at this time.
