### ISSUE TITLE
More details about actual cleanup procedure

### ISSUE THREAD

**Issue by XabiBeltza** [MicrosoftDocs/SCCMdocs#500]
What checks does this process do? Only superseded update? It doesnt clen expired updates, computers not contacting server, unneeded files, unused revisions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38bacc7a-d602-e825-bff3-5d9232f03f72
* Version Independent ID: 7de8c181-3252-de71-bdfe-70b68dd966c5
* Content: [Software updates maintenance - Configuration Manager](https://docs.microsoft.com/en-in/sccm/sum/deploy-use/software-updates-maintenance)
* Content Source: [sccm/sum/deploy-use/software-updates-maintenance.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/software-updates-maintenance.md)
* Service: **unspecified**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by XabiBeltza** [comment]
Also, what logs should we check to assert that the process is working as intended?

**Comment by Yupiter2005** [comment]
Adding my 5 cents: yes, we need some more clarity on the process, especially since we now do decline the expired updates in WSUS DB

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
