### ISSUE TITLE
Inbox folders

### ISSUE THREAD

**Issue by jpcast88** [MicrosoftDocs/SCCMdocs#532]
Is there any updated info on inbox folders that are used by different site components? The most recent reference I could find is @ https://support.microsoft.com/en-us/help/871161/a-description-of-inbox-folders-and-how-they-are-used-in-systems-manage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a98cdb34-bf46-14c7-af61-75f7939457df
* Version Independent ID: dd39871a-92f9-5e20-2930-1eb26c668d31
* Content: [Site components - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/site-components)
* Content Source: [sccm/core/servers/deploy/configure/site-components.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/site-components.md)
* Service: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jocasti for the suggestion. That KB article is one existing resource, as well as this older article from TechNet on [Inbox Folders in Configuration Manager 2007](https://technet.microsoft.com/library/bb892790.aspx). We had some recent internal discussion on this topic, and have an interest in revising an updating, but it will take some time.

**Comment by aczechowski** [comment]
Reference
- [Feedback Hub submission](https://aka.ms/feedbackhuburi/?ContextId=927&feedbackId=6e8dfe74-780c-473b-a664-675f10cc35ba&form=1&src=1)
- Internal doc bug 511611

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
