### ISSUE TITLE
1803 clients seem to work just fine with ConfigMgr 1710

### ISSUE THREAD

**Issue by christopherggg** [MicrosoftDocs/SCCMdocs#535]
Can you elaborate on what it means for a version of Windows 10 to be "not supported as a client?"

We are on ConfigMgr 1710 and Windows 10 1803 clients seem to work just fine (OSD, app deployment, inventory collection, remote control, etc), despite the table showing they are not supported on ConfigMgr 1706 and 1710.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc732ec0-eb14-8da2-7688-dd74a72cdae5
* Version Independent ID: a93682ff-2984-38e0-5a0d-6f77c1c9e5db
* Content: [Support for Windows 10 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/support-for-windows-10)
* Content Source: [sccm/core/plan-design/configs/support-for-windows-10.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/support-for-windows-10.md)
* Service: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
As I always say with this topic, the supported configuration relates to what we have tested and verified as functional. If it’s not in the matrix, that means we haven’t tested it. We have to document things and that comes across as very binary: supported or not supported. There’s likely a lot of product functionality that technically works, but we haven’t tested it. So there’s some risk for customers. Thus we don’t officially support it. In this particular case, there were some bugs that we fixed in the SCCM 1802 final release for OS deployment and software updates with Windows 10 version 1803.

We have no plans to change the support matrix so I'm closing this issue.
