### ISSUE TITLE
Rerun scripts and offline devices

### ISSUE THREAD

**Issue by SoldierPeter76** [MicrosoftDocs/SCCMdocs#542]
If i run a script against a pretty big collection where (at that time) several devices are online,
what is the best approach to rerun the script on only those machines ?
I do not want to rerun it on the successfull clients once more.
As the script will only be valid for 1 hour: Is there any way to increase that timeframe ?
Best regards,
/Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c7d1db7-6812-ff3c-9aac-0f55800ed665
* Version Independent ID: a4499cf7-ed5a-710c-66e0-005563b9c015
* Content: [Create and run scripts - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/create-deploy-scripts)
* Content Source: [sccm/apps/deploy-use/create-deploy-scripts.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/create-deploy-scripts.md)
* Service: **unspecified**
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @SoldierPeter76, thanks for taking the time to provide feedback on Configuration Manager! This feedback is actually feature ideas that scripts currently don't support, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback]( https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress.

I'm closing this issue as I don't see anything immediately actionable for docs at this time.
