### ISSUE TITLE
Exit Codes

### ISSUE THREAD

**Issue by ZacBrowning** [MicrosoftDocs/SCCMdocs#564]
I'm not very experienced with Powershell scripts, so it would be AMAZING if there was a feature that I could set an exit code in the Scripts menu and decide whether that should be a success or a failure. I have a script that a coworker put together that checks if the Intel Virtualization and VtdFeatures are enabled, and if not it enables them. But since the script isn't written to account for non-zero exit codes, it will report back a failure if it already has those enabled. If I could put in "-2147467259" Exit code means "Success - already enabled" then that would make my job a whole lot easier.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c7d1db7-6812-ff3c-9aac-0f55800ed665
* Version Independent ID: a4499cf7-ed5a-710c-66e0-005563b9c015
* Content: [Create and run scripts - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/create-deploy-scripts)
* Content Source: [sccm/apps/deploy-use/create-deploy-scripts.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/create-deploy-scripts.md)
* Service: **unspecified**
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ZacBrowning for taking the time to provide feedback on Configuration Manager! This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback]( https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
