### ISSUE TITLE
Less privileged account

### ISSUE THREAD

**Issue by dotraphael** [MicrosoftDocs/SCCMdocs#567]
security is always a concern so sccm should give more information what rights are required, so customers can rely on documentation to secure by default sccm.

the https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/accounts should include information on how to secure these accounts by default. Adding information of what may/may not be supported:
1- removing the account from the domain users
2- adding some privileges (like using deny log on locally, deny log on as a service, deny log on via remote session, etc). 

also, these information should be added on where the privileged should be added/not added. ie client, DP, MP, etc.

also, accounts that are "required" by SCCM/TS (like domain join, reporting execution account, sql service account, etc.) should also be listed and all rights be listed.

(5/30 Admin edit: add GitHub footer from target page for linking)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22f80cf3-6f36-cb44-d0e5-d186164d6281
* Version Independent ID: ada8a281-7d9f-e82e-e4e8-056b93e8b36d
* Content: [Accounts used - Configuraton Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/accounts)
* Content Source: [sccm/core/plan-design/hierarchy/accounts.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/accounts.md)
* Service: **unspecified**
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the suggestion @dotraphael. In the future, you can file feedback directly from a target article which automatically links it with the issue. :)

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.

p.s. I am going to add some info as suggested in #405
