### ISSUE TITLE
More detail on third-party update configuration

### ISSUE THREAD

**Issue by jpoling1** [MicrosoftDocs/SCCMdocs#578]
Can detail as to why the SUP requires HTTPS communication to be enabled with WSUS be added to the doc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a8e07fe-e439-3807-ce09-06e9d942c958
* Version Independent ID: d9d9902c-ed76-6e07-1228-9beb61c979ad
* Content: [Technical Preview 1806 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/get-started/capabilities-in-technical-preview-1806)
* Content Source: [sccm/core/get-started/capabilities-in-technical-preview-1806.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/capabilities-in-technical-preview-1806.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jpoling1, I have a couple of conversations already in the works on this. Hope to have further clarity soon.

**Comment by aczechowski** [comment]
The SUP requires HTTPS because it's a requirement for the WSUS APIs that we're using to handle the signing certificates. Based on feedback from this TP, we have some potential modifications that we're working on (various configurations might change those fundamental requirements). The good news is that this doesn't mean you have to HTTPS-enable clients.

The following two articles are good resources for enabling HTTPS on WSUS:
- https://docs.microsoft.com/windows-server/administration/windows-server-update-services/deploy/2-configure-wsus#bkmk_2.5.ConfigSSL 
- https://blogs.technet.microsoft.com/sus/2011/05/09/how-to-create-an-internet-facing-wsus-server-that-uses-different-internal-and-external-names/

**Comment by aczechowski** [comment]
I just checked in a tip similar to my comment above. It should publish live tomorrow.
