### ISSUE TITLE
Custom Inventory classes

### ISSUE THREAD

**Issue by jpcast88** [MicrosoftDocs/SCCMdocs#583]
From the first Note above, "If you've manually changed the Configuration.mof file to add custom inventory classes, these changes will be overwritten when you update to version 1602." 

Does this apply to just an upgrade to 1602? Or do these custom classes get overwritten after each upgrade  (1702, 1710, 1802 etc.,)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54dd8166-9fb1-3027-ad24-6a14c2dd5f3f
* Version Independent ID: 02c01bf8-020c-b29a-ab8f-1541c83743b5
* Content: [Extend hardware inventory - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/inventory/extend-hardware-inventory)
* Content Source: [sccm/core/clients/manage/inventory/extend-hardware-inventory.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/inventory/extend-hardware-inventory.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jocasti for calling this out. At the very least I'm trying to clean up references to old builds that are no longer supported. In this case it obviously could have a functional impact as well. I'm checking with engineering.

**Comment by felymich** [comment]
Any updates on the question of jocasti as apparently with my upgrade 1802 the Custom Inventory Classes previously used are gone !!!

**Comment by sydbankguy** [comment]
To extend hardware inventory do we need to add the relevant WMI class to each SCCM client and then add it to the client settings?

If yes, how do you do it?

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.

(I think this is now obsolete too, as 1802 is no longer supported)
