### ISSUE TITLE
Help Guide Us out of GUID Hell

### ISSUE THREAD

**Issue by bryandam** [MicrosoftDocs/SCCMdocs#607]
Honestly, documentation might not be the best/right fix for this but I'm going to assume it's more nimble for the task.  I think nearly every admin/architect at a large organization faces this issue.  We can point our admins/techs to this doc to get an idea of what log does what.  The moment they open the log itself though it's game over ... a wall of text that they don't understand and don't want to understand.

One step in the right direction might be to explain what GUIDs the log file contains, what that GUID actually refers to, and how it relates to other logs files with that GUID.  Really, fixing that in the actual product is the better solution but I suspect that's a harder hill to climb.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 972d8899-c8a4-28c5-fabe-5ab294bac22d
* Version Independent ID: 7f772e7a-836c-a18d-df8d-c3d115cb3d9f
* Content: [Log files for troubleshooting - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/log-files)
* Content Source: [sccm/core/plan-design/hierarchy/log-files.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/log-files.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @bryandam for the comment. I know that discussion has come up internally with engineers, some way to make it easier for customers to interpret and follow the flow of the logs. Adding some pointers in the documentation may be an easier approach to tackling that challenge.

**Comment by ChadSimmons** [comment]
Another option would be to build the functionality into the Support Center Log Viewer or OneTrace.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.

p.s. ICYMI, check out the [app deployment troubleshooting article](https://docs.microsoft.com/en-us/mem/configmgr/apps/understand/app-deployment-technical-reference)
