### ISSUE TITLE
Telemetry Level

### ISSUE THREAD

**Issue by FredEricSDE** [MicrosoftDocs/SCCMdocs#620]
"The data in the .cab file is based on the level of diagnostic usage data your site is configured to collect." - This is either incorrect, or not working properly. No matter what setting is configured in ConfigMgr (Basic, Enhanced, Full), the data in the csv (serviceconnectiontool.exe -export -dest X:\Folder\UsageData.csv) is always the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a116b8a6-3c73-0b7d-56f3-c83b1d901565
* Version Independent ID: bd78266e-abaa-1515-c02f-a5b230d94955
* Content: [Service Connection Tool - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/use-the-service-connection-tool)
* Content Source: [sccm/core/servers/manage/use-the-service-connection-tool.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/use-the-service-connection-tool.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @FredEricSDE for filing this. I'm discussing with the engineering team. Could you please also file this as [product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) to track as a potential product bug?

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.

If this is still an issue, file a frown in the console, or open a support case.
