### ISSUE TITLE
Missing documentation about the options when editing a package

### ISSUE THREAD

**Issue by XabiBeltza** [MicrosoftDocs/SCCMdocs#621]
There are many setting missings in the docs, like the Data Access and Distibution settings tabs, some option in the Data Source tab, etc...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e162dd7-b731-31b4-924a-a8546fcdbdb9
* Version Independent ID: f034c24d-000f-da01-70fd-0f84bad9ac26
* Content: [Packages and programs - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/packages-and-programs)
* Content Source: [sccm/apps/deploy-use/packages-and-programs.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/packages-and-programs.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the feedback @XabiBeltza. Aside from just missing descriptions of the widgets themselves, what information about the settings on those pages are you looking for? Can you expand a bit upon what you're after?

**Comment by XabiBeltza** [comment]
- Assignment schedule options. Specially the logon, logoff options which don't seem to work since 2007
- Rerun behaviour. Does it take into account redistributing or modifying a package/program?
- Troubleshooting: Which logs are useful to determine program deploiyment behaviour

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
