### ISSUE TITLE
OEM Scripts

### ISSUE THREAD

**Issue by RPanick** [MicrosoftDocs/SCCMdocs#644]
I realize there are multiple OEMs, and the links may not stay valid.  But it would be very useful to list links to these scripts on at least the major vendors supporting this.  BTW, in my experience unless the OEM script is very well written to accommodate all the different models, doing it yourself could be quite troublesome.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8eaf0aab-4d02-82dd-007f-8457e648984d
* Version Independent ID: 4ea5614c-5e4d-537d-4b98-5ddead504359
* Content: [Task sequence steps to manage BIOS to UEFI conversion - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/deploy-use/task-sequence-steps-to-manage-bios-to-uefi-conversion)
* Content Source: [sccm/osd/deploy-use/task-sequence-steps-to-manage-bios-to-uefi-conversion.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/task-sequence-steps-to-manage-bios-to-uefi-conversion.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @RPanick for the feedback. As you mentioned, it's very difficult to curate and maintain such a list, which is why there are very few (if any) references to third-party products or services in any of the official product documentation. There is some potential work in the product backlog that might help with this in the future. But for now we unfortunately aren't able to support this request. So I'm closing this issue.

**Comment by RPanick** [comment]
Thanks Aaron, that’s what I sort of expected.  Its unfortunately also the most challenging part of the conversion.


Bob Panick
734-925-1523
