### ISSUE TITLE
Import-CMComputerInformation cmdlet can also be used to import new computer

### ISSUE THREAD

**Issue by Ghostmokey582** [MicrosoftDocs/SCCMdocs#663]
Import-CMComputerInformation cmdlet can also be used to import new computer. 
The cmdlet is a lot easier to use and is already documented at 
https://docs.microsoft.com/en-us/previous-versions/system-center/powershell/system-center-2012-r2/jj821991(v=sc.20)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9341692e-b9b7-4d2d-9a9c-ab65fb708f19
* Version Independent ID: ddc3e3c1-3c4d-da4a-1ff5-8f8c2d7c3a99
* Content: [Import a New Computer - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/osd/how-to-import-a-new-computer-into-configuration-manager)
* Content Source: [sccm/develop/osd/how-to-import-a-new-computer-into-configuration-manager.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/osd/how-to-import-a-new-computer-into-configuration-manager.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Ghostmokey582 for the feedback. In general I think most of the conceptual docs haven't been updated to reference the PowerShell content. But obviously something we should be doing. Some of the SCCM PowerShell cmdlets are on docs for current branch instead of the legacy Technet content. For example, see [Import-CMComputerInformation](https://docs.microsoft.com/powershell/module/configurationmanager/import-cmcomputerinformation?view=sccm-ps) for this cmdlet.

**Comment by aczechowski** [comment]
I just made a change for this, it will publish soon.
