### ISSUE TITLE
Polling interval for Macintosh Clients

### ISSUE THREAD

**Issue by eugenevalley** [MicrosoftDocs/SCCMdocs#671]
It should be noted that, in order to set the Client Policy Refresh Interval for Macintosh clients, we should use the "Polling interval for modern devices (minutes)" setting in the Enrollment section of Client Settings. The documentation here only mentions that this setting applies to Windows 10 devices managed via on-prem MDM.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f74f4a-560f-2510-1ae8-fd3976a2197e
* Version Independent ID: 0851f834-e9a1-d0a6-ee60-934bcd3a79fe
* Content: [Client settings - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/deploy/about-client-settings#polling-interval-for-modern-devices-minutes)
* Content Source: [sccm/core/clients/deploy/about-client-settings.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/about-client-settings.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @eugenevalley for the feedback.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
