### ISSUE TITLE
Software Center - Trooubleshooting

### ISSUE THREAD

**Issue by RottenRonnie** [MicrosoftDocs/SCCMdocs#674]
I would like to see an expanded section on Software Center for troubleshooting. For example, a reference to logging:
Logging: 
C:\Windows\CCM\Logs\AppEnforce.log

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54548019-4f0e-183b-a3d7-a2dd089e3119
* Version Independent ID: 3299edc2-d0a3-403f-1fab-8aba7a348c56
* Content: [Use Software Center to deploy Windows over the network - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/deploy-use/use-software-center-to-deploy-windows-over-the-network)
* Content Source: [sccm/osd/deploy-use/use-software-center-to-deploy-windows-over-the-network.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/use-software-center-to-deploy-windows-over-the-network.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
