### ISSUE TITLE
Is the content library tool capable of cleaning up, if the content library is spanned across multiple drives.

### ISSUE THREAD

**Issue by nmn25** [MicrosoftDocs/SCCMdocs#678]
[Enter feedback here]
SCCM Version 1710.
We get this error "System.IO.DirectoryNotFoundException: Could not find a part of the path ..." and it looks for the FileLib folder but is unable to find it. 
This is understandable as and the path specified has PkgLib and DataLib and the FileLib is actually on a different drive. Does the cleanup tool work in this scenario?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15d31569-af98-8c15-a224-f68b83827caa
* Version Independent ID: cd2099fe-d6c5-0983-948c-45617a6c0e11
* Content: [The content library cleanup tool - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/content-library-cleanup-tool)
* Content Source: [sccm/core/plan-design/hierarchy/content-library-cleanup-tool.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/content-library-cleanup-tool.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @nmn25 for sharing this question, and sorry to hear you're having problems. 

This article will update very soon with more information pulled from https://cloudblogs.microsoft.com/enterprisemobility/2013/10/29/understanding-the-configuration-manager-content-library/. Check that out and let me know if it helps answer your question. 

Otherwise, I want to make sure your question gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

**Comment by aczechowski** [comment]
I'm closing this issue, given the updates pending for 1806. If there's anything actionable to change in the docs when you resolve your problem, please reopen this issue or file another.
