### ISSUE TITLE
Feedback on additonal items

### ISSUE THREAD

**Issue by goatmale** [MicrosoftDocs/SCCMdocs#696]
Another good example of when It may be a good use of a configuration baseline would be registry keys required to enable CredSSP, Spectre and Meltdown remediation, as installing the associated Windows updates alone does not solve the problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4858756-0329-76a0-1703-12f6fb0c3ce5
* Version Independent ID: 13882e7f-9771-5416-962c-c79d94fb7faa
* Content: [Common tasks for configuration baselines  - Configuration Manager](https://docs.microsoft.com/en-us/sccm/compliance/plan-design/common-tasks-for-creating-and-deploying-configuration-baselines)
* Content Source: [sccm/compliance/plan-design/common-tasks-for-creating-and-deploying-configuration-baselines.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/compliance/plan-design/common-tasks-for-creating-and-deploying-configuration-baselines.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the feedback @goatmale. 
If you're willing to supply and write the example, I'm happy to review. Just click Edit on the page. 😄 For more information, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute).

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
