### ISSUE TITLE
SCCM Management Pack for HA

### ISSUE THREAD

**Issue by xstaindx** [MicrosoftDocs/SCCMdocs#716]
Is the SCCM Management Pack going to be updated to support the new HA Configuration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c416209-7476-14b2-a60b-9f3477dc79be
* Version Independent ID: 765534af-f933-c768-0994-fa8d0a5712a0
* Content: [Site server high availability - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/site-server-high-availability)
* Content Source: [sccm/core/servers/deploy/configure/site-server-high-availability.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/site-server-high-availability.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @xstaindx for taking the time to provide feedback on Configuration Manager! This is an interesting idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback]( https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. Or click the link for **Product Feedback** at the bottom of any article to go to our [UserVoice](https://configurationmanager.uservoice.com/) site.

I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
