### ISSUE TITLE
Should this not be packaged?

### ISSUE THREAD

**Issue by andykn** [MicrosoftDocs/SCCMdocs#724]
If we installed stuff manually we wouldn't need SCCM in the first place. There surely should be a console install Application created automatically.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6431e1d-681e-fcfb-8066-8491491723a8
* Version Independent ID: ba71437e-ac4b-b1f4-573b-04c397249b3a
* Content: [Install console - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/install-consoles)
* Content Source: [sccm/core/servers/deploy/install/install-consoles.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/install-consoles.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @andykn for taking the time to provide feedback on Configuration Manager! This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback]( https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
