### ISSUE TITLE
No supersedence across resource types regardless of uninstall option

### ISSUE THREAD

**Issue by tofergus** [MicrosoftDocs/SCCMdocs#725]
It would appear that supersedence is not respected for deployments to collections of different resource types even when the uninstall option is not selected on the superseding application.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1b7a162-24aa-0b1b-9f21-ee200369ce6d
* Version Independent ID: 9539b94f-a539-76bf-d1ab-a44d6fca1639
* Content: [Revise and supersede applications - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/revise-and-supersede-applications)
* Content Source: [sccm/apps/deploy-use/revise-and-supersede-applications.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/revise-and-supersede-applications.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @tofergus, let me check with engineering and get back to you.

**Comment by BinneyJ** [comment]
Any update on this?  We are seeing the same behavior (which seems to work prior to an update)  Currently we are trying to move deployments from device to user collections when a new version is released but it stopped working, uninstall not selected in the supersedence rule.  We are documenting multiple scenarios to determine what works and doesn't work as well as what the expected behavior is based on this document.  Once we have collected the data we will submit a ticket.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
