### ISSUE TITLE
Clarification of Distribution Point requirements on 2008r2

### ISSUE THREAD

**Issue by brandonjohnsen** [MicrosoftDocs/SCCMdocs#728]
Could you clarify the support-ability for 2008r2 servers as distribution points on CB?

"Beginning with version 1702, Windows Server 2008 R2 is not supported for site servers or most site system roles. However, versions prior to 1702 continue to support its use. This operating system remains supported for the distribution point site system role (including pull-distribution points, and for PXE and multicast) until deprecation of support is announced, or the operating system's extended support period expires". What about 1710/1802/1806?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87b3c5cd-5c44-267e-3135-d10817ec1044
* Version Independent ID: b670aa72-b865-380b-4891-a80edb9414b1
* Content: [Deprecated for Configuration Manager site servers - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/changes/deprecated/removed-and-deprecated-server)
* Content Source: [sccm/core/plan-design/changes/deprecated/removed-and-deprecated-server.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/changes/deprecated/removed-and-deprecated-server.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
When we say "starting in version ___" or "beginning with version ___", that means it's the first time we introduced something new. Any version later is the same, unless noted otherwise. So in this case, any version after 1702 (including 1802/1806) has the same level of support. 

Also reference the [supported configuration article](https://docs.microsoft.com/sccm/core/plan-design/configs/supported-operating-systems-for-site-system-servers#windows-server-2008-r2-with-sp1-x64-standard-enterprise-and-datacenter)

I'm closing this issue. Please reopen with additional clarification if you think a specific change is needed here.
