### ISSUE TITLE
correct/clarify Unknown max run time behavior with maintenance windows

### ISSUE THREAD

**Issue by tofergus** [MicrosoftDocs/SCCMdocs#731]
This appears to be inaccurate or incomplete:

>  if the maximum run time is set to Unknown, the program starts to run during the maintenance window and continues to run as needed after the maintenance window is closed

A program with max run time set to Unknown will not start unless the window exceeds 12 hours. Is this meant to compliment the note immediately following?

> If the maximum run time (whether set by the user or as the default value) is exceeded, Configuration Manager stops the program if run with administrative rights is selected and Allow users to view and interact with the program installation is not selected.
 
If so, perhaps they should be merged and clarified as to what happens when a program set to Unknown is still running when the >12hr. window closes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e162dd7-b731-31b4-924a-a8546fcdbdb9
* Version Independent ID: f034c24d-000f-da01-70fd-0f84bad9ac26
* Content: [Packages and programs - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/packages-and-programs)
* Content Source: [sccm/apps/deploy-use/packages-and-programs.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/packages-and-programs.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @tofergus, I agree this could be clarified.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
