### ISSUE TITLE
Any logs for "Cloud Protection Service reporting" ?

### ISSUE THREAD

**Issue by jose-camacaro** [MicrosoftDocs/SCCMdocs#764]
Are there any logs on the client side (or anywhere else) that record the cloud protection service reporting activities?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5215a151-f390-9123-5384-516ec3ed3078
* Version Independent ID: 62124728-8029-4565-79a6-88f842ad1e73
* Content: [Endpoint Protection antimalware policies - Configuration Manager](https://docs.microsoft.com/en-us/sccm/protect/deploy-use/endpoint-antimalware-policies#cloud-protection-service)
* Content Source: [sccm/protect/deploy-use/endpoint-antimalware-policies.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/endpoint-antimalware-policies.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
