### ISSUE TITLE
Is this correct under Configure a distribution point?

### ISSUE THREAD

**Issue by g4m3c4ck** [MicrosoftDocs/SCCMdocs#771]
"The distribution point must be running Windows Server, version 1709. There's no client prerequisite."

According to the referenced article, shouldn't this be Windows Server 2016 instead of Windows Server, version 1709?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b49b7692-2fba-a5b6-cc24-3b2621b7f5dd
* Version Independent ID: bbc48abf-20cb-18f4-0db4-467cb0408b30
* Content: [Manage distribution points - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/install-and-configure-distribution-points#bkmk_config-general)
* Content Source: [sccm/core/servers/deploy/configure/install-and-configure-distribution-points.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/install-and-configure-distribution-points.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @g4m3c4ck for the feedback. I'm assuming you're referring to the LEDBAT setting? The part you reference is technically accurate right now. SCCM 1806 currently only supports Windows Server version 1709 with this setting. While Server 2016 technically supports LEDBAT, it's not yet supported with SCCM. 

This issue is already tracked via issue #702, so I'm closing this issue as a duplicate.
