### ISSUE TITLE
Azure Sql and service end points

### ISSUE THREAD

**Issue by john-louden** [MicrosoftDocs/SCCMdocs#776]
Query on this article - was written before service endpoints for sql became GA. Does this change the answer around Azure SQL support?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0da69878-a841-1f05-32c2-a1fcba10506f
* Version Independent ID: 769913cc-0fa4-cd5b-b015-b7c5f38fc0d4
* Content: [Configuration Manager on Azure](https://docs.microsoft.com/en-us/sccm/core/understand/configuration-manager-on-azure)
* Content Source: [sccm/core/understand/configuration-manager-on-azure.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/configuration-manager-on-azure.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @john-louden for taking the time to provide feedback on Configuration Manager! We currently don't support Azure SQL. I suggest filing [Product feedback]( https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) to share the idea with the engineering team. (I also suggest you upvote [this idea on UserVoice](https://configurationmanager.uservoice.com/forums/300492-ideas/suggestions/8343141-suport-azure-paas-for-sql-db), which appears to be the same.) I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
