### ISSUE TITLE
Security Role permissions

### ISSUE THREAD

**Issue by jose-camacaro** [MicrosoftDocs/SCCMdocs#794]
Which Permissions in Security Roles regulate what users can/cannot do with WDAC?

I see there are explicit nodes for features likes "Windows Defender Exploit Guard" and "SMS Scripts", but I don't see any for WDAC in 1802. So I'm guessing it's probably named differently?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2082f138-28f2-d410-d607-4fcb1ddf12db
* Version Independent ID: 7ce37b4e-9330-73d9-f3bb-2f0af4ec6073
* Content: [How to manage Windows Device Guard - Configuration Manager](https://docs.microsoft.com/en-us/sccm/protect/deploy-use/use-device-guard-with-configuration-manager)
* Content Source: [sccm/protect/deploy-use/use-device-guard-with-configuration-manager.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/use-device-guard-with-configuration-manager.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
