### ISSUE TITLE
DPLocality flags wrong?

### ISSUE THREAD

**Issue by matbe** [MicrosoftDocs/SCCMdocs#847]
According to the documentation the flags are:
4=DP_DOWNLOAD_FROM_LOCAL 
6=DP_DOWNLOAD_FROM_REMOTE 
17=DP_NO_FALLBACK_UNPROTECTED 
18=DP_ALLOW_WUMU 
19=DP_ALLOW_METERED_NETWORK 

But when querying WMI and doing a bitwise comparison all the flags seem to be off with one, the correct values should be:
5=DP_DOWNLOAD_FROM_LOCAL 
7=DP_DOWNLOAD_FROM_REMOTE 
18=DP_NO_FALLBACK_UNPROTECTED 
19=DP_ALLOW_WUMU 
20=DP_ALLOW_METERED_NETWORK 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e248ac-084d-51f0-fd13-5976d8e28232
* Version Independent ID: f458c085-7b1e-16fb-7293-b7e84130fafc
* Content: [SMS_CIAssignmentBaseClass Class - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/compliance/sms_ciassignmentbaseclass-server-wmi-class)
* Content Source: [sccm/develop/reference/compliance/sms_ciassignmentbaseclass-server-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/compliance/sms_ciassignmentbaseclass-server-wmi-class.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @matbe for the feedback. I'm checking with engineering - stay tuned.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
