### ISSUE TITLE
CMG CDP Functionality Contradiction

### ISSUE THREAD

**Issue by PhillyUrbs** [MicrosoftDocs/SCCMdocs#856]
Under content storage there seem to be two contradicting bullet points.
-For any other necessary content, such as applications or third-party software updates, you must distribute to a cloud distribution point. Currently, the CMG supports only the cloud distribution point for sending content to clients.
-Starting in version 1806, a CMG can also serve content to clients. This functionality reduces the required certificates and cost of Azure VMs. For more information, see Modify a CMG.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778368d0-1054-678c-4d74-5dce1b5826c8
* Version Independent ID: aaac7308-66e6-66f0-8248-14e1505c11a6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/plan-cloud-management-gateway)
* Content Source: [sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @PhillyUrbs for the feedback. Those are two separate concepts.
- If you're deploying apps or 3p updates to internet-based clients, you need to distribute content to a CDP.
- In 1806, a CMG instance can also host a CDP role. But the behavior of that DP role should be otherwise unchanged. So in the case of the prior bullet, you still need to distribute the app or update content to a CDP. 

Can you clarify your concern about a contradiction?

**Comment by aczechowski** [comment]
Ok, I see. Fair point. Thanks for the clarification.

**Comment by aczechowski** [comment]
This issue is closed because I made a tweak to the article for this feedback. The change should publish live later today.
