### ISSUE TITLE
Task Sequence?

### ISSUE THREAD

**Issue by Krytical13** [MicrosoftDocs/SCCMdocs#865]
There is no way to use these scripts in a task sequence, which is very important in SCCM....
So we still need to go about creating packages or applications and run those in the TS.
Kind of takes away from the coolness of this feature...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c7d1db7-6812-ff3c-9aac-0f55800ed665
* Version Independent ID: a4499cf7-ed5a-710c-66e0-005563b9c015
* Content: [Create and run scripts - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/create-deploy-scripts)
* Content Source: [sccm/apps/deploy-use/create-deploy-scripts.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/create-deploy-scripts.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Krytical13 for taking the time to provide feedback on Configuration Manager! This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
