### ISSUE TITLE
Boot image selection

### ISSUE THREAD

**Issue by Yupiter2005** [MicrosoftDocs/SCCMdocs#877]
The question here is what's the choice of boot image in case we find multiple matched or compatible boot images found on step 3.

AFAIK the right answer is that we select top 1 boot image ordered by DeploymentIDs DESC: that means if we create the deployment from site ZZZ, it will overrule all other deployments :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3527c358-cf3f-07ec-1cb8-88982ff99122
* Version Independent ID: 2c618192-bb71-d934-d20e-1ceb15cb2e01
* Content: [Use PXE for OSD over the network - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/deploy-use/use-pxe-to-deploy-windows-over-the-network)
* Content Source: [sccm/osd/deploy-use/use-pxe-to-deploy-windows-over-the-network.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/use-pxe-to-deploy-windows-over-the-network.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the feedback @Yupiter2005. Let me check and followup.

**Comment by aczechowski** [comment]
Yes, it uses the "highest" or most recent deployment ID. In the case of a multi-site hierarchy, the "higher" letter site would take precedence in that string comparison. So in your example, a year-old deployment from site ZZZ would be selected over yesterday's deployment from site AAA. (In the case where they are both matched otherwise.) I think that's a good clarification to add to this article, so will use this issue to track that change.

If you think the behavior should change, please file [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback).

**Comment by aczechowski** [comment]
I revised the article and included this information. The change will be live on or about Monday, 6 May. I'm closing this issue.
