### ISSUE TITLE
How does Config Manager client determine it is internet or intranet connected?

### ISSUE THREAD

**Issue by alexledger1** [MicrosoftDocs/SCCMdocs#926]
How does Config Manager client determine it is internet or intranet connected?  Reason i ask is that i have seen machine report as being Intranet connected even though it is connected to external network.  It then fails to connect to Management Points and does not try to use CMG

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ef9884b-385c-a5c1-7449-43d3fff9d84d
* Version Independent ID: 6b0135c4-bd5e-fa24-9528-8d24a4604f01
* Content: [Manage clients on the internet - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/manage-clients-internet)
* Content Source: [sccm/core/clients/manage/manage-clients-internet.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/manage-clients-internet.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
This information is included with the specific feature. For example, from the section to [Configure clients for CMG](https://docs.microsoft.com/sccm/core/clients/manage/cmg/setup-cloud-management-gateway#configure-clients-for-cmg):

> The Configuration Manager client automatically determines whether it’s on the intranet or the internet. If the client can contact a domain controller or an on-premises management point, it sets its connection type to Currently intranet. Otherwise, it switches to Currently Internet, and uses the location of the CMG service to communicate with the site.

I'm closing this issue as this detail is already documented.

**Comment by frazeraccount** [comment]
But that doesn't say exactly HOW it attempts to contact a domain controller or an on-premises management point.  Does it try a query, does it perform a dns service record lookup?

**Comment by aczechowski** [comment]
Hi @frazeraccount, why does it matter? 😉 Clients communicate with DCs and MPs in many ways, and you're likely to have bigger problems if one of those channels isn't working.

There's a lot of technical detail about the product that we don't document, we don't have unlimited resources. So I'm just trying to determine the need for this further level of detail in this case.

**Comment by frazeraccount** [comment]
We are trying to troubleshoot an issue where BITS  jobs during the client install fail due to the following error in ccmsetup.log on some of our VPN-connected workstations:

BG error context is 2 Download Update: A recoverable error has occurred. A retry attempt will be made. Error: 0x80200010, Description There are currently no active network connections. Background Intelligent Transfer Service (BITS) will try again when an adapter is connected.

Earlier in the log there are entries that indicate “Client is on Internet” vs “Client is on Intranet”.  I was just hoping the detection method for Intranet vs Intranet being discussed here might be similar to that used by ccmsetup, and that it may give us a clue as to why BITS thinks there is no active network connection. All other network operations work normally on these clients. In fact, we can manually download the files that BITS is attempting to download by using the URL in a browser. Frustrating. 🙂

**Comment by shashank2791991** [comment]
hi any update on that, i also want to know that which servsices it exactly use, because the ind of VPN solution we use, we dont put the user on network although user will always get access to some application due to which machine alsoways shows internet and not intranet due to which Software Center does not display any user-deployed apps, as these do not appear when connected to a CMG

**Comment by frazeraccount** [comment]
Network Location Awareness was to blame.  Check HKLM\System\CurrentControlSet\Services\NlaSvc\Parameters\Internet\EnableActiveProbing.  Make sure it's set to '1' not '0'.  If you have to change to '1', it will require a restart.  BITS jobs immediately started moving through.

This registry value can be controlled with group policy:
Computer Configuration\Administrative Templates\System\Internet Communication Management\Internet Communication Settings\Turn off Windows Network Connectivity Status Indicator active tests (you would disable this setting to change EnableActiveProbing from 0 to 1)
