### ISSUE TITLE
Add list of available vendors

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#980]
Similar to the list for TP 1806: https://docs.microsoft.com/en-us/sccm/core/get-started/capabilities-in-technical-preview-1806#bkmk-3pupdate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 054797d3-c4d8-2c2e-9940-e8763f6f3881
* Version Independent ID: 9751d801-35de-ebd8-29ea-57e459f845dc
* Content: [Enable third party updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/third-party-software-updates)
* Content Source: [sccm/sum/deploy-use/third-party-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/third-party-software-updates.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by jimmyeao** [comment]
Plus one for this, before I go and spend a load on SolarWinds... If SCCM can deliver the small set of 3rd party patches I need, I would rather stick with that.

**Comment by aczechowski** [comment]
@jimmyeao we currently expose two catalogs out of the box that support this new in-console feature: HP client and Dell client. 
Note that you can still use SCUP to import older catalogs, or import a custom catalog.

**Comment by rdoloto** [comment]
@aczechowki is there way to import certs into SCCM i have some Adobe  SCUP catalog that are not in the new format.  "You can still use the older catalog cab file version as long as the download URL is https and the updates are signed. The content will fail to publish because the certificates for the binaries aren't in the cab file and already approved. You can work around this issue by finding the certificate in the Certificates node, unblocking it, then publish the update again. If you're publishing multiple updates signed with different certificates, you'll need to unblock each certificate that is used." the problem is those certs never appear in Cert MGR certificates console

**Comment by aczechowski** [comment]
@mestew might know the answer

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
