### ISSUE TITLE
Automatically remove previously installed antimalware software before Endpoint Protection is installed

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/SCCMdocs#996]
This section is missing in the new documentation , was present in the old one. 
https://docs.microsoft.com/en-us/previous-versions/system-center/system-center-2012-R2/gg682067(v=technet.10)#BKMK_EndpointProtectionDeviceSettings

please document this setting "Automatically remove previously installed antimalware software before Endpoint Protection is installed" and also add the list of products that are supported to be uninstalled. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f74f4a-560f-2510-1ae8-fd3976a2197e
* Version Independent ID: 0851f834-e9a1-d0a6-ee60-934bcd3a79fe
* Content: [Client settings - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/deploy/about-client-settings)
* Content Source: [sccm/core/clients/deploy/about-client-settings.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/about-client-settings.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
This setting was explicitly removed from the documentation in July. (Reference commit [change for bug 511544](https://github.com/MicrosoftDocs/SCCMdocs/commit/40029559d0fec66f39a0169096b00cd081f7f476#diff-b760dd47e2df15cb4bb40319bde2df1d).) The setting itself was removed in Configuration Manager version 1806. The feature team asked that the setting be removed from the documentation, due to known issues with the functionality. 
I'm closing this issue.
